### ISSUE TITLE
React 0.13

### ISSUE THREAD

**Issue by mike-thompson-day8** [reagent-project/reagent#102]
http://facebook.github.io/react/blog/2015/02/24/react-v0.13-rc1.html

**Comment by yogthos** [comment]
From the changelog it looks like 0.13 should work fine, has anybody run into any issues?

**Comment by Deraen** [comment]
React 0.13 is available from Cljsjs.

**Comment by sir-pinecone** [comment]
I've been running it in production for a few days with no issues.

**Comment by sdegutis** [comment]
Is Reagent going to use React 0.13 any time soon? The source currently says it uses 0.12.

**Comment by hura** [comment]
FYI: You can always use leiningen's `:exclusion` and pull it in yourself.

**Comment by sdegutis** [comment]
@hura right, thanks; see my comment's edit

**Comment by yogthos** [comment]
Reagent appears to work fine with React 0.13, it's what the reagent-template currently defaults to. If any specific bugs are found with using React 0.13 then a separate issue should be opened for them.
