### ISSUE TITLE
Accidental Infinite Re-rendering due to Reagent overwriting Clojure atom

### ISSUE THREAD

**Issue by marcloyal3** [reagent-project/reagent#103]
Problem:
Reagent atom overwriting Clojure atom can cause accidental re-rendering when dereferenced inside Reagent component even if it is not part of the component state (e.g. atom used for updating a counter logging) 

Question:
Is this by design, a bug, or both? Are we supposed to use a counter function in this case? I'm personally tempted to use the Clojure atom for quickly adding counters and boolean states for debugging different parts of the component code... but I realize we're working with Clojure and hence use of a counter function (via a closure) would be more appropriate. 

But can we have Reagent provide a differently named "atom" (e.g. "ratom")? Alternatively, can we refer to the Reagent atom (or otherwise use it) by a different name? Would that lead to a much bigger issue?

Here is a video to show that incrementing and dereferencing a Reagent atom (by accident, the require for Reagent is not needed but was left over from a previous experiment) inside of a Reagent component will cause infinite re-rendering. I had meant to use a regular atom.

https://www.youtube.com/watch?v=1XWk8X4hjwI

Will be happy to post relevant portions of the code but I think the video conveys the problem.

**Comment by seancorfield** [comment]
It's much safer to just `(:require [reagent.core :as r])` and then use `r/atom` where you need it. `:refer` should be used with care -- for exactly this reason -- and it's why people advise against `:use` as well.

**Comment by seancorfield** [comment]
BTW, this is how Clojure(Script) works for any library that contains a symbol that would shadow / overwrite a core symbol -- namespaces are intended for such differentiation.

**Comment by marcloyal3** [comment]
Ok, thank you Sean. That is great knowledge to have. Closing and updating our coding practice around that...!
