### ISSUE TITLE
HTML special characters

### ISSUE THREAD

**Issue by sundbry** [reagent-project/reagent#104]
How do I insert HTML special characters into an element?

    (defn my-blank-component []
      [:div "&nbsp;"])

This renders as the literal string "&amp;nbsp;" (the HTML entity gets escaped to "&amp;amp;nbsp;"). Do we have support for inserting unescaped strings?

Thanks.

**Comment by yayitswei** [comment]
Try this:

```Clojure
(defn my-blank-component []
  [:div
    {:dangerouslySetInnerHTML {:__html "&nbsp;"}}])
```

**Comment by hzhu** [comment]
Also try https://github.com/davidsantiago/hickory

You can parse HTML / entities into Hiccup: 

`(parse-fragment "&lArr;")`
`(parse-fragment "&nbsp;")`

**Comment by marcloyal3** [comment]
Require Closure's string object, like so:
(:require [goog.string :as gstring])

Then:
[:div (gstring/unescapeEntities "&nbsp;")  ]

Or to insert within a sentence, wrap the string fragments in str, like so:
[:div (str "hello world" (gstring/unescapeEntities "&nbsp;") ) ]

**Comment by JulianLeviston** [comment]
This should now be closed, @sundbry

**Comment by sundbry** [comment]
@julianleviston yup. Thanks everyone.
