### ISSUE TITLE
should-component-update required when vector prop is passed?

### ISSUE THREAD

**Issue by arnaudbos** [reagent-project/reagent#108]
Hi guys,

I'm not sure of what's happening, but I'm having an issue where I pass a vector as a prop of children components and all the components get re-rendered at every change...

I'm not really good at describing it, so I took the todo-app example of the reagent page and created a gist with 2 updates that you can find here: https://gist.github.com/arnaudbos/8f4d53020d941af5a5cb/revisions

Version 1:

Scroll to the bottom of the page to see the first version which is a simple copy/paste of the example found on the reagent presentation page.
Everything work as expected.

Version 2:

I've wrapped todo-item and todo-app components in "with-meta" for debugging purposes and added logs in the rendering fns.
I have also changed the `(for [todo ...] [todo-item todo])` part to a `map-indexed` and added a key `:path` to the todo, because this is what I'm trying to do in my project: give its path in the datastructure to the child component.
Everything still works as expected.

Version 3:

Now I just change the `:path` value to `[i]` instead of just `i`, and this is where it gets confusing.
If I do not implement the :should-component-update with something as simple as `(not= old-argv new-argv)`, all the todo-item are updated an re-rendered. Just because I changed a prop to a vector.

Is this the expected behavior? Am I messing up with something?

Thanks!

**Comment by holmsand** [comment]
I'm guessing you're pre-0.5.0 Reagent?

Reagent 0.5.0 should work as you expected: :should-component-update is now basically just `(not= old-argv new-argv))`.

**Comment by arnaudbos** [comment]
Yes, 0.4.2. I'll test it with 0.5.0.

**Comment by mike-thompson-day8** [comment]
Is there any further information?  Can this issue be closed?

**Comment by mike-thompson-day8** [comment]
Without an answer I'm going to close.
