### ISSUE TITLE
Should reagent perhaps not use cljsjs/react?

### ISSUE THREAD

**Issue by Skinney** [reagent-project/reagent#109]
Maybe it should be up to the users of reagent to specify how react is bundled, and instead do some runtime checking to make sure the user has bundled (a correct version of) react?

**Comment by Deraen** [comment]
The dependencies on JS libraries should be thought the same as dependencies on Clj/Cljs libraries, meaning that library should depend on JS libraries it uses.

User can however use Maven exclusions to remove the dependency and `deps.cljs` file to define what file should be used to provide `cljsjs.react` namespace.

**Comment by Gonzih** [comment]
I like that reagent nowadays depends only on cljsjs.react namespace, it's simple solution that just works.

**Comment by city41** [comment]
I'm on the opposite side, I agree with Skinney that Reagent should not have a dependency on React. 

To remove the React dependency, I added cljsjs/react.cljs to my project which just has a namespace in it. Then do `[reagent "0.5.0-alpha3" :exclusions [cljsjs/react]]`. This does work, but it just doesn't seem right that a hack should be needed. I feel providing our own deps.cljs is also a hack.

I don't think JS libraries should be treated the same as cljs libraries, because when you do you lose all advantages of caching and CDNs.

**Comment by Gonzih** [comment]
with cljsjs/react dependency you can get benefits of clojurescript modules for example. Also it feels more idiomatic.

Could you please explain more "advantages of caching and CDN"? I don't see really big gain here if you are already serving your compiled clojurescript code in a proper way.

**Comment by city41** [comment]
React is a large library. So to bundle it in with your ClojureScript and serve it all as one package is not as performant as serving it on its own, let it get cached, and then your user never downloads it again. Throughout the life of a project, React itself essentially won't change at all, but the app will. So to force the user to keep re-downloading the React bits does not make very much sense.

**Comment by Gonzih** [comment]
@city41 you can define module that contains only cljsjs/react namespace in it (:modules configuration option for cljs compiler).

**Comment by city41** [comment]
Another problem with packaging React with Reagent is it makes it harder to use native React components. For example I grabbed Khan Academy's [TimeoutTransitionGroup](https://github.com/Khan/react-components/blob/master/js/timeout-transition-group.jsx). Rather than port it to cljs (which granted, I ultimately will do at some point) I use it in its JS form. This requires React to be on the page before TimeoutTransitionGroup, which is not possible when React is bundled with Reagent.

> you can define module that contains only cljsjs/react namespace in it (:modules configuration option for cljs compiler).

I know, and that's basically what I'm doing. But I just disagree with this. I feel webapps, even cljs based ones, have too much variety and needs and the safest route is to expect the consumer to provide React.

**Comment by Gonzih** [comment]
For external components I load them after all my cljs modules are loaded. But in my case initialization call for components happens from inside component container after server side rendered markup is in-lined.

You can of course move react to separate closure module and after you load this module load your external dependency. Or try to use :foreign-libs.

I was also not happy about direct dependency at first, but honestly saying now I'm realizing that tools where there all this time and I was just trying to fight them.

**Comment by city41** [comment]
That's also possible. Everything I need to do is currently possible, so ultimately this isn't all *that* important. It just feels like jumping through a lot of unnecessary hoops with essentially no gain. For those who like React being provided by cljsjs, it's one line in their project.clj and one require. It's more explicit too.

**Comment by Gonzih** [comment]
that is totally true

**Comment by holmsand** [comment]
I totally agree with the arguments against including cljsjs/react automatically – but I still think it's the right thing to do… My reasoning is this: using the default React is probably the most common case, and in particular it is almost certainly most common for beginners, who might be inclined to mismatch versions and do all kinds of crazy things :)

So I think it is more important to make life as easy as possible for them, at the price of complicating things for more advanced users (who, hopefully, will be able to jump through a couple of hoops to get their custom setup working). It's a compromise, but I still think it's the right one.

It would be great, though, if there was a cljsjs/no-react (or some such) package somewhere – i.e. a package that provides the cljsjs/react namespace, without including react.js, and ideally the same externs. That would make it slightly less ugly to exclude the React dependency.

**Comment by ilazarte** [comment]
I'm always trying libraries for which no cljsjs entries exist and I don't expect them to.  Given how large the node/javascript community is, I expect that will be a very common scenario.

**Comment by ilazarte** [comment]
I ended up going with cljsjs but only because reagent forces it on me and I'm not into creating empty namespaces just to handle a libraries expectation.  I hope this decision is revisited.

**Comment by Gonzih** [comment]
How would you load react otherwise? What is preferable way for you?

**Comment by ilazarte** [comment]
There are two decent options.  One is webjars.org which contains a ton of not so common libs (for example I'm currently exploring materializecss for my styling - I always check there first.  A larger universe can be pulled in via lein-npm, which allows you to configure npm packages like standard lein deps except under a different key.  Finally, there is lein-bower which gives you access to bower packages.  After I get my resources,  I manually insert the js ref into templates - usually just one function in my experience (moderately serious hobbyist stuff).  

I understand this isn't optimized, but I feel that it allows you a lot of convenient flexibility.

**Comment by Deraen** [comment]
@ilazarte The reason why Cljsjs is exists is that libraries without extern files are pretty useless with Cljs. This means that JS libraries from Webjars are not easily usable with Cljs. For some libraries the missing extern might not be a problem if the library only exports a few functions (you could use https://github.com/myguidingstar/fence or just `aget`), but for libraries like React which have quite large API it would be really inconvenient.
Another deficiency with Webjars is the packages don't have depenendencies, e.g. jquery plugins don't depend on jquery.

Btw. in future it might be possible to use CommonJS libraries with Cljs: http://dev.clojure.org/jira/browse/CLJS-1044 http://dev.clojure.org/jira/browse/CLJS-1092

**Comment by Gonzih** [comment]
@ilazarte I use webjars on my own, it's better than using something else, but still I would preffer to have packages that I need in cljsjs repo. Much move convinient.

**Comment by city41** [comment]
All of this really boils down to some pretty core design choices of ClojureScript itself. Reagent is definitely not alone in having this debate. So I'd argue of the two choices, core Reagent devs should choose the approach they prefer and we just roll with the decision. Ultimately it'd be nice if ClojureScript itself had a really good story for Closure/externs/CommonJS/and standalone JS script files. And I have no doubt at all cljs will get there.

**Comment by yogthos** [comment]
I would say it's safe to close this one. It's currently possible to add cljsjs dependencies to the project and use the react from those. The reagent-template provides React 0.13 using that method.
