### ISSUE TITLE
BMI calculator example is buggy

### ISSUE THREAD

**Issue by hura** [reagent-project/reagent#110]
When I change BMI slider and then change the height. The weight & BMI jumps to 0 (and the sliders are off).

**Comment by holmsand** [comment]
Thanks, should be fixed now.

**Comment by hura** [comment]
Unrelated, but just wondering: Is there a reason you're using `(-> % .-target .-value)` instead of `(.. % -target -value)`. I think `(..)` is exactly made for that. I've noticed other projects also pick this up.

**Comment by hura** [comment]
Btw, I don't think this is fixed. Now the value jumps all around.

**Comment by Frozenlock** [comment]
`(..)` was created at Clojure inception.

The threading macro `->` was added later and is considered a little more idiomatic. (It works for everything.)

**Comment by hura** [comment]
Does it compile to the same?

**Comment by holmsand** [comment]
@hura Yes, it will use the last input set by the user (by design, I might add...).

**Comment by hura** [comment]
@holmsand do this:
1. Move the Weight
2. Move the BMI
3. Move the Height

Notice at step 3 that the weight & BMI will jump. I don't think that's intuitive if that's the intended behavior.
