### ISSUE TITLE
Reloading with figwheel is inconsistent 

### ISSUE THREAD

**Issue by torbjornvatn** [reagent-project/reagent#112]
I'm trying to do somthing similar to the input field example at http://reagent-project.github.io/ but the figwheel reloading is not working as expected.

When I do it like this: 

```clojure
(defn search-component []
  (let [searched-for (atom "rive")]
    (fn []
      [:div
       [:p "Du er på jakt etter en: " @searched-for]
       [:p "Hva vil du låne? " 
        [:input {:type "text"
                 :value @searched-for
                 :on-change #(reset! searched-for (-> % .-target .-value))}]]])))

(defn home-page []
  [search-component])
```
Changing the text in the :p triggers a figwheel reload and rerendering. 

If I do it like this however:

```clojure 
(defn home-page []
  (let [searched-for (atom "rive")]
    (fn []
      [:div
       [:p "Du er på jakt etter en: " @searched-for]
       [:p "Hva vil du låne? " 
        [:input {:type "text"
                 :value @searched-for
                 :on-change #(reset! searched-for (-> % .-target .-value))}]]])))
```
a text change will trigger a figwheel reload, but the change doesn't appear on the webpage.

**Any advice?**

Ps: I'm having the same issues if I copy/paste the example from the webpage as well.

**Comment by mike-thompson-day8** [comment]
A duplicate of #94?

See latest docs:  https://github.com/reagent-project/reagent/blob/master/src/reagent/core.cljs#L100-L104

**Comment by torbjornvatn** [comment]
Yes, it seems to be a duplicate. Sorry for that!

Tried to follow @holmsand 's advise of using ```#'``` by adding it to the init!-function 
```clojure
;; -------------------------
;; Initialize app
(defn init! []
  (hook-browser-navigation!)
  (reagent/render [#'current-page] (.getElementById js/document "app")))
```
but it made no difference as I far as I could see

**Comment by mike-thompson-day8** [comment]
No need to apologize, I think it's an annoying and baffling little problem.  We certainly got caught by this too. 

@holmsand I still believe this is problem, despite the improved docs. This is going to catch a lot of people out, and burn a lot of time.  In the meantime, I'm going to ask the template writers to highlight this problem.

**Comment by holmsand** [comment]
@torbjornvatn Are you sure that `init!` is actually called when figwheel does its reloading? Or are you using `force-update-all` (in which case: are you sure that that is actually called when figwheel reloads)?

@mike-thompson-day8 Yes, I agree. The only "solution" I can think of is to make the templates and examples out there not use `force-update-all`...

**Comment by torbjornvatn** [comment]
@holmsand https://github.com/reagent-project/reagent/blob/master/src/reagent/core.cljs#L100-L104 refers to using ```(render [#'foo])``` to mount components, and as the ```init!```function was the only place I could find a ```reagent/render``` call I thought it would do the trick.

But now I see that this function of course is called only at startup, so I'm not sure where to apply the ```#'```trick to make it affect the ```force-update-all``` call from figwheel

**Comment by gadfly361** [comment]
@torbjornvatn Would you mind seeing if you get the same problem with [reagent-figwheel](https://github.com/gadfly361/reagent-figwheel)?  I tried reproducing the problem, but wasn't able to.

**Comment by torbjornvatn** [comment]
@gadfly361 reagent-figwheel doesn't work in the same way bacause your ```watch-and-reload``` looks like this:
```clojure
(figwheel/watch-and-reload
  :websocket-url "ws://localhost:3449/figwheel-ws"
  :jsload-callback (fn [] (core/main)))
```

when I change it to:
```clojure
(figwheel/watch-and-reload
  :websocket-url "ws://localhost:3449/figwheel-ws"
  :jsload-callback (fn [] (r/force-update-all)))
```
I hit the same issue.

I'd like to know the pros and cons of using ```:jsload-callback (fn [] (core/main))``` vs. ```:jsload-callback (fn [] (r/force-update-all))```

**Comment by mike-thompson-day8** [comment]
@torbjornvatn  It works like this:
1.  When you call `reagent/render`,reagent keeps a reference to the root component you supply. That's a reference to `home-page` in your case. 
2.  If you later call `force-update-all`, reagent starts at the remembered root component and re-renders the entire tree underneath it.  

Trouble is that reagent is remembering (holding a reference to) the original `home-page`, and it doesn't know about the new version of `home-page` loaded by figwheel. So when `force-update-all` is called,  reagent will re-render the original one (the one provided in the original call to `reagent/render`).  And that's why you see no change in it. 

So calling `force-update-all` will always have this problem.  Best not to use it. 

The reagent-figwheel approach is the correct approach.  Look in `core/main` and you'll see that it just calls `reagent/render`  again.  So it doesn't ask for a re-render, it just completely re-mounts the root component `home-page` via a call to `reagent/render`,  and so it picks up the new version of `home-page`. 

Do this (untested).  Split `init!` in two so you can re-mount:

```
(defn mount-root []
     (reagent/render [current-page] (.getElementById js/document "app"))

(figwheel/watch-and-reload
  :websocket-url "ws://localhost:3449/figwheel-ws"
  :jsload-callback mount-root)            ;;   <-----  

;; Initialize app
(defn init! []
  (hook-browser-navigation!)
  (mount-root))                                    ;; <---- 
```

**Comment by mike-thompson-day8** [comment]
@torbjornvatn are you happy to close this?  

@yogthos has [tweaked `reagent-template`](https://github.com/reagent-project/reagent-template/commit/b0a0d61ae571c892cb0399f0d1d8f5435ec9e6ba), so this issue should become a thing of the past.

**Comment by torbjornvatn** [comment]
Tnx @yogthos, @mike-thompson-day8 and @holmsand !
