### ISSUE TITLE
support for live-preview file type input in examples

### ISSUE THREAD

**Issue by JulianLeviston** [reagent-project/reagent#115]
I'm switching a project from Om to Reagent.

One of the things the project does is allows file uploads with live image previews. Could you please amend the examples so that they illustrate how to do this? In Om it was necessary to use an "uncontrolled" component and a ref to the underlying HTML element, as below, so that an "uncontrolled" img tag could have its URL field set to the raw data properly and React wouldn't try to manage it.

I'm actually not even sure how to approach this in Reagent, tho I understand how it works in Om or vanilla React. Would you be able to direct me here a little as well as improve the examples a bit?

    (defcomponent file-selector
      [{:keys [editing-item comm ui] :as state} owner]
      (render [_]
        (dom/div
           (dom/input {:type "file" ; ensure you don't have any om managed state in here, otherwise it won't work propely
                       :ref "file"} nil)
           (when-not (coll? (:item_file editing-item)) (dom/img {:src (:item_file editing-item)} nil))))
      (did-mount [_]
        ; Set up the onchange handler
        (set! (.-onchange (om/get-node owner "file")) (b/change-file :item_file comm ui)))
      (will-unmount [_]
        ; Reset the files attribute as a blank native array
        ; This will work for most browsers. We need to do this for the case where
        ; where we select a file, then press cancel, then come back and do it again - it should be cleared
        (set! (.-value (om/get-node owner "file")) "")))

**Comment by JulianLeviston** [comment]
I should mention, I'm (re)creating a local-preview file upload control.

**Comment by JulianLeviston** [comment]
and this is the contents of the change-file function, for reference:

    (defn change-file
    	[fieldname comm ui]
    	(fn [event]
    		(let [file (first (into [] (array-seq (.. event -target -files))))]
    			(put! comm [:on-change {:fieldname fieldname
    															:ui ui
    															:comm comm
    															:value file}])
    			(let [file-reader (js/FileReader.)]
    				(set! (.-onload file-reader)
    					(fn [loadEvent]
    						(put! comm [:on-change {:fieldname fieldname
    																		:ui ui
    																		:comm comm
    																		:value (-> loadEvent .-target .-result)}])))
    				(.readAsDataURL file-reader file))
    			)))

**Comment by antishok** [comment]
This seems to work fine for me: 
```clojure
[:input {:type "file" :on-change change-handler}]
```

**Comment by JulianLeviston** [comment]
Apologies @antishok I didn't make myself clear enough, it seems. I've amended the title of this issue to be a bit clearer.

Your example works fine for standard file uploads, but I'm not using a form to upload a file, I'm using a deferred AJAX upload, so I have to get the data out, and I also want to have a live preview.

I can get the file data out just fine, but I can't set the "live preview" img tag's src attribute to the uuencoded data because the img tag is managed.. the pertinent bit of info is here:

             (when-not (coll? (:item_file editing-item)) (dom/img {:src (:item_file editing-item)} nil))

or, in Reagent syntax, it now looks like this (note the last two lines):

    (defn file-selector
      [editing-item-cursor]
      [:div [:input {:type "file"
                     :onChange (b/change-file :item-file editing-item-cursor)}
            (when-not (coll? (:item_file @editing-item-cursor))
              [img {:src (:item_file @editing-item-cursor)} nil])]])

**Comment by JulianLeviston** [comment]
I've also amended the wording of my original issue so it reads better as to what the code does.

**Comment by antishok** [comment]
I still don't see where the problem is. This works fine for me, doing more or less the same as you did:
```clojure
(def preview-src (r/atom ""))

(defn file-selector []
  [:div 
   [:input {:type "file" 
            :on-change (fn [e]
                        (let [file (first (array-seq (.. e -target -files)))
                              file-reader (js/FileReader.)]
                          (set! (.-onload file-reader)
                                (fn [e] 
                                  (reset! preview-src (-> e .-target .-result))))
                          (.readAsDataURL file-reader file)))}]
   [:img {:src @preview-src}]])
```

**Comment by JulianLeviston** [comment]
@antishok thankyou so much for taking the time to investigate this. It turns out I had 3 bugs (misnaming was the prime culprit) that ended up in the same behaviour as the issue that was present in Om. I've fixed the bugs, and it works now. I'll close this issue. Sorry for the noise everyone. Reagent rocks, and so do you.
