### ISSUE TITLE
Prefixed attributes

### ISSUE THREAD

**Issue by NoxDeleo** [reagent-project/reagent#121]
How would you go about using a prefixed attribute, for example xlink:href in SVG image tag?

**Comment by yayitswei** [comment]
I don't think prefixed attributes are supported in React: https://github.com/facebook/react/issues/1657

I have a clunky workaround- you pass this function a reagent component and it replaces "href" with "xlink:href".

```Clojure
(defn img-with-href [[elem-type props :as elem]]
  (let [image-elem [elem-type (select-keys props #{:href :height :width})]
        image-elem-html (clojure.string/replace
                         (reagent/render-to-static-markup image-elem)
                         "href" "xlink:href")]
    [:svg
     (merge props
            {:dangerouslySetInnerHTML {:__html image-elem-html}})]))
```

Would like to see what others are doing.

**Comment by NoxDeleo** [comment]
Thanks for the workaround. Hopefully the functionality will get patched into React at some point, but for the time being I'm just glad there's a way to do it.

**Comment by mike-thompson-day8** [comment]
Can this issue be closed?

**Comment by NoxDeleo** [comment]
Yeah, sorry, I should have closed it before. Was just waiting to see if anyone else had input.

**Comment by yochannah** [comment]
March 2016 update (Leaving this here for any future people who find this issue): 

React > 0.14 supports "xlink:href" more effectively. See http://stackoverflow.com/questions/26815738/svg-use-tag-and-reactjs. 

The current non-alpha reagent version is [0.5.1](https://reagent-project.github.io/news/news051.html) which uses react 0.13.3, which isn't up-to-date enough - but hope is in sight if you use the [alpha 0.6.0 Reagent version, which *does* use an up-to-date-enough version of React](https://reagent-project.github.io/news/news060-alpha.html).
