### ISSUE TITLE
clojure 1.7.0 warning

### ISSUE THREAD

**Issue by mike-thompson-day8** [reagent-project/reagent#125]
Using this dependency:
    `[org.clojure/clojure "1.7.0-beta2"]`

this compiler warning is produced:  
```
run! already refers to: #'clojure.core/run! in namespace: reagent.ratom, being replaced by: #'reagent.ratom/run!`
```

**Comment by mike-thompson-day8** [comment]
Just to save on a few google searches ...  

It turns out that clojure 1.7.0 has a new function `clojure.core/run!`  
https://github.com/clojure/clojure/blob/clojure-1.7.0-beta2/src/clj/clojure/core.clj#L7363-L7368

**Comment by seancorfield** [comment]
FYI, `update` and `cat` are also new in 1.7.0 and those caused a lot of library warnings as well.

**Comment by JulianLeviston** [comment]
Odd. I wonder why I don't get those warnings. Is this actually a namespacing issue, in which case, can it be closed?

**Comment by mike-thompson-day8** [comment]
To see it, you have to be requiring the macros in `reagent.ratom`

**Comment by JulianLeviston** [comment]
Ok thanks. Please excuse the noise then! :)

**Comment by yayitswei** [comment]
I'm seeing this warning as well. `run!` is an unfortunate name for a core function because quite a few libraries have a run! function.

**Comment by Frozenlock** [comment]
There's `:refer-clojure` for this purpose:
https://clojuredocs.org/clojure.core/refer-clojure

**Comment by skrat** [comment]
Quick grep reveals that this macro is only used in test suite. Why not moving there then?

**Comment by mike-thompson-day8** [comment]
It has has been used by many. Just like `reaction`

**Comment by yogthos** [comment]
@mike-thompson-day8 I'm not seeing the warning with the latest, is this still a problem?

**Comment by danielcompton** [comment]
(On behalf of Mike) nope, looks like it was fixed in https://github.com/reagent-project/reagent/commit/569322949b31921a5eeedb4158414da86027ea49.
