### ISSUE TITLE
[:input] without attributes causes TypeError

### ISSUE THREAD

**Issue by cemerick** [reagent-project/reagent#129]
If a component function returns content that includes a "bare" `[:input]` (i.e. no attributes or inner content), this error is shown in the console and rendering halts:

```
Uncaught TypeError: Cannot read property 'hasOwnProperty' of null
(anonymous function) @ template.cljs:112
reagent$impl$template$input_render_setup @ template.cljs:112
(anonymous function) @ template.cljs:139
(anonymous function) @ component.cljs:40reagent$impl$component$do_render @ component.cljs:41
(anonymous function) @ component.cljs:57
reagent$ratom$capture_derefed @ ratom.cljs:17
reagent$impl$batching$run_reactively @ batching.cljs:95
(anonymous function) @ component.cljs:57
(anonymous function) @ react.inc.js:6578
```

I can understand `[:input]` not being a valid element as far as reagent/react is concerned, but the (lack of a useful) error message made it tough to discover what was causing the problem after an extended period of editing & not running the app.

This is with v0.5.0, CLJS 0.0-3269, Clojure 1.7.0-beta2. Thanks for the useful library, BTW. :-)

**Comment by rhacker** [comment]
I have the same error, if I put any attributes in it, it works.

**Comment by mike-thompson-day8** [comment]
Fixed by @holmsand in https://github.com/reagent-project/reagent/commit/63515236cbcdf255c391272bc9171eb47d3b2a80.  Will be a part of the 0.6.0 release.
