### ISSUE TITLE
Figwheel duplicates components when using component-did-mount

### ISSUE THREAD

**Issue by tdavis** [reagent-project/reagent#131]
I have a component:

```clojure
(defn navbar-component []
  (reagent/create-class {:reagent-render navbar-dom
                         :component-did-mount #(.foundation (js/$ js/document))}))
;; ...
(defn mount-components []
  (reagent/render-component [navbar-component] 
    (.getElementById js/document "navbar-content"))
  (reagent/render-component [page] (.getElementById js/document "app")))

(defn init! []
  (secretary/set-config! :prefix "#")
  (session/put! :page :home)
  (mount-components))

```

Every time I change this file and figwheel reloads the page, I end up with a duplicate navigation bar rendered next to the previous one. This didn't happen until I started using ``component-did-mount``, and only seems to happen there if the function in question modifies the DOM in some way; a simple console log doesn't cause the duplication.

Has anyone noticed this before? Is there any easy way to hack around the issue like by having figwheel clear the container element before the reload?

**Comment by zarkone** [comment]
Figwheel suggests to write reloadable code. Seems like the issue is because this code isn't...
Also, in `env/dev/...../dev.cljs` there is the code: 
```clojure
(figwheel/watch-and-reload
  :websocket-url "ws://localhost:3000/figwheel-ws"
  :jsload-callback (fn [] (r/force-update-all)))
```
May be this can help too, you can redefince jsload-callback in the way you want.

**Comment by mike-thompson-day8** [comment]
Never use `force-update-all`
https://github.com/reagent-project/reagent/issues/94
Other related: https://github.com/reagent-project/reagent/issues/153#issuecomment-118449228

**Comment by zarkone** [comment]
Thanks @mike-thompson-day8 ! It seems like I used the snippet from the old project(with accordingly old template used). In my newer projects i have `:jsload-callback core/mount-root` instead. Didn't know about the problem, thank for the correction.
