### ISSUE TITLE
Reagent Mobile UI Framework - perhaps a bridge to famo.us?

### ISSUE THREAD

**Issue by luposlip** [reagent-project/reagent#132]
Hi there,

May famo.us be the answer for a reagent based mobile UI?
Perhaps based upon the work from https://github.com/pilwon/react-famous?

I know this is more like a feature - or perhaps even repo - request. But I couldn't find any obvious place to put this question.

Henrik

**Comment by sonwh98** [comment]
I am also interested in this question

**Comment by alanmeira** [comment]
Doesn't Famo.us funcionalities overlaps React ones, mainly in virtual dom concerns?
I'm looking for a good UI solution too, like this one: https://github.com/callemall/material-ui
And this looks promising too: https://github.com/touchstonejs/touchstonejs

**Comment by luposlip** [comment]
Perhaps you're right @alanmeira. But it should be possible to wire these two.

In the mean time I've started using a combination of Reagent and OnsenUI. You can take a peek here if you wish - it's a work in progress:
https://github.com/enterlab/cordevicljs (Cordova, Device and CLJS).

Comments/suggestions are welcome. I'd be happy to get rid of Angular and still get the native-like performance like now.

But what I'm looking for in the longer run is a "official" Reagent Mobile UI.

**Comment by sonwh98** [comment]
Dom manipulation is a source of performance problems so Famous uses its own definition of a render tree using a scene graph and  creates a flat and static dom. All the visual affects are done with css. React on the other hand minimizes dom manipulation by diffing the virtual dom. The two can work well together.  I created infamous to try to integrate the two. See https://github.com/sonwh98/infamous

**Comment by JulianLeviston** [comment]
Man... this confused me for about 4 minutes just now. "Mobile UI" does *not* mean "Native Mobile UI" to me! A webpage can definitely have a UI! :P 

It'd be nice if you could slip the word "native" in there somewhere.

On the other hand, I'm even more confused because infamous appears to simply be a less popular version of freactive... (sorry @sonwh98).

**Comment by sonwh98** [comment]
@julianleviston I was unaware of freactive but its not the same as infamous. Infamous is a DSL for famous.js but I want to incorporate reagent/react into it

**Comment by JulianLeviston** [comment]
I'm still at a loss as to what this has to do with Native Mobile development. It appears to be a JS framework. Why would we use this, when we have Reagent?

**Comment by sonwh98** [comment]
Sorry didn't realize this thread was about native developments. I thought it was for using famous and react for mobile web

**Comment by JulianLeviston** [comment]
@sonwh98 I'm not convinced it's to do with native, actually. Given that reagent is based on React, I'm a bit unsure what famous would have to do with it. It's a bit confusing to me.

**Comment by mike-thompson-day8** [comment]
I'm tempted to close this issue unless anyone has more to add or propose further actions.

**Comment by luposlip** [comment]
Sorry for not getting back until now. This thread was NOT about native development, but about having/getting a "standard" Reagent-backed Mobile UI framework..

**Comment by GetContented** [comment]
@luposlip so, that means a Mobile *WEB* UI framework?

**Comment by GetContented** [comment]
That's not part of reagent proper in that case, is it.

**Comment by luposlip** [comment]
Yes @GetContented, a Mobile web UI framework. But if someone had made a framework for React Native using Reagent that would be just as nice. What I hoped to find was sort of a "bootstrap" for mobile applications built with Reagent.

And you're right, it should be its own sub project under reagent-project, didn't know where else to put my request/question.

**Comment by GetContented** [comment]
Someone HAS made a web framework using reactive. https://github.com/Day8/re-com there's also the cookbook. Reagent is already kind of "easy mode" for web dev. I'm not really sure what else you would need...

**Comment by luposlip** [comment]
OnsenUI v2 actually has react components now:
https://onsen.io/v2/react.html

I just don't know exactly how to integrate them into my existing reagent-app.
