### ISSUE TITLE
Ratom with plain JS Object

### ISSUE THREAD

**Issue by huxley-source** [reagent-project/reagent#133]
Is it possible to use ratom  with a JavaScript object/array? I have a large array with rows similar to 
```#js [ #js {a 1} #js {a 2}].```

 I have used arrays and JavaScript objects because of the very large number of calculations, but now there is a problem, ```reaction``` at each ```deref``` recalculate value. Is it possible workaround? js->clj takes several seconds ...

**Comment by mike-thompson-day8** [comment]
I believe the short answer is "no".  

The longer answer goes a bit like this:  reagent can have no way of knowing if a mutable js data structure has changed.  Without this knowledge, reagent can't then propagate changes through a multi-step signal graph.  

There might be ways of faking the arrangement.  Your code could change the js objects and then, after the changes are completed, deliberately change some aspect of the immutable state, to trigger state propagation. 

I'm going to close this issue for the moment.  Let's discuss in the normal Q/A channels like: clojarians or google groups.
