### ISSUE TITLE
Stripe checkout and 3rd party JS load

### ISSUE THREAD

**Issue by siscia** [reagent-project/reagent#134]
Hi everybody,

I am extremely new to reagent, so forgive my naiveness.

I am trying to load a [stripe checkout](https://stripe.com/docs/checkout) form in a page that I render with Reagent, however it seems like it does nothing.

``` clojure 
(defn stripe []
  [:div
   [:h2 "Payment"]
   [:form {:action "/charge" :method "POST"} 
    [:script.stripe-button
     {:src "https://checkout.stripe.com/checkout.js"
      :data-key "pk_test_6pRNASCoBOKtIshFeQd4XMUh"
      :data-name "Stripe.com"
      :data-description "2 widgets"
      :data-amount "2000"}]]])
```

With render into:

``` html
<h2 data-reactid=".0.0.0">Payment</h2>
  <form action="/charge" method="POST" data-reactid=".0.0.1">
    <script src="https://checkout.stripe.com/checkout.js" 
            class="stripe-button" 
            data-key="pk_test_6pRNASCoBOKtIshFeQd4XMUh" 
            data-name="Stripe.com" 
            data-description="2 widgets" 
            data-amount="2000" 
            data-reactid=".0.0.1.0">
    </script>
  </form>
```

That seems fine to me if compared with the one provide in the [documentation](https://stripe.com/docs/checkout#integration-simple).

However the render is a little disappointing...
![reagent-stripe](https://cloud.githubusercontent.com/assets/640555/7766494/fc70d62a-0069-11e5-8ae2-cc128a704776.png)

There is a way around this ?

Thanks for your time,

**Comment by rukor** [comment]
I may be wrong, but I think you need to use the JS call instead.

**Comment by VFe** [comment]
Yeah, this is something that frustrated me for a long time. Basically the way that checkout.js functions is incompatible with the way reagent renders.  checkout.js is looking for the element it's contained within because it populates the html of the form. 

You basically have to use a custom form so you can guarantee it renders and can generate the token if using clojurescript.

**Comment by VFe** [comment]
Moments after writing why it can't work like that, you can force load the js before the render and it'll work.

Working example:

    (defn stripez []
      (goog.net.jsloader.load "https://checkout.stripe.com/v2/checkout.js")
        [:form {:action "" , :method "POST"}  
         [:script {
               :src "https://checkout.stripe.com/checkout.js", 
               :class "stripe-button", 
               :data-key aToken",
               :data-amount "2000", :data-name "Demo Site", 
               :data-description "2 widgets ($20.00)", 
               :data-image "/128x128.png"}]])

**Comment by coyotespike** [comment]
Thanks, @VFe! Usually we'd have to load the JS source on the Clojure side, so that it is present in the HTML when we try to use it on the ClojureScript side. Your solution makes this much easier, because we don't have to create the modal window or anything.

I think this issue can be closed.
