### ISSUE TITLE
Strange bug with cursor and :on-blur

### ISSUE THREAD

**Issue by Deraen** [reagent-project/reagent#135]
Hi,

Sorry about ambiguous title but the problem is so strange that I can't describe it better.

We've had strange problems in our project where sometimes Reagent stops responding to state changes after changing input's value. Yesterday we found that this is caused by a ` :on-blur` handler which updates the state through a cursor.

I have a demo here: http://deraen.github.io/problems/reagent-strange-bug/
and the source can be found here: https://github.com/Deraen/problems/blob/reagent-no-render/src/hello_world/core.cljs#L11-L29

1. app-state is saved on single ratom
2. forms access (:value, :on-change, :on-blur) the data through a cursor
3. actions (save thingie etc.) access state atom directly
4. `:on-blur` does something like `#(swap! data assoc :not-pristine true)`

To reproduce:

1. Change the input value
2. Click save => the component is re-rendered successfully
3. Change the input value
4. Click save => the component is not re-rendered
5. Changing the input value now will cause component to be re-rendered

Everything works if

- Cursor is not used
- A non-empty map is assoced in `:on-blur` handler instead of empty map or true

**Comment by antishok** [comment]
A simpler testcase, without `:on-blur`. Just click the button twice, the "Active" text should disappear but it doesn't.

```clojure
(def a (r/atom {:foo {:active? false}}))
(def c (r/cursor a [:foo]))

(defn button-click [e]
  (swap! c assoc :not-pristine true)
  (swap! a update-in [:foo :active?] not))

(defn main []
  [:div
   [:button {:on-click button-click} "Click"]
   (if (:active? @c) "Active")])
```

**Comment by holmsand** [comment]
Thanks for the simpler testcase!

I think I've found the problem now. Turns out that the `cursor` got confused when changes arrived both directly and from the underlying `atom` at once, due to some silly "optimization" on my part...

**Comment by ikitommi** [comment]
Any plans in getting a fix for this?

**Comment by scttnlsn** [comment]
FYI the test case added in https://github.com/savaki/reagent/commit/b7d0d0d362e979409539274d2d6f456f0f807d36 passes for me regardless of whether `(not dirty?)` is present.

**Comment by scttnlsn** [comment]
I think this issue (as well as #141) can be closed.  A fix similar to #141 was comitted here: https://github.com/reagent-project/reagent/commit/cdd3c851a0374825b166681152420d638307ba4e

**Comment by Deraen** [comment]
I can confirm this is fixed. I suggest this issue is kept open until the next version is released.

**Comment by JulianLeviston** [comment]
It's also not merged in yet.

**Comment by Deraen** [comment]
The commit @scttnlsn (cdd3c85) linked is in master.

**Comment by JulianLeviston** [comment]
Sorry I meant pull https://github.com/reagent-project/reagent/pull/141

**Comment by JulianLeviston** [comment]
... but I clearly just got confused. Sorry. :(

**Comment by mike-thompson-day8** [comment]
Checking;  once Dan releases 1.5.1, we can close this?

**Comment by Deraen** [comment]
Yes. I tested with the rc to be sure and it works now.
