### ISSUE TITLE
Is there any router for reagent

### ISSUE THREAD

**Issue by rhacker** [reagent-project/reagent#136]
I find reagent really really interesting. I'm working on an app with reactjs and react-router at router ( isomorphic app ). I've been looking around asking that is there any router solution for reagent yet ?

if there is, it would be great that we have an example for that. Thanks :)

**Comment by siscia** [comment]
I am not sure of what you mean, but maybe secreatary is what you are looking for...

https://github.com/gf3/secretary

``` clj
(secretary/set-config! :prefix "#")

(secretary/defroute "/" []
  (session/put! :current-page #'home-page))

(defn home-page []
  [:div [:h2 "Welcome to yiersan"]
   [:div [:a {:href "#/about"} "go to about page"]]])
```

**Comment by rhacker** [comment]
@siscia Thanks for your comment. But secretary is a router for client side only. We need a router that can work both client and server. Silk seems to be one but it's WIP.

**Comment by Frozenlock** [comment]
[Bidi](https://github.com/juxt/bidi) works for both clj and cljs.

**Comment by yogthos** [comment]
there's also [an experiment for using React router](https://github.com/ghedamat/reagent-react-router)
