### ISSUE TITLE
How do I *not* escape HTML text?

### ISSUE THREAD

**Issue by Engelberg** [reagent-project/reagent#137]
`[:span "   "]`
eats the extra space.  But if I do:
`[:span "&nbsp;&nbsp;&nbsp;"]`
it treats the text literally, rather than taking it as HTML.

How do I force an HTML interpretation of the hiccup-like elements in Reagent?

**Comment by hura** [comment]
https://github.com/reagent-project/reagent/issues/14

https://github.com/reagent-project/reagent/issues/104
