### ISSUE TITLE
Support seqs of strings for :class

### ISSUE THREAD

**Issue by lvh** [reagent-project/reagent#138]
Right now, the `:class` attr takes a single string, a la `"class-a class-b class-c"`. That works, but makes merging a little ugly (something like `(str curr " " new)`). It'd be pretty cool if it could be `["class-a" "class-b" "class-c"]` (or even with keywords), and reagent would take care of translating that to a class string.

**Comment by Deraen** [comment]
Merged in https://github.com/reagent-project/reagent/pull/154, released on 0.8.0-alpha2
