### ISSUE TITLE
Non-deterministic "Doesn't support name: " error thrown in initial reagent/render call

### ISSUE THREAD

**Issue by snowell** [reagent-project/reagent#139]
Reagent version: 0.5.0, running via `lein ring server`

I say non-deterministic, because I have two identical copies of my project checked out, it happens on one, but not the other...and not always on the one! It's very frustrating! Overloading the cljs.core.name function, I can see that the error is coming because a nil value is being passed in. My presumption was that I defined a component incorrectly, but as I said it works fine in a fresh checkout with the same core.cljs file. Stacktrace follows:

```
Uncaught Error: Doesn't support name: 
name @ core.js:26861
dash_to_camel @ util.js:77
(anonymous function) @ util.js:56
reagent.impl.util.memoize_1 @ util.js:57
(anonymous function) @ component.js:281
(anonymous function) @ component.js:282
(anonymous function) @ core.js:23220
cljs.core.PersistentHashMap.cljs$core$IKVReduce$_kv_reduce$arity$3 @ core.js:23221
_kv_reduce @ core.js:2009
reduce_kv @ core.js:7935
camelify_map_keys @ component.js:279
cljsify @ component.js:384
create_class @ component.js:392
fn_to_class @ template.js:262
as_class @ template.js:271
reag_element @ template.js:297
vec_to_elem @ template.js:377
as_element @ template.js:388
as_element @ core.js:117
reagent.core.render.f @ core.js:149
(anonymous function) @ util.js:277
render_component @ util.js:278
reagent.core.render.render__3 @ core.js:152
reagent.core.render.render__2 @ core.js:145
reagent.core.render.render @ core.js:157
init_BANG_ @ core.cljs:812
(anonymous function) @ dev.cljs:15
```

**Comment by antishok** [comment]
Hi. Can you show some code? And your project.clj file. 
Have you tried cleaning the output and doing a clean compile when getting the error?

**Comment by snowell** [comment]
Sorry, but I can no longer reproduce this issue. It must have been something in my environment that I accidentally cleaned up.
