### ISSUE TITLE
dangerouslySetInnerHTML support?

### ISSUE THREAD

**Issue by ptaoussanis** [reagent-project/reagent#14]
Hi Dan,

This isn't obvious to me - can you recommend the easiest way of providing text content in a component that'll be rendered as arbitrary HTML?

``` clojure
(defn my-component [] [:div "<strong>I want to see this in bold</strong>"])
```

Maybe we could do something with metadata to indicate that an element's content should be set with `dangerouslySetInnerHTML`? Was thinking along the lines of `^:html [:div "..."]` but not sure how feasible that'd be.

Cheers! :-)

**Comment by awb99** [comment]
There is another aspect to this ticket that was not yet fixed: scripts that are added via this manner are never evaluated! I do work on a reagent based gorilla repl that needs to include components that bring their own Javascript inside html. How can that be solved?

**Comment by Deraen** [comment]
@awb99 This is not limitation of Reagent or React, `innerHTML` not allowing `script` tags comes from HTML spec: https://developer.mozilla.org/en-US/docs/Web/API/Element/innerHTML

Some ways to add/run script tags from components are to just manually modify `document.body` with normal DOM operations like `appendChild`, or runing JS code from `img` `onload` (or `onerror`).

**Comment by awb99** [comment]
@Deraen Thank you! It does not really fit my usecase. But good to know!
