### ISSUE TITLE
Document testing convention for state

### ISSUE THREAD

**Issue by lvh** [reagent-project/reagent#140]
Not sure whether to put this under reagent-template or reagent itself.

reagent-template has some clear opinions on how testing and state (reagent-utils.session) works. Is there an opinion on how to do both at the same time? The "obvious" solution might be dynamic binding of the state, but that doesn't quite work due to async event callbacks.

**Comment by yogthos** [comment]
this should go under the reagent-template, and the session state is just an atom so that would be no different from having a regular global atom for state

**Comment by lvh** [comment]
Kind of. If you're using asynchronous event handlers, bindings don't work as you'd expect :(
