### ISSUE TITLE
Suggestion: extended hiccup syntax

### ISSUE THREAD

**Issue by hlship** [reagent-project/reagent#142]
Way, way back in my early days of Clojure, I worked on a server-side web framework called "Cascade". Long since abandoned.  It also used hiccup style templating, with a bunch of differences.

I basically adapted some Emmet-like syntax, so you could say:

```
[:head>title "Example Template" ]
    [:body#root>p 
      "Cascade is complete unto itself, it "
      [:em "does not" ]
      " use external template files."
    ]
```
The `>` is used to define a nested element.  I found this very useful.

If this seems like the kind of change you are interested in, I'd be thrilled to put together a PR.

**Comment by yogthos** [comment]
I don't see any harm in this, and it doesn't break existing functionality. It would be especially nice if the syntax allows multilevel chaing, e.g:

```clojure
[:body#root>div.content>p#foo.bar ...]
```
Working with stuff like bootstrap you often end up with a lot of nested divs that add a lot of noise to the code.

@holmsand any thoughts? :)

**Comment by hlship** [comment]
Yes, the multi-level stuff is easy enough to do (Cascade did that) and is very useful for Bootstrap and the like.

**Comment by yogthos** [comment]
:+1: from me :)

**Comment by hlship** [comment]
Great! I'll find some time to put this together.

**Comment by hlship** [comment]
Working on a PR for this now. I have it working, but need to update docs & maybe tests.

**Comment by yogthos** [comment]
[supported](https://github.com/reagent-project/reagent/blob/b45f84fa710221c3ad12f4d0b4e17cc8efb622b1/test/reagenttest/testreagent.cljs#L508) in `0.5.1-rc`
