### ISSUE TITLE
add-watch on cursors

### ISSUE THREAD

**Issue by JulianLeviston** [reagent-project/reagent#145]
It'd be nice to be able to add-watch on a cursor.

**Comment by muhuk** [comment]
It works for me using `[reagent "0.5.0"]`.

See [ratom.cljs](https://github.com/reagent-project/reagent/blob/master/src/reagent/ratom.cljs#L155).

**Comment by JulianLeviston** [comment]
I don't quite follow - does this mean add-watch works with cursors, or just ratoms? I know it works with ratoms. I couldn't get it working on 0.5.0, but perhaps I'm mistaken. I'll try again.

**Comment by muhuk** [comment]
`add-watch` works with cursors for me. Please provide a minimal program that reproduces this.

**Comment by JulianLeviston** [comment]
I'll close this because if I create it on a fresh install it works fine. My app is quite large and I don't have time at the moment to do the required isolation tests. I'll try when I've got some time.
