### ISSUE TITLE
Developer documentation - how to run tests, etc.

### ISSUE THREAD

**Issue by hlship** [reagent-project/reagent#147]
I'd like to contribute an enhancement to the project (see #142) ... but I have been unable to figure out how to set things up and run the existing tests.  A little documentation about how to do that, and how to generate the site documentation, would be quite welcome!

In terms of testing:

I executed `lein figwheel`  and a lot of JavaScript was created, but when I open http://localhost:3449, I just get a reminder to ... open the same URL.  I don't see a REPL started in my terminal, which seems like the first step towards running the tests (e.g., site/public/index.html).  Seems like the file is vended from site/public/index.html and the JavaScript is in outsite/public/js/app.js.

**Comment by scttnlsn** [comment]
@hlship I'm not a maintainer but have managed to get the tests running in the past.  After running `lein figwheel`, open `http://localhost:3449` and view the browser's JavaScript console.  You should see the test output there and saving a file should re-run the tests.  I agree, some documentation here would go a long way.

**Comment by dqdinh** [comment]
+1 for adding a Contributing section or wiki page that documents dev workflow

**Comment by Deraen** [comment]
https://github.com/reagent-project/reagent/blob/master/docs/development.md
