### ISSUE TITLE
Help re-rendering application using figwheel

### ISSUE THREAD

**Issue by joakin** [reagent-project/reagent#153]
Hi!

I've been working on migrating a hackathon project to clojurescript using reagent https://github.com/joakin/webkipedia

The problem I'm hitting is that figwheel reloads do not trigger a full re-render of the webapp, and I'm not sure why.

This is where the figwheel reload calls: https://github.com/joakin/webkipedia/blob/master/src/webkipedia/core.cljs#L9-L20

```clojure
(defn render! []
  (reagent/render-component [webkipedia]
                            (.-body js/document)))

(render!)
(router/init)

(defn on-js-reload []
  ;; optionally touch your app-state to force rerendering depending on
  ;; your application
  (render!)
)
```

I've been trying the solutions proposed in #94 but neither `[#'webkipedia]` nor calling `reagent/force-update-all` in `on-js-reload` seem to help me out.

To try out if the the re-rendering I'm changing the main title here https://github.com/joakin/webkipedia/blob/master/src/webkipedia/ui/main_page.cljs#L11

Any ideas on what I'm doing wrong or how could I circle the issue?

Thanks a lot for your work on reagent, it is a pleasure to use.

**Comment by joakin** [comment]
I've been poking a bit more and it seems like the root component `webkipedia` get's actually re-rendered (if I change the css  class here https://github.com/joakin/webkipedia/blob/master/src/webkipedia/ui/webkipedia.cljs#L22 it actually changes).

So now what happens is that the  `[main-page]` component isn't being rerendered: https://github.com/joakin/webkipedia/blob/master/src/webkipedia/ui/webkipedia.cljs#L10
Coming from : https://github.com/joakin/webkipedia/blob/master/src/webkipedia/ui/webkipedia.cljs#L24

Shouldn't `reagent/force-update-all` have helped me out with this?

**Comment by JulianLeviston** [comment]
You seem to be replacing the body, which is what contains your js.

**Comment by joakin** [comment]
Hey @JulianLeviston thanks for the comment!

I just tried:

```clojure
(defn render! []
  (reagent/render-component [webkipedia]
                            (.getElementById js/document "app")
                            #_(.-body js/document)))
```

And the problem still persists, so that doesn't seem to be the issue.

I'll research and consider not mounting into the `body`. It didn't pose any problems for me neither using JS nor with CLJS + React before, but you may be right.

**Comment by JulianLeviston** [comment]
I use reagent and figwheel daily without issue.

You probably need ^:figwheel-always to be attached to your core namespace to make sure saving *other* files than your core reloads everything.

You've closed over your render-component in a argumentless function, which means it won't get re-run, I think.

Consider pulling the reagent/render-component call out into the top level.

**Comment by JulianLeviston** [comment]
Oh, the other thing is my main component is a function that returns a function (as in, returns a render function)

something like:

      (defn main []
          (fn []
          [:div "hey"]))

**Comment by JulianLeviston** [comment]
@joakin Still having this issue?

**Comment by joakin** [comment]
I've tried both suggestions:

```clojure
(ns webkipedia.core ^:figwheel-always
```

And also:

```clojure
(defn webkipedia []
  (fn []
    [menu-container
     [:div.Webkipedia
      [top-bar]
      [:div.Webkipedia-body.container (get-content @current-route)]]]))
```

But no luck :disappointed:

**Comment by JulianLeviston** [comment]
The metadata goes before the ns symbol.
        (ns ^:figwheel-always webkipedia.core)
What exactly is going wrong? it's not loading when you save files?

**Comment by antishok** [comment]
I'd try this:

````clojure
(def content-components
  {:home    [#'main-page]
   :search  [#'main-page]
   :page    [#'page]
   :explore [:div "Explore"]})
````

since you say it's `[main-page]` not being re-rendered

**Comment by joakin** [comment]
Hey @antishok that worked! Thanks a lot. (https://github.com/joakin/webkipedia/commit/c33949af26e8046d1962a0d05a3ffccce4b4df46)

Any explanation of why I need to use that form there, but for example the [`top-bar` component](https://github.com/joakin/webkipedia/blob/c33949af26e8046d1962a0d05a3ffccce4b4df46/src/webkipedia/ui/webkipedia.cljs#L23) and sub-components live-reload fine?

For example changing [logo.cljs](https://github.com/joakin/webkipedia/blob/c33949af26e8046d1962a0d05a3ffccce4b4df46/src/webkipedia/ui/logo.cljs) which is contained by [top_bar.cljs](https://github.com/joakin/webkipedia/blob/c33949af26e8046d1962a0d05a3ffccce4b4df46/src/webkipedia/ui/top_bar.cljs) live-reloads just fine :confused: 

I'd love to understand what's going on.

Thanks again folks!

**Comment by antishok** [comment]
I can't really think of a satisfying explanation, I guess I don't fully know it.
But it has to do with the fact that before this change, `content-components` kept referring to the older `main-page` var even after a figwheel reload. Now with the `#'` it always takes the current, updated var. 
This SO answer, especially the 2nd example in it, seems similar to what might happen during a figwheel-reload: http://stackoverflow.com/a/14763690/1098884

Hopefully someone else can give a more satisfactory explanation.

**Comment by mike-thompson-day8** [comment]
As I understand it, you previously had this: 
```
(def content-components
  {:home    [main-page]
   :search  [main-page]
   :page    [page]
   :explore [:div "Explore"]})
```

That creates a datastructure which holds a the value of `main-page` at the time the data structure is created.   Even though figwheel reloads a new version of `main-page`,  that data structure will still be holding the old value of `main-page`.  So the old function is used even though a new one is loaded (both versions exist at once). 

So, two solutions would work:
   1.  recreate that data structure each time figwheel reloads  by adding the `^:figwheel-always` metadata to the `ns`.
   2.  introduce some indirection

You can add indirection via the #' trick  or  by this method:
https://github.com/reagent-project/reagent/blob/master/src/reagent/core.cljs#L95-L106

Also see the comments here:
https://github.com/reagent-project/reagent/blob/master/src/reagent/core.cljs#L95-L106

See also discussion in previous tickets like this one:
 https://github.com/reagent-project/reagent/issues/112

**Comment by mike-thompson-day8** [comment]
I'm guessing this issue can now be closed?

**Comment by joakin** [comment]
Hey @mike-thompson-day8 your comment makes a lot of sense, and I would've assumed that is how things are working, but something else happened:

By using the `#'main-page` every time the component returned by `get-content` changed I noticed that the whole DOM was being blown away, even if it was the same component (which it is between *home* and *search*).

I experimented a bit trying to get reagent/react to reconcile the DOM without just replacing it, and I ended up changing the `webkipedia` component to use `case` and normal vars instead of the `#'` indirection:

https://github.com/joakin/webkipedia/commit/0207477fb4cdda24239e300450e867f78e3d3758

```clojure
(defn webkipedia []
  [menu-container
   [:div.Webkipedia
    [top-bar]
    [:div.Webkipedia-body.container
     (case @current-route
       (:home :search) [main-page]
       :page [page]
       :explore [:div "Explore"]
       not-found)
     ]]])
```

This helped fix the DOM being blown away between changes in `home` and `search` while maintaining live-reloadability of all the children components.

This made me very confused since I thought I really needed the `#'` indirection for the live-reloading to keep  working.

I'm not sure what the difference is and what is going on, but in the interest of getting-shit-done I'm just going to close this issue. We can continue discussing what is actually going under the hood if you guys feel like it.

I'm a bit concerned about not knowing exactly how the system as a whole is behaving, but I'm happy that I have everything I wanted working.

Thanks everybody for your help.

**Comment by JulianLeviston** [comment]
I recommend reading more about figwheel at the figwheel repo, and looking under the hood.

Reagent in combo with figwheel uses function replacement, which causes a re-render but only of the functions that change. This also happens when Reagent builds a reaction - as happens anytime you use a dereffed atom or cursor, from what I understand. This will cause a re-render on atom/cursor modification.

So, every time you save, and figwheel reloads the code, what you *were* doing is re-evaluating the refs to the functions which means it had to reload the whole tree - it had no choice because it couldn't tell if the functions had changed or not. Using that strategy, figwheel can't actually do anything other than get react to reload everything.

This is also the reason we use defonce around atoms when building "live-reloadable code"... because each time you save, figwheel will reload the refs, so if you have atoms defined with def they would get re-deffed, which would cause everything to reload from scratch the same as when you were using #' everywhere.

Hope that helps you understand more what's happening.

**Comment by mike-thompson-day8** [comment]
A full reload will be because this:
https://github.com/joakin/webkipedia/blob/master/project.clj#L29

causes this:
https://github.com/joakin/webkipedia/blob/master/src/webkipedia/core.cljs#L16-L20

which, in turn, causes this:
https://github.com/joakin/webkipedia/blob/master/src/webkipedia/core.cljs#L10-L11

So, each time figwheel loads new source, the entire reagent tree is remounted from the root down.
