### ISSUE TITLE
Re-rendering only when a cursor changes

### ISSUE THREAD

**Issue by mhuebert** [reagent-project/reagent#155]
I expected that when I dereference a cursor in a component, the component will re-render **only** when the value of that cursor changes. However, in the following example, two components which render different cursors of the same atom *both* re-render when *either* location in the atom is modified:

```clj
(defonce my-state (r/atom {1 "aaa"
                           2 "bbb"}))

(defn display-item [item-cursor id]
  (fn []
    (prn (str "Re-rendering item #" id))
    [:div
     [:span (str @item-cursor)]
     [:a {:on-click #(reset! item-cursor (str (rand-int 1000)))} (str "Modify " id)]]))

(defn test-div []
  [:div
   [display-item (cursor [1] my-state) 1]
   [display-item (cursor [2] my-state) 2]])
```

I get the expected behaviour if I store r/atoms inside of r/atoms:

```clj
(defonce my-state (r/atom {1 (r/atom "aaa")
                           2 (r/atom "bbb")}))
```

but this doesn't seem ideal. Am I missing something?

**Comment by antishok** [comment]
The inner function in `display-item` should have the same parameters as the outer one  (or just remove the inner one).
That said, I'm not seeing the same behaviour you are, it's working as expected for me with your code.

**Comment by JulianLeviston** [comment]
The problem seems to me that you have your atom argument position switched for the index argument.
eg:
     (r/cursor state-atom [:some-index])

and not 
     (r/cursor [:some-index] state-atom)

Also it might be useful to note that your reset! won't generate a new random number on every click, like you might suppose. You'd need to wrap the function and call it if you wanted that, I think.

**Comment by mhuebert** [comment]
@JulianLeviston your note about atom position made me realize that I had forgotten to update this library to use `cursor` from reagent core - I was using the [deprecated version](https://github.com/reagent-project/reagent-cursor). Using the new version gives me the expected behaviour. Thanks!

@antishok thanks for the note. I did not realize that one should always pass in the same arguments to inner render functions (now I see it clearly in the docs, though there is no example of argument-passing where it is mentioned & I think that's why I missed it).

**Comment by mike-thompson-day8** [comment]
@mhuebert   Have a look at these docs:  https://github.com/Day8/re-frame/wiki/Creating-Reagent-Components.  It mentions this issue as one of the rookie mistakes.  The other notes in there may help you to avoid others.

**Comment by mhuebert** [comment]
@mike-thompson-day8 thanks for the link! a very helpful article.
