### ISSUE TITLE
How do I share the same atom in multiple files?

### ISSUE THREAD

**Issue by thiagofm** [reagent-project/reagent#156]
Hello,

I wanted to share the same atom in multiple files/module, so I could use cursors(0.5.0) to grab and update data there. But couldn't find anywhere... how do I do it?

Cheers

**Comment by JulianLeviston** [comment]
This isn't a help forum.

Having said that you can simply refer to the atom like you would anything else defined in another file:

    typing-area/character-maps

for example, assuming the namespace the atom was in is called typing-area in your current file, and the atom you want is called character-maps. Might seem a little strange to write things like  @typing-area/character-maps to deref them, but it works fine. Please close this.

**Comment by gadfly361** [comment]
Good resources to ask for help include:

* [Reagent Project Google Group](https://groups.google.com/forum/#!forum/reagent-project)
* Reagent channel on Slack. Sign up [here](http://clojurians.net/)

**Comment by thiagofm** [comment]
@JulianLeviston I don't understand why you have to speak things that way, but thanks for the help.

@gadfly361 thanks, didn't know about that.

**Comment by JulianLeviston** [comment]
@thiagofm Sorry, which way wasn't good? Was "This isn't a help forum" a bit too short? Apologies if you became offended or my communication came across as brash. It was just unadorned information. Perhaps it's ironic (given that this further communication is now taking place), but I like to be precise and concise in communication. It appeals to my appreciation of efficiency.

**Comment by martinskou** [comment]
Remember to require the reagent atom in your file though...
[reagent.core :as reagent :refer [atom]]
