### ISSUE TITLE
Alternative to React refs in event handler?

### ISSUE THREAD

**Issue by lotabout** [reagent-project/reagent#160]
Suppose I want to create some reusable components.

```
(defn song-player []
  "display songs and controls"
  (let [current-song (atom {"title" "some title", "url" "some-url"})]
    (fn []
      [:div.player
       [:p "title: " (@current-song "title")]
       [:audio#player-audio
        {:src (str (@current-song "url"))}]
       [:input {:type "button"
                :value "Play/Stop"
                :on-click #(let [player (. js/document (getElementById "player-audio"))]
                             (if (.-paused player)
                               (.play player)
                               (.pause player)))}]])))
```
Suppose I will want several `song-player` in one page. In that case I cannot assign ID(`#player-audio`) to the `audio` element, because the page will have duplicate ID.

So how do I refer to local component in event handler? In this case, how do I refer to the local `audio` element in the event handler of `on-click` event?

In react.js, I can assign a `ref` to the `audio` component and refer to by `this.refs.XXX`. How do I do this in reagent? Thanks!

**Comment by JulianLeviston** [comment]
This seems like a question more than a bug report.

**Comment by lotabout** [comment]
@JulianLeviston Yes, it is. Sorry for any inconvenience. And if the issues page is not allowed to ask, I will not do it again.

I was intended to ask on stackoverflow, but wanting for more related and professional reply.

**Comment by JulianLeviston** [comment]
Well if you want to start a FAQ in the wiki and add your question to it (in a general form), it will probably be a better idea than opening a ticket for it. Having said this, I don't know what the general policy is for this. I just assume that a source code repo isn't particularly a good spot to ask questions, unless it's a question of missing documentation... in which case the question should be phased perhaps a little differently. Apologies if I've annoyed you.

**Comment by gadfly361** [comment]
@JulianLeviston @lotabout I think the following are good options:

1. [Google Groups](https://groups.google.com/forum/#!forum/reagent-project), and 
    * (+) Leaves a paper-trail in case others have similar issues; (-) May be comparatively slower feedback
2. [Clojurians](http://clojurians.net/) on Slack.
    * (+) Quicker feedback (active reagent and re-frame channels); (-) Chat log isn't permanent.

**Comment by mike-thompson-day8** [comment]
Clojarian discussions are logged here:  http://clojurians-log.mantike.pro/

**Comment by mike-thompson-day8** [comment]
@lotabout good to close this?
