### ISSUE TITLE
BMI slider should be read-only

### ISSUE THREAD

**Issue by ulsa** [reagent-project/reagent#162]
It's possible to move the intro demo BMI slider, which I assume is a bug.

**Comment by mike-thompson-day8** [comment]
I don't see a bug.  

I just had a look, and there's no code trying to stop the BMI slider from being dragged.  And sliding it seems to result in reasonable behaviour in the values of other sliders.  So nothing obviously bad is happening here. It is just a deliberately simple example working as expected. 

I'm going to close this.

**Comment by ulsa** [comment]
The BMI value is a function of two input values. I just think it's weird, being able to change the function result, since it's undefined what the single corresponding change in input values would be. In the Hoplon version, they disabled the BMI slider, which removes this issue. I like that. Just my two cents.
