### ISSUE TITLE
render-to-static-markup still warns about unique keys

### ISSUE THREAD

**Issue by mhuebert** [reagent-project/reagent#163]
I'd like to render :svg elements without adding a unique :key to each, so I have tried:

``` clj
:dangerouslySetInnerHTML  {:__html (r/render-to-static-markup @value)}
```

It renders, but fills the console with "Every element in a seq should have a unique :key" warnings.

Are these warnings necessary for static markup? I don't think React cares.

**Comment by Deraen** [comment]
I'm closing this as old and probably fixed by new React versions. I have rendered svgs using Reagent and haven't noticed any problems using them output adding keys etc.
