### ISSUE TITLE
Add Travis-CI or similar

### ISSUE THREAD

**Issue by danielcompton** [reagent-project/reagent#168]
Having continuous integration on the project makes it easy for contributors to see if they've broken the tests. I'd like to add this, but I'm not sure how to run the tests from the command line.

Relates to #147.

**Comment by scttnlsn** [comment]
Agreed.  I've used PhantomJS and a custom cljs.test reporter to do this.  Here's an implementation for Reagent: https://github.com/scttnlsn/reagent/commit/10e44f1d7e75c0dcebe74bad54dcb38fcbd44f7f

You can run the tests via `lein cljsbuild test` and the `.travis.yml` file could just contain:

```yaml
language: clojure
script: lein cljsbuild test
```

**Comment by dqdinh** [comment]
@scttnlsn Thanks for the phantomjs implementation. However, I did get some react related warnings:
```bash
$ lein cljsbuild test
Compiling ClojureScript.
Compiling "outsite/public/js/main.js" from ("src" "demo" "examples/todomvc/src" "examples/simple/src" "examples/geometry/src" "test")...
Successfully compiled "outsite/public/js/main.js" in 7.455 seconds.
Compiling "target/test/test.js" from ["src" "test"]...
Successfully compiled "target/test/test.js" in 4.809 seconds.
Running ClojureScript test: test
Warning: Error unmounting:
Error: Invariant Violation: unmountComponentAtNode(...): Target container is not a DOM element.

Testing reagenttest.testratom

Testing reagenttest.testinterop

Testing reagenttest.testreagent

Testing reagenttest.testwrap

Testing reagenttest.testcursor

Ran 52 tests containing 1139 assertions.
0 failures, 0 errors.
Tests passed.
```

Any idea why these warnings show up? Do you also get them after running `lein cljsbuild test`?

**Comment by scttnlsn** [comment]
@dqdinh Yeah, I also see those warning messages.  They're showing up because the console messages are being forwarded: https://github.com/reagent-project/reagent/pull/169/files#diff-7e7c3958584f1ce4c64d8c1c7e77285fR3

The warnings should be addressed separately since they're unrelated to the PhantomJS setup.

**Comment by dqdinh** [comment]
@scttnlsn thanks
