### ISSUE TITLE
using local state

### ISSUE THREAD

**Issue by benzen** [reagent-project/reagent#170]
I'm having diffculty with creating a local state with reagent.

I've tryed to use 
(r/set-state (r/current-component) my-map-update)
With a let binding on r/current-component.
But all my instances of this component where updated at the same time.

I've tryed to let bind a r/atom inside my reagent component function.
Only one instance gets the update, but i have multiple event handler that halter my local state.
When the second fire, it looks like the update made by the first one have disappeared.

What would be the recommended way to create a local state.

I understand that it's best to use only global state, but for animation, I would prefer to keep things locally.

**Comment by benzen** [comment]
I think i've found what is the cause of my issue.

I've got a list from which i want to generate a list of component.
I've used `(map list-of-things things-to-components)`. But i've got a warning from template which says that reactive deref is not supported inside lazy-seq and that i should wrap it into a doall.

But when i do so, the r/atom update is broken.
When I did not, the r/atom update work just fine.

Maybe this error message isn't correct anymore ?

**Comment by benzen** [comment]
I've got some clarification on clojurians slacker.

I think that this https://github.com/Day8/re-frame/wiki/Creating-Reagent-Components should be made visible on the pages that explains how to create reageant components.

I leave this open just to be sure that people behind reageant read this, and consider this propposition.

**Comment by JulianLeviston** [comment]
You're probably correct.

**Comment by gadfly361** [comment]
Forgot to mention on this thread, I added a section on [component-level-state](https://github.com/reagent-project/reagent-cookbook/blob/master/basics/component-level-state/README.md) to the cookbook.

**Comment by mike-thompson-day8** [comment]
Closing.  No further value in continuing to be left open.
