### ISSUE TITLE
README.md Example atom def vs defonce

### ISSUE THREAD

**Issue by owenrh** [reagent-project/reagent#171]
Really minor, but the example atoms in the README.md are defined with *def* rather than *defonce*. No biggie, but probably avoids confusion to put them as *defonce* to play nice with realtime/figwheel dev right? Unless there's a specific reason not too.

It probably only effects beginners and those prone to cut n paste! 

(PS. I love Reagent. It is awesome. Thanks for sharing it.)

**Comment by JulianLeviston** [comment]
Why not submit a PR?

**Comment by JulianLeviston** [comment]
Actually, don't worry, I will.

**Comment by JulianLeviston** [comment]
Ok PR created... https://github.com/reagent-project/reagent/pull/172

**Comment by owenrh** [comment]
@JulianLeviston sure, thanks.

**Comment by Whoops** [comment]
Merged, so I'll go ahead and close
