### ISSUE TITLE
Embedding images in svg doesn't work.

### ISSUE THREAD

**Issue by AdamSaleh** [reagent-project/reagent#173]
I have a reagent component that looks like this:

```clojure
(defn hexagon [x y]
  (let [pixel-x (+ 50 (* x hexagon-radius 1.5) )
       pixel-y (+ 50 (* x (* hexagon-radius (/ 25 30))) (* y 2 (* hexagon-radius (/ 25 30))))]
  [:g {:x pixel-x :y pixel-y}
    [:polygon
      {:points (hex-point-string pixel-x pixel-y hexagon-radius)
      :style {:fill "rgb(255, 255, 255)" :stroke "rgb(0, 0, 0)" :stroke-width "1px"}}]
      [:image {:x pixel-x :y pixel-y :width "100" :height "100" :xlink:href "hexbg.png"}]
      [:text  {:x pixel-x :y pixel-y :fill "red"} (clojure.string/join " " [x  y])]]))
```

I expected it to render as a hexagon, with png imagein front of it, and the x,y coordinates.
Instead, just the hexagon and coordinates are rendered, and the image element

```clojure
[:image {:x pixel-x :y pixel-y :width "100" :height "100" :xlink:href "hexbg.png"}]
```

is missing the xlink:href parameter:

```
<image x="50" y="50" width="100" height="100" data-reactid=".0.0.4.0.1"></image>
```

**Comment by GetContented** [comment]
This is react issue.

https://github.com/facebook/react/issues/2250

**Comment by AdamSaleh** [comment]
Thanks for explanation, I have missed that somehow :)

**Comment by GetContented** [comment]
It's totally understandable. I recommend you voice your opinion over on that issue. It'll help git it solved in React, which is a great idea.

**Comment by GetContented** [comment]
Actually, they just added a top notice to the issue recommending you don't do that, so maybe not. Sorry!
