### ISSUE TITLE
Feature request: allow user to provide a function to preprocess components

### ISSUE THREAD

**Issue by lorddoig** [reagent-project/reagent#174]
API example:

```
(reagent/render [my-component]
  (.getElementById js/document "app")
  {:preprocess-fn process-elem})
```

where `process-elem` might receive a map like this:

```
{:tag :button
 :props {:class #{:btn :btn-primary}
         :type :button}}
```

Things this could allow:

* Detection of forgotten `aria-` attributes
* Injection of your `app-state` atom into function arguments
* Wrapping event handling functions, such as `on-click` for buttons where you might want to `blur` the element every time
* Ensuring event handlers don't accidentally return `false`
* Injection of debug statements

I'm not sure exactly how this would work, what the API should look like, or how performant it'd be but I think it'd be a really great feature.

**Comment by mike-thompson-day8** [comment]
@lorddoig  there's a lot of proposed magic here without much meat :-)  I think you'll need to provide some more specifics.

**Comment by mike-thompson-day8** [comment]
@lorddoig   in the absence of your further elaboration, I'm going to close this.  If you get time to take these ideas further, then we'll certainly reopen later.
