### ISSUE TITLE
Can't use Material-UI “native” component

### ISSUE THREAD

**Issue by atroche** [reagent-project/reagent#175]
Hello! I'm trying to use components from [Material-UI](https://github.com/callemall/material-ui).

Here's my CLJS app:

```cljs
(ns ^:figwheel-always booking.core
  (:require
    [reagent.core :refer [render-component adapt-react-class]]))

(def app-bar
  (adapt-react-class (aget js/MaterialUI "AppBar")))

(render-component [app-bar]
                  (.getElementById js/document "app"))
```

`app-bar` gets defined without any errors or warnings, but when I try to render it, I get:

![localhost_3449___appointments](https://cloud.githubusercontent.com/assets/29839/9346114/eef0e804-465b-11e5-8a1f-c50f98896983.jpg)

I'm using Material UI v0.10.4, unminified, built using a method adapted from [om-material-ui](https://github.com/taylorSando/om-material-ui/tree/master/build-mui).

Any ideas what I'm doing wrong?

**Comment by atroche** [comment]
When I use the prebuilt `material.js` used by [reagent-material](https://github.com/tuhlmann/reagent-material), I get:

![localhost_3449___appointments](https://cloud.githubusercontent.com/assets/29839/9346173/f125146e-465c-11e5-8b9b-1b2fd688be30.jpg)

**Comment by scttnlsn** [comment]
@atroche Did you figure out what the issue was?  I'm getting the same error when using `adapt-react-class` (though I'm not using Material UI).
