### ISSUE TITLE
Integration with Radium

### ISSUE THREAD

**Issue by madvas** [reagent-project/reagent#176]
Hi,

This might be a trivial question or not, I'm pretty new to reagent. How would one integrate reagent with [FormidableLabs/radium](https://github.com/FormidableLabs/radium)? 

Thanks a lot

**Comment by mike-thompson-day8** [comment]
This isn't really an issue with reagent, so I'm going to close this.   

Best to post these kinds of questions in a more general help forum like:
    - http://clojurians.net/   (reagent channel)
    - https://groups.google.com/forum/#!forum/reagent-project
    - stackoverflow
