### ISSUE TITLE
0.5.1-rc wants testing

### ISSUE THREAD

**Issue by holmsand** [reagent-project/reagent#177]
There is now a Reagent 0.5.1-rc uploaded to clojars. Try it out!

**Comment by yogthos** [comment]
@holmsand did this get rolled back at some point? https://github.com/reagent-project/reagent/pull/149/files I was just hoping to use it :)

**Comment by holmsand** [comment]
@yogthos No, the functionality is still there – but I rewrote most of it, to avoid performance trouble when the new syntax is *not* used.

There are even a few tests here: https://github.com/reagent-project/reagent/blob/master/test/reagenttest/testreagent.cljs#L508

**Comment by yogthos** [comment]
ah most excellent :)

**Comment by jonase** [comment]
If I change `[:li [:a {:href "#"} "Profile"]]` to `[:li>a {:href "#"} "Profile"]` I get "Invariant Violation: Invalid tag: li>a”

**Comment by mike-thompson-day8** [comment]
Reporting:  the [re-com demo app](http://re-demo.s3-website-ap-southeast-2.amazonaws.com/#/h-box)  works correctly with `0.5.1-rc`

**Comment by GetContented** [comment]
FWIW I just tried switching my app to it (from 0.5.0), and it ground to a halt on some of the data I tested it on. I can't seem to work out how to debug it, though, as Chrome just basically locks out with no input. Same with Safari. I'll try to see if I can run the profiler in Chrome again (tried once but it didn't work). Feels like there's maybe an infinite loop somewhere or something.

**Comment by GetContented** [comment]
Ok nevermind, it's working for me now. The problem was a bug in my codebase that only manifested as a serious problem with the new clojurescript version, it seems... though I'm not sure why it caused such an issue. Follows is the incorrect code:

    (defn every-entry-in?
      "returns true if all full entries in the inclusion-check-map
       are present in the test map."
      [inclusion-check-map test-m]
      (= (select-keys inclusion-check-map (keys test-m))
         test-m))

I obviously need to name my variables better! :)

Also, though, I might add that firefox helped me to debug this. Safari and Chrome were next to useless.

Also, Firefox is complaining about the following. I'm not sure if this is a clojurescript or reagent issue:
      mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create

**Comment by mike-thompson-day8** [comment]
From my point of view, this looks good to release. No problems in our apps.

**Comment by GetContented** [comment]
Yeah, likewise. I think the error I reported at my last message was some old code caching. Since I've cleared everything out several times and I'm not seeing any errors at all anymore related to this. Mind you, I haven't bumped to rc2 yet.

**Comment by yogthos** [comment]
I've been using the new version in all my apps without issues as well

**Comment by holmsand** [comment]
There is now a 0.5.1-rc3 with a small additional fix. If that doesn't cause any major disasters, I'll push a 0.5.1 in a day (or two).

**Comment by holmsand** [comment]
I've now pushed 0.5.1, and posted a description here: http://reagent-project.github.io/news/news051.html

**Comment by weltan** [comment]
We just pulled down 0.5.1 (we use "LATEST"), and we're getting the following clojure.lang.Exception during build:
No such namespace: reagent.core, could not locate reagent/core.cljs, reagent/core.cljc, or Closure namespace "reagent.core" {:tag :cljs/analysis-error}

Everything compiles cleanly when I rever to 0.5.0. 

We are using:
[lein-cljsbuild "1.1.0"]
[org.clojure/clojure "LATEST"]
[org.clojure/clojurescript "1.7.48"]

Any ideas?

**Comment by danielcompton** [comment]
Can you try reproducing this with Clojure 1.7.0?

**Comment by weltan** [comment]
Ok, tried 1.7.0 and everything worked perfect. Strangely, after doing this, it continued working even after upgrading back to alpha5, so I can't repro this again...seems like a strange fluke.

Point noted on the dependency thing! It's always frustrating when stuff breaks directly underneath you...it's happened a couple times already for us.

Thanks for the help.

**Comment by yogthos** [comment]
One thing that can cause this is cljc, since it's only available in 1.7 the build breaks in 1.6 if there are libraries depending on it.
