### ISSUE TITLE
how to use local module in reagent/clojurescript ?

### ISSUE THREAD

**Issue by WeweTom** [reagent-project/reagent#179]
I build a reagent app `reagent-demo-app` with

```
lein new figwheel reagent-demo-app -- --reagent
```

and `reagent-demo-app` use a devloping module , for example 

```
lein new figwheel reagent-calendar -- --reagent
```

`reagent-calendar` is local , how it can be used in `reagent-demo-app` ?

**Comment by mike-thompson-day8** [comment]
@WeweTom  Sorry, I don't fully following the question **but** I'm fairly sure this question shouldn't be in here.  Please ask this sort of question in one of the help forums like:  Stackoverflow, the clojarians slack channel, or google groups for cljs or reagent.  

This question seems to be more about the lein template you are using than reagent. 

I'm going to close this issue, although I'm hoping that someone watching might understand the question better than I and still provide you with an answer/pointer.

**Comment by WeweTom** [comment]
ok , thanks
