### ISSUE TITLE
`adapt-react-class` doesn't report an error if its argument is null

### ISSUE THREAD

**Issue by danielbraun** [reagent-project/reagent#180]
Just spent a few hours debugging this -

`(def nav-bar (reagent/adapt-react-class js/ReactBootstrap.NavBar))`

The actual name is Navbar, not NavBar.
Instead of complaining that the argument is null, I'm getting 
`Uncaught TypeError: Cannot read property 'toUpperCase' of undefined` when rendering.

Could we perhaps throw an exception if the argument to `adapt-react-class` is null?

**Comment by holmsand** [comment]
Good catch. I'll add an assert.

**Comment by holmsand** [comment]
Done in 0.5.1
