### ISSUE TITLE
Sharp corner with #79 fix (`input-set-value` cursor positioning)

### ISSUE THREAD

**Issue by ptaoussanis** [reagent-project/reagent#183]
Hi there!

In reference to commit https://github.com/reagent-project/reagent/commit/90949431f58a6ba20189a35629b5b3aa8114a59a:

New cursor offset is being calculated as: `(- (count value) existing-offset-from-end)`

This assumes that the node's value is countable. For strings (the normal case), that holds.

But I believe this breaks compatibility with previous versions of Reagent which (afaik?) allowed integer input values. Not sure if that allowance was actually intentional (?), but figured it might be worth pointing out the difference here.

This caught me with a date `select` tag which had int value options instead of strings. Fix was trivial, but took some doing to track down.

If the current behaviour's intentional, could I suggest an assertion to check that the node val's a string before counting? Would give a clearer error message for what might be a relatively easy mistake to make?

All the best, cheers! :-)

**Comment by mike-thompson-day8** [comment]
@ptaoussanis can you supply an example of the hiccup which triggers this please.

**Comment by holmsand** [comment]
@ptaoussanis Good catch!

I think I've fixed this now, by being more careful with the cursor-repositioning thing.

**Comment by holmsand** [comment]
There is now a 0.5.1-rc3 with the fix.

**Comment by ptaoussanis** [comment]
Fix looks good - much thanks!
