### ISSUE TITLE
React 14

### ISSUE THREAD

**Issue by mike-thompson-day8** [reagent-project/reagent#184]
React 14 is out.  http://facebook.github.io/react/blog/2015/09/10/react-v0.14-rc1.html

**First**, Dan should bask in the glory of his thought leadership. React now has a shortcut for stateless components. Does it look familiar?  http://facebook.github.io/react/blog/2015/09/10/react-v0.14-rc1.html#stateless-function-components   A few more years and they'll discover the devine ratom :-)

**Second**, given this version is now at RC stage, we need to figure out if there are threats and/or opportunities in adopting it.

**Comment by holmsand** [comment]
@mike-thompson-day8 Thanks! I'm now blushing quite a bit, while I'm basking in my glory :)

React 0.14 is going to be a little bit of a mess, since there are now two packages – one for React core, and one for the DOM stuff. So, at some point Reagent will probably have to split as well. I'm not entirely sure how to do that in a way that minimizes the trouble involved...

**Comment by Deraen** [comment]
React 0.14 is now packaged in Cljsjs. React-dom is packaged as a separate package.

**Comment by Gonzih** [comment]
Since dom functionality was moved from react-core I curious what are possibilities of running diff algorithm inside for example web worker? Do you guys have any ideas on that?

**Comment by ClashTheBunny** [comment]
According to the release notes for the 0.14 rc1, there are only a few methods broken out.  I grepped through the source code using `grep -nr "js/React"` and then grepping for the old and new methods.

These are the ones moved to react-dom and react-dom/server:
```bash
grep -e render -e unmountComponentAtNode -e findDOMNode -e renderToString -e renderToStaticMarkup
```

React-dom:
```clojure
./impl/util.cljs:117:        (->> (.' js/React render (comp) container
./impl/util.cljs:133:  (.' js/React unmountComponentAtNode container))
```

React-dom/server:

```clojure
./core.cljs:84:       (.' js/React renderToString (as-element component)))))
./core.cljs:95:       (.' js/React renderToStaticMarkup (as-element component)))))
```

These are the ones that stay the same:

```clojure
./core.cljs:33:   (js/React.createElement type props))
./core.cljs:36:   (js/React.createElement type props child))
./core.cljs:39:   (apply js/React.createElement type props child children)))
./impl/template.cljs:235:    (.' js/React createElement c jsprops)))
./impl/template.cljs:336:    0 (.' js/React createElement comp jsprops)
./impl/template.cljs:338:    1 (.' js/React createElement comp jsprops
./impl/template.cljs:341:    (.apply (.' js/React :createElement) nil
./impl/component.cljs:233:        res (.' js/React createClass spec)
./impl/component.cljs:275:  (.' js/React createClass
```

These are probably just search-replace changes.  The other change being `getDOMNode` being no longer required.  This would say that:
```clojure
./core.cljs:197:  (.' this getDOMNode))
./impl/template.cljs:105:             (let [node       (.' this getDOMNode)
```

would become:
```clojure
./core.cljs:197:  this)
./impl/template.cljs:105:             (let [node       this
```

Are these the big changes?

**Comment by yogthos** [comment]
and looks like React 0.14 is officially out http://facebook.github.io/react/blog/2015/10/07/react-v0.14.html

**Comment by holmsand** [comment]
Excellent. I'll have a closer look as soon as cljsjs is updated.

Right now, I think it is safest to move render etc. to a couple of new packages: reagent.dom and reagent.dom.server, to match what React is doing. And deprecate reagent.core/render etc. That will be kindof painful, but it's probably the best long term solution.

**Comment by yogthos** [comment]
Would it be possible to make `render` a protocol that would be implemented by `dom` and `server`?

**Comment by holmsand** [comment]
@yogthos No need, I think. `reagent.dom.server` would only contain `render-to-string` and `render-to-static-markup`, to match React's `react-dom/server` package (as per the blog post).

**Comment by yogthos** [comment]
You're right, it doesn't look like server would be affected. I'm thinking mainly from the perspective of keeping the API stable with `reagent.core/render`. I assume you suggest deprecating it since there would be separate implementations for dom/native?

**Comment by yogthos** [comment]
oh and looks like `getDOMNode` is being deprecated in favor of `findDOMNode` and there's a bit of a change as to how refs behave for built-in components.

**Comment by Skinney** [comment]
Two things I find interesting in this release are stateless components and the inlining optimization.

Stateless components seems to be mostly an easier syntax for JS-devs right now, but fb says that it opens the road for further optimizations in the future. Perhaps reagent should makes use of stateless components for reagent components that don't use a ratom today?

Inlining of elements seems like a nice optimization, but is recommended disabled for development purposes due to poorer warnings when things go wrong. Reagent might already provide the relevant warnings here, so we could enable this by default?

Sorry if the answer to any of these are obious. I don't know the reagent code that well.

**Comment by GetContented** [comment]
@Skinney I actually thought all components of Reagent *are* stateless. Do Reagent components use props?

**Comment by mike-thompson-day8** [comment]
@Skinney reagent has had stateless components from the beginning.  See the first comment in this issue.

**Comment by Skinney** [comment]
@mike-thompson-day8 and @GetContented I'm referring to the new syntax that is available in React 0.14. I'm saying that reagent perhaps should compile down to it, instead of a React.createClass statement, as such syntax might be recognized and optimized by react in future releases (and also might save some lines of code).

**Comment by Deraen** [comment]
Cljsjs packages have been updated.

```clj
[cljsjs/react "0.14.0-0"]
[cljsjs/react-dom "0.14.0-0"]
```

**Comment by holmsand** [comment]
React 0.14 is now in master. I've added two new namespaces: reagent.dom and reagent.dom.server, but I haven't deprecated the old api in core (yet?).

React 0.14 is a bit of a mess – renderToString has been deprecated in the standalone version of React (which is the one packaged by cljsjs) with no replacement, so it is now only available in the npm version.

There is a React issue about that here: https://github.com/facebook/react/issues/5159

Hopefully the React people can come up with a solution. In the meantime, I've added some support for using the npm version of React, either directly in node or using something like webpack. Using webpack etc. is quite messy, but at least it can be done :)

**Comment by yogthos** [comment]
@holmsand would it make sense to push out a snapshot to Clojars? Then could open up the new version for public testing. :)

**Comment by holmsand** [comment]
@yogthos It would indeed... I'll try to get something out in the next couple of days.

**Comment by yogthos** [comment]
:+1:

**Comment by ducky427** [comment]
Does [React v0.14.3](https://facebook.github.io/react/blog/2015/11/18/react-v0.14.3.html) address the issue with `renderToString`?

**Comment by Gonzih** [comment]
@ducky427 
what issue are you talking about?

**Comment by Deraen** [comment]
Versions 0.14.1, 0.14.2 and 0.14.3 are now available from Clojars should it should be easy to test if they fix some problems.

**Comment by holmsand** [comment]
@ducky427 It should. 0.14.3 adds a non-deprecated renderToString in a new ReactDOMServer package.

@Deraen Great news! Do you now if ReactDOMServer will be packaged as well?

**Comment by Deraen** [comment]
@holmsand It's packaged now.

**Comment by holmsand** [comment]
@Deraen Brilliant. Thanks!

**Comment by atroche** [comment]
I upgraded my project to Reagent master using [my fork](https://clojars.org/org.clojars.atroche/reagent), and I haven't had any issues =)

**Comment by yogthos** [comment]
I think rc might be in order :)

**Comment by schmee** [comment]
@atroche I tried using your fork since I want to use [react-select](https://clojars.org/cljsjs/react-select) in my project, but when I try to compile I get this error:

```
Figwheel: Starting server at http://localhost:3000
Figwheel: Watching build - app
Compiling "resources/public/js/app.js" from ("src/cljs" "env/dev/cljs")...
{:tag :cljs/analysis-error}
ANALYSIS ERROR: Referred macro reagent.interop/$! does not exist on file null, line null, column null
```

Any clue what might cause this?

**Comment by Atsman** [comment]
Any estimations here?

**Comment by holmsand** [comment]
Reagent 0.6.0-alpha is finally pushed, containing React 0.14.3.

**Comment by yogthos** [comment]
:fireworks:

**Comment by esp1** [comment]
React 15 is now out... https://facebook.github.io/react/blog/2016/04/07/react-v15.html

**Comment by yogthos** [comment]
Looks like it should be pretty seamless moving form 0.14 as most of the changes are in internal operation.

**Comment by minikomi** [comment]
Quickly tested with `15.0.1-1` from clojars - showing "All tests ok".

**Comment by minikomi** [comment]
Wow, just got bitten by the extra-spans issue [this](https://facebook.github.io/react/blog/2016/03/07/react-v15-rc1.html#no-more-extra-ltspangts) should clear up.

**Comment by Gonzih** [comment]
yeah had the similar problem

I like this statement in particular:

 > Very few people have depended on the actual markup generated here so 
it's likely you are not impacted.

great attitude from them :/

**Comment by mike-thompson-day8** [comment]
I think we can close this ticket. @holmsand has already added React 15 to Reagent v0.6.0 and that work has been pretty solidly tested through a series of alpha releases, all without incident. The only feedback have been reports about React 15 being stricter in its validity checks (which is a good thing) and some gotchas around reduced spans.
