### ISSUE TITLE
(when) always renders as if cond is true

### ISSUE THREAD

**Issue by mbertheau** [reagent-project/reagent#187]
```clojure
[:p (if nil "if nil" "else nil")]
```
renders as
```html
<p data-reactid="...">else nil</p>
```
which is as expected, but 

```clojure
[:p (when nil "when nil")]
```
renders as
```html
<p data-reactid="...">when nil</p>
```
where I'd expect
```html
<p data-reactid="..."></p>
```

Am I missing something here?

**Comment by antishok** [comment]
This is working fine for me. Can you post a full testcase?
Also maybe try cleaning your output files and rebuilding, just in case.

**Comment by mike-thompson-day8** [comment]
@mbertheau `[:p (when nil "when nil")]`  will evaluate to `[:p nil]` which will be rendered as `<p ...></p>`

The only way for `(when nil "when nil")` to evaluate to `"when nil"` is if there was a bug in clojurescript itself - which seems unlikely and, even were it true, it wouldn't be a reagent issue.   

So I'm going to close this.  I'd encourage you to retest.  And, if necessary, to take this up in the various help forums like:
   - http://clojurians.net/     (#reagent channel)
   -  https://groups.google.com/forum/#!forum/clojurescript

**Comment by mbertheau** [comment]
I had a symbol `when` in the scope. Sorry for the noise.
