### ISSUE TITLE
nodes/components as attribute values?

### ISSUE THREAD

**Issue by rinconjc** [reagent-project/reagent#189]
This is an awesome library!
I'd like to know if it's possible to have nodes (react components) as attribute values?. Specifically, I'm trying to use the Tab component from react-bootstrap library which support the "tittle" attribute as a node.
Something like this:

```clojure
(def tabs (r/adapt-react-class js/ReactBootstrap.Tabs))
(def tab (r/adapt-react-class js/ReactBootstrap.Tab))

(defn my-tabs []
[tabs
[tab {:title [:h4 "custom tab header"]}
"My tab 1 content"]])
```

**Comment by danielcompton** [comment]
Hi @rinconjc, the Github issues for this project are for feature requests and bug reports. Here are some other places which are better for this kind of discussion: https://github.com/reagent-project/reagent/blob/master/CONTRIBUTING.md#support-questions

**Comment by vans163** [comment]
I am looking for this too, its not really documented much. Iv went through much of these examples without success https://reagent-project.github.io/news/news050.html.

To be clear I have a UDM library which has a React class called <DatePicker />. How do you use this in Reagent?
