### ISSUE TITLE
Making ReactRouter and reagent play nicely together

### ISSUE THREAD

**Issue by stopachka** [reagent-project/reagent#192]
I am experiment with building an isomorphic cljs application, and am a bit confused with making node + cljs dependencies play well together.

- reagent depends on cljs/react
- React Router depends on node's react

I wanted to use React Router, so I managed to get it working on the server by 
1) excluding reagent cljs/react from reagent
2) making an empty namespace, cljsjs.react
3) adding node's React to the preamble

// project.clj

    (defproject stepanp "0.0.1"
      ...
      :profiles {:default [:cljs-shared]
                 :cljs-shared
                 {:dependencies [...
                                 [reagent "0.5.1" :exclusions [cljsjs/react]]]
                                 ;; am excluding cljsjs/react, to use one from node, in order to also use ReactRouter
                  :plugins [[lein-cljsbuild "1.1.0"]]
                  :cljsbuild
                  {:builds [{:id "server"
                             :source-paths ["src-cljs"]
                             :compiler
                             {:main "stepanp.core-server"
                              :target :nodejs
                              :output-to "deploy/index.js"
                              :output-dir "out-server"
                              :preamble ["include.js"]
                              :optimizations :simple
                              :language-in :ecmascript5
                              :language-out :ecmascript5}}
                            {:id "client"
                             :source-paths ["src-cljs"]
                             :compiler
                             {:main "stepanp.core-client"
                              :output-to "resources/js/stepanp.compiled.js"
                              :output-dir "out-client"
                              :optimizations :advanced
                              :pretty-print false}}]}}})

// include.js (preamble to server) 

        var React = require("react");
        var ReactRouter = require('react-router');
        var createLocation = require('history/lib/createLocation');
        var createBrowserHistory = require('history/lib/createBrowserHistory');

// server.cljs 

    (js/React.renderToString
      ((js/React.createFactory js/ReactRouter.RoutingContext)

**Now, the problem**
How does the client get access to it?

// client.cljs

    js/React ;; undefined

// package.json 

    "dependencies": {
      "logfmt": "^1.2.0",
      "express": "^4.13.3",
      "react": "^0.13.3",
      "react-router": "1.0.0-rc1",
      "history": "^1.9.1"
    },

It seems to me like the best solution would be to leave all the dependencies to ClojureScript and the compiler.

But, cljsjs is not up to date with ReactRouter. What should my foreign-libs look like, so reagent works, react-router works, and react works?

**Comment by jaen** [comment]
As of now your best bet is to use browserify or webpack to demodulify the libraries and use the resulting file as a foreign lib. Here's an example of someone doing this to a material ui lib for React - https://github.com/taylorSando/om-material-ui/tree/master/build-mui

**Comment by stopachka** [comment]
thanks @jaen! Trying now
