### ISSUE TITLE
Shearing on squares async demo

### ISSUE THREAD

**Issue by chr15m** [reagent-project/reagent#194]
I am experiencing shearing of sprites in an HTML5 game I am building with Reagent. I went to this demo page and I see shearing on the color changing squares:

https://reagent-project.github.io/news/reagent-is-async.html

How can I verify that requestAnimationFrame is indeed being called and the rendering is happening during my monitor's vblank?

**Comment by mike-thompson-day8** [comment]
@chr15m the code you are after is in 
https://github.com/reagent-project/reagent/blob/master/src/reagent/impl/batching.cljs

Perhaps in your code, you could do this: 
    `(reagent.impl.batching/do-after-flush  #(println "I'm after an animation frame"))`

Your  `println` function  will then run after the render queue is finished.  See:
       https://github.com/reagent-project/reagent/blob/master/src/reagent/impl/batching.cljs#L64

**Comment by chr15m** [comment]
Hi, cool, thanks for the hook. What I am referring to is "tearing" like this:

![](https://en.wikipedia.org/wiki/Screen_tearing#/media/File:Tearing_%28simulated%29.jpg)

<https://en.wikipedia.org/wiki/Screen_tearing>

I will do some investigation into whether this is due to some local property of my machine (e.g. bad video driver) or the reagent code doing requestAnimationFrame incorrectly.

**Comment by chr15m** [comment]
I'm interested to know if anybody else sees tearing on this demo too:

https://reagent-project.github.io/news/reagent-is-async.html

**Comment by mike-thompson-day8** [comment]
I don't see tearing on Chrome/Windows.

**Comment by mike-thompson-day8** [comment]
@chr15m  I'm wondering what to do with this issue.  Did you resolve?  More information available?

**Comment by chr15m** [comment]
@mike-thompson-day8 I've tested this on another older, slower machine and I can't replicate the shearing effect.

I think we can mark this down to my laptop's graphics driver/card and I'll have to investigate that myself. Sorry for the noise!
