### ISSUE TITLE
Macro names .' and .! not in compliance with symbol name limitation

### ISSUE THREAD

**Issue by settinghead** [reagent-project/reagent#196]
I ran into issue when trying to compile the Reagent source code with [cljs-bootstrap](https://github.com/swannodette/cljs-bootstrap). Specifically, the name for [`.'`](https://github.com/reagent-project/reagent/blob/master/src/reagent/interop.clj#L26) and [`.!`](https://github.com/reagent-project/reagent/blob/master/src/reagent/interop.clj#L42) does not seem to be in compliance with [symbol naming limitations](http://clojure.org/reader#The Reader--Reader forms): 

> Symbols beginning or ending with '.' are reserved by Clojure.

As a result, the compiler translates `.'` incorrectly to `._SINGLEQUOTE_` (which gives a JavaScript syntax error, instead of something like `_DOT__SINGLEQUOTE`)
Any chance they can be renamed? Or is there a workaround? 

Thanks

**Comment by mike-thompson-day8** [comment]
@holmsand it would be good for reagent to be cljs-bootstrap-able.  So I recommend we action this even though this might be considered a breaking change, if someone considered these macros to be a part of the API.  

Does anyone have thoughts about good alternatives: 
   -  `.'`  ->  ??
   - `.'`   -> ??

See:  https://github.com/reagent-project/reagent/blob/master/src/reagent/interop.clj

**Comment by holmsand** [comment]
I went for $ and $! respectively (because they are short...).

.' and .! are just deprecated for now (but no longer used in reagent itself), and you should get a warning at compile time if you try to use them.

**Comment by settinghead** [comment]
@holmsand  That works. Thanks.
