### ISSUE TITLE
colspan

### ISSUE THREAD

**Issue by colorgmi** [reagent-project/reagent#199]
I want to do some render table like:

[:table.table.table-bordered
     [:tbody
      [:tr
       [:th {:colspan "2"} "2"]]
      [:tr
       [:th 1]
       [:th 2]]]]

BUT, after rendered in browser (Chrome), there is no colspan property here, I have no idea what's wrong.

**Comment by gadfly361** [comment]
This is a subtle gotcha, try `:col-span` instead.  

React.js supports the attribute as colSpan, which is camelcase, and we just need to convert that to dashes instead.

**Comment by mike-thompson-day8** [comment]
Similarly, `auto-focus` must be used instead of `autoFocus`.

**Comment by mike-thompson-day8** [comment]
I believe this has been answered, so I'm closing.
