### ISSUE TITLE
Any way to async render a component in a go loop

### ISSUE THREAD

**Issue by hmgibson23** [reagent-project/reagent#204]
Basically, I fetch some data from the server, put it in the state and do some fairly heavy processing on the data in the view (as in just one part of the data). Ideally I'd like to go through my data asynchronously and render the components once the processing is done. Currently when I try to render in a go loop, nothing happens. 

Any help/ideas appreciated...

**Comment by outamaa** [comment]
I don't know if this is a recommended way to achieve this, but one way to get intermediate resultsfrom a go block for rendering can be achieved along these lines:
```clojure
(defn heavy-processing []
  (let [progress-atom (reagent/atom nil)]
    {:progress progress-atom
     :go-block (go (do-stuff)
                   (reset! progress-atom "Did do-stuff")
                   (do-more-stuff)
                   (reset! progress-atom "Did do-more-stuff"))}))
```
You can pass `progress-atom` as an argument to a rendering function, and as the go block updates the value of the atom, the component is rerendered.

**Comment by hmgibson23** [comment]
Thanks I'll give it a go!

**Comment by mike-thompson-day8** [comment]
Closing this.  Best if support questions are directed to these places:  https://github.com/reagent-project/reagent/blob/master/CONTRIBUTING.md#support-questions
