### ISSUE TITLE
got some problems building the docs in gh-pages branch

### ISSUE THREAD

**Issue by jiyinyiyong** [reagent-project/reagent#206]
I was translating the docs and pushed it to GitHub,
http://react-china.github.io/reagent/
https://github.com/react-china/reagent

Then I found an exception and all demos not running(will probably reproduced opening the link above):

![image](https://cloud.githubusercontent.com/assets/449224/11425348/42cc8916-948f-11e5-8e71-a7fcf7018968.png)

I looked into it, it was:

``` js
clojure.string.replace.call(null, '', base_5752, /^\/, ''/)
```

and `base_5752` is a string starting with `/`. I can't figure out what was happening and how I can run the demo now.

And this project is somehow using very outdated ClojureScript, which official release is already `1.7.170`.

**Comment by Deraen** [comment]
Example site build scripts are now rewritten, and we are using new Cljs etc., so I think these are fixed, or at least the problems would be different now.
