### ISSUE TITLE
Recommended aproach of using a Reagent component as a React component from js?

### ISSUE THREAD

**Issue by jbeja** [reagent-project/reagent#210]

**Comment by danielcompton** [comment]
From [CONTRUBUTING.md](https://github.com/reagent-project/reagent/blob/master/CONTRIBUTING.md)

Support questions

The Github issues for Reagent **are for bug reports and feature requests**. Support requests and usage questions should go to the Clojure Slack channel, the ClojureScript mailing list, or the Reagent mailing list.

**Comment by jbeja** [comment]
Fair enough.
