### ISSUE TITLE
Auto keying collections

### ISSUE THREAD

**Issue by whamtet** [reagent-project/reagent#211]
I very often find myself using the same pattern

```clojure
(map-indexed #(with-meta %2 {:key %1}) collection)
```

React wants us to key items in a collection.  Since Clojure collections are immutable can't we just abstract this away by keying on the object hash?  I'm happy to make a contribution...

**Comment by whamtet** [comment]
It won't work.

**Comment by whamtet** [comment]
Bad idea, how do I delete?

**Comment by mike-thompson-day8** [comment]
Not possible unfortunately:  https://github.com/isaacs/github/issues/253

But closing is good enough  :-)
