### ISSUE TITLE
tr doesn't have on-click

### ISSUE THREAD

**Issue by shmish111** [reagent-project/reagent#213]
The following code:
```clj
[:tr {:class "somethin" :on-click some-real-function}
  [:td "hi"]]
```
will produce
```html
<tr class="somethin">
    <td>hi</td>
</tr>
```
Where is my `onClick` :(

If I put the same `:on-click some-real-function` in a button element it works fine.

I need clickable table rows ;(

**Comment by mike-thompson-day8** [comment]
Please don't ask this sort of question here.  Repo issues are for bug reports and feature requests. 

**Support requests and usage questions should go to the [Clojure Slack channel](http://clojurians.net), the [ClojureScript mailing list](https://groups.google.com/forum/#!forum/clojurescript), or the [Reagent mailing list](https://groups.google.com/forum/#!forum/reagent-project).**

But, to answer your question .... this is expected.  React uses "Event Delegation".  [From the React docs](https://facebook.github.io/react/docs/interactivity-and-dynamic-uis.html#under-the-hood-autobinding-and-event-delegation):

>Event delegation: React doesn't actually attach event handlers to the nodes themselves. When React starts up, it starts listening for all events at the top level using a single event listener. When a component is mounted or unmounted, the event handlers are simply added or removed from an internal mapping. When an event occurs, React knows how to dispatch it using this mapping. When there are no event handlers left in the mapping, React's event handlers are simple no-ops.
