### ISSUE TITLE
Do not encode content of style tag

### ISSUE THREAD

**Issue by niquola** [reagent-project/reagent#214]
When creating [:style "body {font-family: 'Exo 2'}"] tag, resulting css is encoded:

```
body {
  font-family: &#x27;Exo 2&#x27;;
}
```

**Comment by ducky427** [comment]
The correct way of doing inline styles with reagent is something like this:

```clojure
[:body {:style {:font-family "Exo 2"}} "...."]
```

I think this issue is best answered/clarified on the #reagent on clojurians slack channel.

**Comment by mike-thompson-day8** [comment]
@ducky427   Thanks for answering!

@niquola  github issues are for Reagent bug reports and feature requests. Support requests and usage questions should go to the Clojure Slack channel, the ClojureScript mailing list, or the Reagent mailing list.
