### ISSUE TITLE
Tests do not re-render

### ISSUE THREAD

**Issue by AshtonKem** [reagent-project/reagent#217]
The default specs created by reagent-template don't appear to re-render when any reagent atoms change, despite the fact that :on-click callbacks appear to work as expected.

I've created a very minimal test case to demonstrate the problem here: https://github.com/AshtonKem/reagent-bad-test-example

**Comment by ducky427** [comment]
Hi @AshtonKem, for the example you've given, when I click "Increment!", the click count title does increment. So not sure what the issue is.

**Comment by AshtonKem** [comment]
The tests do not work. 

--
Ashton

**Comment by AshtonKem** [comment]
Or rather, it's not obvious how to make reagent re-render from a cljs testing perspective. 

--
Ashton

**Comment by ducky427** [comment]
@AshtonKem, I misunderstood the problem. below is the correct solution. Essentially you were calling `with-mounted-component` incorrectly and you need to flush after the click event.

```clojure
(deftest test-home
  (with-mounted-component [rc/home-page]
    (fn [c div]
      (let [h2 (.getElementById js/document "title")]
        (is (= "Welcome to bad-tests, click count is 0" (.-textContent h2))))
      (click (.getElementById js/document "click"))
      (reagent/flush)
      (let [h2 (.getElementById js/document "title")]
        (is (= "Welcome to bad-tests, click count is 1" (.-textContent h2)))))))
```

For the future, these questions are best answered over clojurians slack on the google group.

**Comment by mike-thompson-day8** [comment]
@ducky427 appreciate the help.  Thanks!

@AshtonKem  As indicated above, support questions should not be asked here. This issue tracker is for reporting bugs and feature requests. Instead, please ask in Clojure Slack http://clojurians.net/, or the ClojureScript mailing list https://groups.google.com/forum/#!forum/clojurescript
