### ISSUE TITLE
Unable to access variable inside atom variable

### ISSUE THREAD

**Issue by ArchanaKalidoss** [reagent-project/reagent#218]
Hi,

Could you please tell how to access or print the variable "first" inside the atom variable contact?

(def default-db
  (reagent/atom {:name [{:first "Abe" :middle "Cibi" :last "Kiwi"}]}))

**Comment by ArchanaKalidoss** [comment]
Typo in the above question. Inside the atom variable "name" ?

**Comment by ducky427** [comment]
Hi @ArchanaKalidoss, 

Github issues are for Reagent bug reports and feature requests. Support requests and usage questions should go to the Clojure Slack channel, the ClojureScript mailing list, or the Reagent mailing list.

That said, 

```clojure
(:name @default-db)
```

should work. For details, please use the above channels to get help.
