### ISSUE TITLE
use key metadata but still get warning

### ISSUE THREAD

**Issue by zjhmale** [reagent-project/reagent#219]
i use `^{:key key}` metadata in a for structure but still get the warning

```
Warning: Every element in a seq should have a unique :key
```

i use reagent 0.5.1 and re-frame 0.6.0

**Comment by mike-thompson-day8** [comment]
Support questions should not be asked here.  This issue tracker is for reporting bugs and feature requests.   Instead, please ask in Clojure Slack http://clojurians.net/, or the ClojureScript mailing list https://groups.google.com/forum/#!forum/clojurescript

Having said that, I think that message is telling you that you are providing duplicate keys.  Keys must be unique among sibling components/elements.

**Comment by zjhmale** [comment]
:ok_hand:
