### ISSUE TITLE
run! is triggered with nil value after exception is thrown in another run!

### ISSUE THREAD

**Issue by metametadata** [reagent-project/reagent#223]
Reproducible in v.0.6.0-alpha; v0.5.1 works as expected. Tested in browsers: Chrome 49, Safari 9.

__Steps__
1) It's the smallest example I could come up with and it corresponds to the real scenario in my project where there are several run!s listening to the model reaction:
```cljs
(ns app.core
  (:require [reagent.core :as r])
  (:require-macros [reagent.ratom :refer [reaction run!]]))

(enable-console-print!)

(def model (r/atom {:val 1}))
(def readonly-model (reaction @model))

(run!
  (println "model change:" (pr-str @readonly-model)))

(let [val (reaction (:val @readonly-model))]
  (run!
    (println "val change:" (pr-str @val))))

(run!
  (when (:error? @readonly-model)
    (throw (ex-info "Error detected!" {}))))

(println "swap!")
(swap! model assoc :error? true)
```

2) See browser console log.

__Actual__
There's an unexpected "val change: nil" at the end:
```
model change: {:val 1}
val change: 1
swap!
model change: {:val 1, :error? true}
Uncaught #error {:message "Error detected!", :data {}}
val change: nil
```

__Expected__
```
model change: {:val 1}
val change: 1
swap!
model change: {:val 1, :error? true}
Uncaught #error {:message "Error detected!", :data {}}
```

**Comment by holmsand** [comment]
Thanks!

This problem appears to be fixed now in master.

**Comment by metametadata** [comment]
Thanks!

I've since moved away from using run! and started using add-watch. Mostly due to the fact that run!  macro catches all derefs inside its body which can lead to hard to debug behaviour, as discussed here: https://groups.google.com/d/msg/reagent-project/8yFATqOMB7U/u--Uo-_QKgAJ

Also making a reaction simulate the "readonly" ratom was not the good idea because reactions and ratoms have slightly different behavior (e.g. add-watch works differently).

**Comment by metametadata** [comment]
Works as expected in v0.6.0-rc.
