### ISSUE TITLE
How does re-rendering work?

### ISSUE THREAD

**Issue by ccorcos** [reagent-project/reagent#224]
What does this mean?

> Any component that uses an atom is automagically re-rendered when its value changes.

https://reagent-project.github.io/

How does a function know to re-render?

**Comment by zjhmale** [comment]
@ccorcos just like the example shows that

```clojure
(defn counting-component []
  [:div
   "The atom " [:code "click-count"] " has value: "
   @click-count ". "
   [:input {:type "button" :value "Click me!"
            :on-click #(swap! click-count inc)}]])
```

the div display the internal value of the atom `click-count` and there is a button down below to change the value of the atom. everytime you click the button to inc the value of `click-count`, the `counting-component` component will be automagically re-rendered.

**Comment by ccorcos** [comment]
I get that it does, but my question is how? How does the function know it
needs to be re-run? This isn't something that's built into clojure is it?

**Comment by mike-thompson-day8** [comment]
Github issues for Reagent are for bug reports and feature requests. Support requests and usage questions should go to the [Clojure Slack channel](http://clojurians.net), the [ClojureScript mailing list](https://groups.google.com/forum/#!forum/clojurescript), or the [Reagent mailing list](https://groups.google.com/forum/#!forum/reagent-project).

Your questions above will be answered if you read these 3 pages:
1.  https://github.com/Day8/re-frame/wiki/Creating%20Reagent%20Components
2.  https://github.com/Day8/re-frame/wiki/Using-%5B%5D-instead-of-%28%29
3. https://github.com/Day8/re-frame/wiki/When-do-components-update%3F

**Comment by ludbek** [comment]
@ccorcos 
To understand how Reagent knows which component to re render when a value changes, I think you should look at following places.

1. https://github.com/lynaghk/reflex/blob/master/src/cljs/reflex/core.cljs#L18
2. https://repl.it/@ludbek/HighFractalRefactoring#main.clj

My guess is, when Reagent renders a component it keeps track of the reagent/atoms that are being dereferenced by the component. The answer to how Reagent knows which atoms are being dereferenced, see how the code in the first link extends `atom` to notify when it is dereferenced.

The code in the 2nd link is trying to mimic how https://github.com/mobxjs/mobx works.
