### ISSUE TITLE
Am I using run! wrong?

### ISSUE THREAD

**Issue by deg** [reagent-project/reagent#226]
(Not sure if I'm reporting a bug or, just exposing how new I am to Reagent).

If I read the atom inside the function called by a run! watching a cursor in the atom, it dives into an infinite loop.

Here's a bit of my code
````
(defn get-state [path]
  (get-in @app-state path))

(defn subscribe [path f]
  (run! (f @(cursor app-state path))))

;; ...

(subscribe [:this] #(side-effect (get-state [:that])))

;; side-effect is called repeatedly forever, rather than being called just once per change of :this.
;; If I remove my call to (get-in @app-state ...), then side-effect is only called once

````

Is what I'm doing legitimate?

Big picture -- I want certain side effects to occur anytime a particular element of my state is modified. This does not involve modifying the dom. In order to perform this action, I need to read other parts of my state too.

Is run! the correct API I should be using for this?

**Comment by danielcompton** [comment]
Github issues for Reagent are for bug reports and feature requests. Support requests and usage questions should go to the [Clojure Slack channel](http://clojurians.net/), the [ClojureScript mailing list](https://groups.google.com/forum/#!forum/clojurescript), or the [Reagent mailing list](https://groups.google.com/forum/#!forum/reagent-project).

**Comment by deg** [comment]
Thanks. I've moved this to https://groups.google.com/forum/#!topic/reagent-project/8yFATqOMB7U
