### ISSUE TITLE
Composition of third-party components (React Router)

### ISSUE THREAD

**Issue by stepugnetti** [reagent-project/reagent#227]
Hi! I'm having problems in creating custom components starting form [React Router][1]. It may be connected to the API for composing components (issues [#13][2] and [#68][3]). The code for reproducing the problem and a thorough description can be found [here](https://github.com/stepugnetti/react-router-issue).

The components I use appear to have been imported successfully form the WebPack bundled version provided by the authors (instead of using the Cljsjs port, the version number has been increasing a lot since the cljsjs version): they work fine if I use them directly. If I try to use them in a composition, then the page is not rendered correctly. I've tried several forms of composition, but none seems to work.

[1]:(https://github.com/reactjs/react-router)
[2]:(https://github.com/reagent-project/reagent/issues/13)
[3]:(https://github.com/reagent-project/reagent/issues/68)

**Comment by mike-thompson-day8** [comment]
Reagent uses Github issues for bug reports and feature requests. Support requests and usage questions should go to the #reagent channel in [Clojure Slack](http://clojurians.net/) or the [ClojureScript mailing list](https://groups.google.com/forum/#!forum/clojurescript).
