### ISSUE TITLE
React TransitionGroup

### ISSUE THREAD

**Issue by Odinodin** [reagent-project/reagent#228]
Is it possible to use the React TransitionGroup (see https://facebook.github.io/react/docs/animation.html#low-level-api-reacttransitiongroup) from Reagent?

The reason is that I want to use inline CSS instead of CSS classes.

See http://codepen.io/makenosound/pen/rstvx for an example use case.

**Comment by danielcompton** [comment]
Github issues for Reagent are for bug reports and feature requests. Support requests and usage questions should go to the [Clojure Slack channel](http://clojurians.net/), the [ClojureScript mailing list](https://groups.google.com/forum/#!forum/clojurescript), or the [Reagent mailing list](https://groups.google.com/forum/#!forum/reagent-project).
