### ISSUE TITLE
Forward setNativeProps to children

### ISSUE THREAD

**Issue by seanhess** [reagent-project/reagent#232]
I'm using reagent to create a react-native app. If I start with this template: https://github.com/drapanjanas/re-natal/blob/master/resources/cljs-reagent/core.cljs, and try to move the `text` for the button into a custom component, I get an error: 

```
(defn button-label [message]
  [text {:style {:color "white" :text-align "center" :font-weight "bold"}} message]
  )

; ... if I change app-root to use the above
       [touchable-highlight {:style {:background-color "#999" :padding 10 :border-radius 5}
                             :on-press #(alert "HELLO!")}
        [button-label "press me now"]]])))
```

The error I get is "Touchable child must either be native or forward setNativeProps to a native component". 

Some google presents [this solution](https://github.com/facebook/react-native/issues/1040)

```
  setNativeProps: function (props: Object) {
    this.children.forEach(function(child) { child.setNativeProps(props) })
  },
```

I'm not sure that fixes the error (I'm new to clojure and not sure how to test this), but it seems like it would work, and wouldn't trigger or get in the way for non-native react applications. 

[Here's an article from the React docs explaining](https://facebook.github.io/react-native/docs/direct-manipulation.html)

Thanks!

**Comment by Deraen** [comment]
This does look like React-native problem, not Reagent.
