### ISSUE TITLE
is reagent/render behaviour ok ?

### ISSUE THREAD

**Issue by WeweTom** [reagent-project/reagent#238]
reagent/render-to-string render a unchanged component multiple times but get diffrent result , this lead to   re-render ,  is this the expected  behaviour?

![qq20160515-0 2x](https://cloud.githubusercontent.com/assets/243645/15274899/7ce9bea6-1af0-11e6-9903-3da69cae6778.png)

**Comment by mike-thompson-day8** [comment]
There's no Reagent bug here. 

There's a fair bit of background material out there, for example:
- https://github.com/facebook/react/issues/3300
- http://stackoverflow.com/questions/34311221/what-is-checksum-in-react-and-how-to-use-it

Reagent uses Github issues for bug reports and feature requests. Support requests and usage questions like this one should go to the #reagent channel in [Clojure Slack](http://clojurians.net/) or the [ClojureScript mailing list](https://groups.google.com/forum/#!forum/clojurescript).

Closing.
