### ISSUE TITLE
Implementing with-class function

### ISSUE THREAD

**Issue by smogg** [reagent-project/reagent#240]
I've implemented a `with-class` fn that will add the given class to the passed element and it looks like this:

```clojure
(defn with-attrs
  "Adds some attrs to an element."
  [attrs elem]
  (update elem 1 merge-attrs attrs))

(defn with-class
  "Adds a class to a component."
  [cls component]
  (if (vector? component)
   (r/as-element (with-attrs {:class cls} component))
   (fn with-class-outer* [_ _ & outer-props]
    (let [outer-comp (apply component outer-props)]
      (fn with-class-inner* [_ _ & inner-props]
        (let [inner-comp (apply outer-comp inner-props)]
          (with-attrs {:class cls} inner-comp)))))))
```

The fn allows me to do the following and get working components in following ways:

```clojure
(def app-state (reagent/atom 2))

(defn form-2-comp
  []
  (swap! app-state + 5)
  (fn []
   [:div {:class ""}
    [:h2 @app-state]
    [:button {:on-click #(swap! app-state inc)}
     "click"]]))

(d/with-class "some-class" [:div {:class ""} "hiccups called with ()"])
(d/with-class "some-class" [:div {:class ""} "hiccups called with []"])
[d/with-class "some-class" form-2-comp]
```

Now, because of what `with-class` returns, using it on simple hiccups kills the simplicity and doing something like simple equality testing is no longer possible:

```clojure
(is (= (with-class "some-class" [:a])
       [:a {:class "some-class"}]))
```

What would be the _correct_ approach to writing this? If my goal was to still get a simple hiccups back when a simple form-1 component is passed to `with-class`, how would I do that without knowing how user is calling `with-class` (`[]` or `()`)? Last but not least, maybe I shouldn't allow users to call `with-class` using `[]` in the first place, and I should return a component wrapped in `[]` directly from `with-class`?

**Comment by Deraen** [comment]
I would avoid such function if possible. I can think of two much simpler ways to change styles of elements inside a component.

1. Add a class option or such to the component. `[some-component {:class "some-class"} "something"]`
2. Wrap the component in a div with the class and change CSS to style elements inside this div: `[:div.some-class [some-component "something"]]`

Also, this seems more like a usage question than bug report or feature request, and thus should be discussed elsewhere: https://github.com/reagent-project/reagent/blob/master/CONTRIBUTING.md#support-questions

**Comment by smogg** [comment]
Fair enough, thanks you.
