### ISSUE TITLE
API Docs link in README.md is broken

### ISSUE THREAD

**Issue by karthik-singaravelan** [reagent-project/reagent#246]
The link to API Docs at http://blog.ducky.io/reagent-docs/index.html throws an error saying that the host cannot be resolved.

**Comment by ducky427** [comment]
@karthik-singaravelan, I maitain that link and it works for me.

**Comment by ducky427** [comment]
you can also try: http://ducky427.github.io/reagent-docs

**Comment by karthik-singaravelan** [comment]
@ducky427 I tried the intial one http://blog.ducky.io/reagent-docs/index.html.  I tried from my workstation and also tried from my ec2 instance both threw me a host not found error. I tried the new and got a 302 redirect blog.ducky.io/reagent-docs which also doesn't work strangely. I will check again from home. Thanks.

**Comment by ducky427** [comment]
@karthik-singaravelan, it could be a dns issue on my domain. let me check and fix it if thats the case.

**Comment by ducky427** [comment]
@karthik-singaravelan, it should be working now.

**Comment by tirkarthi** [comment]
@ducky427 Its working fine now and the issue can be closed. Thanks :)

**Comment by ducky427** [comment]
@mike-thompson-day8, perhaps this can be hosted under reagent-project namespace. I'm happy to maintain it.
