### ISSUE TITLE
Difference between r/as-element and r/reactify-component

### ISSUE THREAD

**Issue by hanwencheng** [reagent-project/reagent#248]
Hi, 

I have used reagent for several weeks, but sometimes I really don't know which one to use.

After reading [News in 0.5.0](https://reagent-project.github.io/news/news050.html) As I understood,
 
* r/as-element is used only used for Reagent’s hiccup forms 
* r/reactify-component is used for a whole piece of code like a whole cljs file
Is it right?

Thanks in advanced

**Comment by danielcompton** [comment]
Github issues for Reagent are for bug reports and feature requests. Support requests and usage questions should go to the [Clojure Slack channel](http://clojurians.net/), the [ClojureScript mailing list](https://groups.google.com/forum/#!forum/clojurescript), or the [Reagent mailing list](https://groups.google.com/forum/#!forum/reagent-project).
