### ISSUE TITLE
How to suppress warnings

### ISSUE THREAD

**Issue by ertugrulcetin** [reagent-project/reagent#254]
![screen shot 2016-07-14 at 18 00 03](https://cloud.githubusercontent.com/assets/8271291/16844219/ea0ebd4e-49ec-11e6-9ce0-bd6bbbaad01e.png)

**Comment by xfthhxk** [comment]
@ertugrulcetin It is something that React ultimately uses.  [See here.](https://facebook.github.io/react/docs/multiple-components.html#dynamic-children)

You can add the :key to the attribute map for each of the :td elements.  
```[:tr [:td {:class "title" :key 1} ...] [:td {:class "votelinks" :key 2} ..]]```

**Comment by mike-thompson-day8** [comment]
Although re-frame oriented, this answer might help you:
http://stackoverflow.com/questions/37164091/how-do-i-loop-through-a-subscribed-collection-in-re-frame-and-display-the-data-a/37186230#37186230

I'm going to close this.  This is effectively a support question and should be handled via other forums.
