### ISSUE TITLE
:simple CLJS optimization triggers compilation error

### ISSUE THREAD

**Issue by rationalism** [reagent-project/reagent#255]
I'm using Reagent version 0.6.0-rc. My code works with :none or :whitespace optimization, but with :simple optimization, it throws this error while compiling:

Jul 17, 2016 4:35:27 AM com.google.javascript.jscomp.LoggerErrorManager println
SEVERE: <project directory>/resources/public/js/main/reagent/dom.js:9: ERROR - required "cljsjs.react.dom" namespace never provided
goog.require('cljsjs.react.dom');
^

Jul 17, 2016 4:35:27 AM com.google.javascript.jscomp.LoggerErrorManager println
SEVERE: <project directory>/resources/public/js/main/reagent/dom/server.js:4: ERROR - required "cljsjs.react.dom.server" namespace never provided
goog.require('cljsjs.react.dom.server');
^

Jul 17, 2016 4:35:27 AM com.google.javascript.jscomp.LoggerErrorManager println
SEVERE: <project directory>/resources/public/js/main/reagent/impl/util.js:4: ERROR - required "cljsjs.react" namespace never provided
goog.require('cljsjs.react');
^

Jul 17, 2016 4:35:27 AM com.google.javascript.jscomp.LoggerErrorManager printSummary
WARNING: 3 error(s), 0 warning(s)
ERROR: JSC_MISSING_PROVIDE_ERROR. required "cljsjs.react.dom" namespace never provided at <project directory>/resources/public/js/main/reagent/dom.js line 9 : 0
ERROR: JSC_MISSING_PROVIDE_ERROR. required "cljsjs.react.dom.server" namespace never provided at <project directory>/resources/public/js/main/reagent/dom/server.js line 4 : 0
ERROR: JSC_MISSING_PROVIDE_ERROR. required "cljsjs.react" namespace never provided at <project directory>/resources/public/js/main/reagent/impl/util.js line 4 : 0

**Comment by danielcompton** [comment]
Github issues for Reagent are for bug reports and feature requests. Support requests and usage questions should go to the [Clojure Slack channel](http://clojurians.net/), the [ClojureScript mailing list](https://groups.google.com/forum/#!forum/clojurescript), or the [Reagent mailing list](https://groups.google.com/forum/#!forum/reagent-project).
