### ISSUE TITLE
ReagentInput `:ref` broken

### ISSUE THREAD

**Issue by Deraen** [reagent-project/reagent#259]
https://github.com/reagent-project/reagent/commit/42ba1662cbc62dc7ebc0c437abe990f1acbe9840 broke using `:ref` attribute with input elements. This is because `:ref` attribute is always overriden for these elements: https://github.com/reagent-project/reagent/blob/42ba1662cbc62dc7ebc0c437abe990f1acbe9840/src/reagent/impl/template.cljs#L186

If the code keeps on going using `:ref` callback, it must keep track of the original function and call that. If ref callback is used, string ref can never be supported here, but maybe that is not a problem as those haven't really worked with Reagent anyway.

**Comment by holmsand** [comment]
Great catch! The patch looks good too as far as I can tell – I'll put that into a 0.6.1. Thanks!

**Comment by pesterhazy** [comment]
FWIW I do use string based `:ref`s for `input` elements. Mostly for historical reasons -- `ref` callbacks (which are superior) didn't exist a while ago.

**Comment by pesterhazy** [comment]
BTW I use `(aget (.-refs (r/current-component)) "my-input")` to get the backing instance of the component

**Comment by Deraen** [comment]
Check PR https://github.com/reagent-project/reagent/pull/260, looks like ReagentInput will be using findDOMNode so it doesn't need to touch refs at all.
