### ISSUE TITLE
`:input` BUG in `0.6.0`

### ISSUE THREAD

**Issue by stumitchell** [reagent-project/reagent#264]
This small project https://github.com/stumitchell/reagent-bug
generated from the reagent-template, shows the problem.

`:input` seems to not like the `:checked` argument changing from `:a` to `nil` which was fine in previous versions.

Consuming projects may have assumed the previous behaviour (in this case `re-com`) and this bug is not obvious at all.

**Comment by Deraen** [comment]
This is working as expected.

https://reactjs.org/docs/forms.html#controlled-components
