### ISSUE TITLE
:ref callback fns don't work with controlled input components?

### ISSUE THREAD

**Issue by ptaoussanis** [reagent-project/reagent#267]
Hi there!

Currently using `[reagent "0.6.0"]`, though I believe this behaviour may extend to earlier versions?

Something like `(defn cmpt1 [] [:div {:ref (fn [node] (println "node is available"))}])` works as expected.

If you try the same with a controlled `:input` or `:textarea`, the `:ref` callback appears to be lost - perhaps as a result of the transformation at https://github.com/reagent-project/reagent/blob/b65afde4d7ac4864d7e355acdc16977cb92afa3c/src/reagent/impl/template.cljs#L278?

Is this a known issue? Something that could potentially be solved?

Closest mention I could find in the existing issues is https://github.com/reagent-project/reagent/issues/5, but that seems to be a different problem (and/or doesn't seem to be relevant in general to callback `:ref`s?).

Current workaround I'm using is just to wrap input components in a extra `[:div <input>]`, then using the parent div's :ref to grab the child node when it exists.

Thanks, cheers! :-)

**Comment by Deraen** [comment]
https://github.com/reagent-project/reagent/issues/259

**Comment by ptaoussanis** [comment]
@Deraen Awesome, thanks Juho! Sorry for missing that :-)
