### ISSUE TITLE
Warning: You are manually calling a React.PropTypes validation function ... See https://fb.me/react-warning-dont-call-proptypes for details.

### ISSUE THREAD

**Issue by vans163** [reagent-project/reagent#268]
Creating a Row component like so:

``` html
<script src="https://unpkg.com/react@15.3.2/dist/react.js"></script>
<script src="https://unpkg.com/react-dom@15.3.2/dist/react-dom.js"></script>
<script src="https://unpkg.com/antd@2.0.1/dist/antd.js"></script>
```

``` clojure
[:> window.antd.Row]
```

Gives this warning. Copy+paste this code into regular babel script inbrowser produces no warnings.

**Comment by Deraen** [comment]
Reagent doesn't use PropTypes so I doubt this was caused by us.

Without more information I can't do anything about this, and I can't test JS libs without existing example project.
