### ISSUE TITLE
Possible bug with reactions 'firing' unnecessarily in 0.6.0

### ISSUE THREAD

**Issue by yatesco** [reagent-project/reagent#277]
posted originally in [reagent google group](https://groups.google.com/d/msg/reagent-project/iSxt-KVou98/x9yl4T1OBQAJ)

My understanding is that a reaction is memoised and only executes the body the first time it is derefed since any atoms or reactions it deref's have changed.

Given this, and the following code:
```
(def active-stage-headers (ratom/reaction .....)
 
(defonce old-stage-header-ids (atom [])) ;; - a "normal" atom, not a reagent.ratom/atom
(def active-stage-header-ids
  (ratom/reaction
   (let [result (mapv (comp :id :patient) @active-stage-headers)]
     (if (= @old-stage-header-ids result)
       (js/console.log "recalculating stage-header-ids SAME!")
       (js/console.log "recalculating stage-header-ids DIFFERENT!"))
     (reset! old-stage-header-ids result)
     result)))
```

I would never expect to see more than one "recalculating stage-header-ids SAME!", however I am seeing that message appear in an endless loop (in Chrome).

I do see the expected behaviour in other reaction 'chains'.

Is this a bug or have I misunderstood - thanks.

**Comment by ducky427** [comment]
@yatesco, reagent atoms/reactions behave markedly different when inside a reagent component.

Have you tried the same using a reagent component?

**Comment by yatesco** [comment]
Thanks @ducky427, that's interesting - I didn't realise this. Yes, both reactions are used independently inside components.

However, I still don't see that what I am doing (derefing a reaction inside another reaction) should cause that reaction to be fired over and over?

**Comment by yatesco** [comment]
Can anybody at least confirm whether this is a bug or have I misunderstood something?

**Comment by atroche** [comment]
I just tried this out on master, and when I deref'd it just printed this out once:
`recalculating stage-header-ids DIFFERENT!`

So maybe it's been inadvertently fixed?

**Comment by Deraen** [comment]
Can't reproduce.
