### ISSUE TITLE
Keys in style map should be camel-cased

### ISSUE THREAD

**Issue by bsteuber** [reagent-project/reagent#279]
When providing e.g.
`{:style {:align-text :center}}`
I would expect reagent to convert this to alignText as it does with properties - but it doesn't so I need to camel-case myself here which feels very inconsistent.

**Comment by Frozenlock** [comment]
I must be missing something on this...
CSS is a hyphen-delimited syntax, why would you want to convert your `:style` into CamelCase?

**Comment by bsteuber** [comment]
Well react requires that, I guess since it uses js properties. So you will
get a react warning otherwise.

Frozenlock <notifications@github.com> schrieb am Mi., 14. Dez. 2016 21:37:

**Comment by Deraen** [comment]
Reagent does this already:

- https://github.com/reagent-project/reagent/blob/master/src/reagent/impl/template.cljs#L275
- https://github.com/reagent-project/reagent/blob/master/src/reagent/impl/template.cljs#L95
- https://github.com/reagent-project/reagent/blob/master/src/reagent/impl/template.cljs#L67
- https://github.com/reagent-project/reagent/blob/master/src/reagent/impl/template.cljs#L46

I added a new test to check this https://github.com/reagent-project/reagent/commit/4ea070d15a50c5fcee8dee526b79db9e6c8dd6aa

If you use custom React components, this won't work and that can't be fixed.
