### ISSUE TITLE
DOMException in interaction between semantic-ui and reagent

### ISSUE THREAD

**Issue by danceasarxx** [reagent-project/reagent#280]
reagent version `0.6.0`

I am currently using semantic-ui with reagent for a modal component.
```clojure
(defn component []
  (reagent/create-class {:component-did-mount #(.modal (js/$ "#app-node") "show")
                                      :reagent-render #([:div#app-node.modal.ui [:div.header "Modal Header"]])}))

(defn main-component []
  [:div.ui.container
   [component]])
```

I noticed anytime I closed the modal it raises this error

```
Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at removeChild (http://localhost:3000/out/react.inc.js:1273:14)
    at Object.processUpdates (http://localhost:3000/out/react.inc.js:1389:11)
    at Object.dangerouslyProcessChildrenUpdates [as processChildrenUpdates] (http://localhost:3000/out/react.inc.js:8335:27)
```

After setting a breakpoint on removeChild, it so happens that this exception gets thrown only when it's removing `#app-node`. Suggesting that semantic-ui somehow is causing some problems.

**Comment by danceasarxx** [comment]
I think I found the problem. Semantic ui was adding classes `transition.hidden` to the component and that's why reagent/react was confused. So I added it myself in the component.
```clojure
[:div#app-node.transition.hidden.modal.ui]
```

This is not in anyway reagent's fault.

**Comment by danceasarxx** [comment]
Turns out it does not actually change anything.

**Comment by danielcompton** [comment]
Can you provide a minimal example without Semantic UI and what looks like JQuery (`js/$`)?

**Comment by danceasarxx** [comment]
That's the problem, I have never experienced this problem beyond using this semantic-ui modal. In fact I find this difficult to reproduce sometimes(as I don't know when removeChild will be called). And the reason for jQuery is that semantic basically creates a jquery plugin for the modal. Hence this problem only ever exists because semantic UI does some work on this node(at least I think so)

**Comment by danielcompton** [comment]
If you've got anything else touching your DOM nodes apart form React, I'm pretty sure all bets are off. Have you looked at using doing the modal the way React Semantic-UI does it http://react.semantic-ui.com/modules/modal ?

**Comment by danceasarxx** [comment]
That's a lot of code to rewrite. Anyways I have decided against using semantic as I might need to do this in other places. Thanks anyways
