### ISSUE TITLE
as-element fails to trigger rerender

### ISSUE THREAD

**Issue by vans163** [reagent-project/reagent#285]
If you create a local atom and then create an as-element to swap! (with?) it, if the as-element was created from a function call rerender fails.

```clojure
(defonce state (r/atom {
        :toggle {} }))
 
(r/as-element
   (if (= (get (:toggle @state) (.-uuid record)) true)
        [:a {:onClick #(swap! state assoc-in [:toggle (.-uuid record)] false)} "Cancel"]
        [:a {:onClick #(swap! state assoc-in [:toggle (.-uuid record)] true)} "Rename"]))
```

Now as-element here gets created by a #() from Material-UI component.

To fix this behavior you can place (:toggle @state) at the top of the components render.

**Comment by Deraen** [comment]
Where is the result of `as-element` used? I think this requires more complete example.

**Comment by Deraen** [comment]
Closing this as I can reproduce this with current Reagent.
