### ISSUE TITLE
FEATURE: Easy way to access 'this' inside components

### ISSUE THREAD

**Issue by vans163** [reagent-project/reagent#286]
Currently there is no easy way to access this inside a component. This is often needed to accomplish working with javascript apis or libraries.

For example when working with a canvas it becomes really complex to do anything without having access to this, for example:

```clojurescript
[:div
  [:canvas {:onMouseMove #(draw %)}]
  [:button {:onClick #(save_image ?canvas?}]
  ;We cant get canvas from anywhere :(
]

; If we can do like
(defn save_image [canvas_js_object]
  (.getContext canvas_js_object "2d"))

(let [canvas (reagent/as-element [:canvas {:onMouseMove #(draw %) :ref this-macro}])]
  [:div
    canvas
    [:button {:onClick #(save_image (.-ref canvas)}]])
```

It becomes so much simpler.

**Comment by danielcompton** [comment]
Does `this-as` work for you? http://clojurescriptmadeeasy.com/blog/how-to-use-this-in-cljs.html

**Comment by vans163** [comment]
@danielcompton 
It does not because you cannot use (this-as this) in this way.  You cannot grab the this-as of the canvas element.  The only this-as you can grab is the react component, but there is no way now to grab the actual html element this.

**Comment by vans163** [comment]
I found the solution to this thanks to Frozenlock.

```clojure
[:canvas {:ref #(js/console.log (.getContext % "2d"))}]
```

Perhaps I should open a pull request to add this to the mainpage documentation for reagent, as this is a pretty essential function.

**Comment by Deraen** [comment]
https://github.com/reagent-project/reagent/blob/master/src/reagent/core.cljs#L119-L123

Ref callbacks are also fine.

**Comment by Deraen** [comment]
As far as I know, this works fine using either `:ref` callbacks (PR improving documentation welcome), or using `r/current-component`.
