### ISSUE TITLE
[:input {:type "number"}] is broken in 0.6.0

### ISSUE THREAD

**Issue by minikomi** [reagent-project/reagent#289]
Using a reagent/atom with an `[:input {:type "number"}]` has odd behavior in 0.6.0.

Seems to be working in 0.6.0-alpha.

Minimal example:

```clj
(ns inputtest.core
    (:require [reagent.core :as reagent :refer [atom]]))

(def value (atom 0))

(defn atom-input []
  [:input {:type "number"
           :value @value
           :step "any"
           :on-change #(reset! value (-> % .-target .-value))}])

;; -------------------------
;; Initialize app

(defn mount-root []
  (reagent/render [atom-input] (.getElementById js/document "app")))

(defn init! []
  (mount-root))
```

Trying to type a decimal point will reset the cursor to the start of the input, then pressing decimal again clears/resets the input.

**Comment by minikomi** [comment]
Cljsfiddle - which is running on 0.6.0-alpha - [does not exhibit this problem](http://escherize.com/cljsfiddle/#gist=94b0a61aeb5ae9afeb9f664162482a4a).

**Comment by minikomi** [comment]
Appears to be a react bug: facebook/react#8717

**Comment by Deraen** [comment]
0.6.1 has input related changes, did you try with that?

**Comment by minikomi** [comment]
> 0.6.1 has input related changes, did you try with that?

Still exhibits the same problem. Seems it was a [react problem](https://github.com/facebook/react/pull/7750) and was [fixed](https://github.com/facebook/react/issues/8717#issuecomment-274676621) in [15.4.2](https://github.com/facebook/react/blob/master/CHANGELOG.md#1542-january-6-2017) .

**Comment by Deraen** [comment]
You can test the fix by upgrading you React dependencies:

```
                 [cljsjs/react-dom "15.4.2-2"]
                 [cljsjs/react-dom-server "15.4.2-2"]
```

**Comment by minikomi** [comment]
Yep, confirmed upgrading react dependency fixes it.

**Comment by Deraen** [comment]
I pushed updated the version. I'm not yet sure if I want to create minor release with this fix or wait for other fixes.

**Comment by Deraen** [comment]
Reagent 0.6.2 has been released with upgraded React dependency.
