### ISSUE TITLE
ReactAddonsDOMDependencies.getReactDOM() is null with latest cljsjs/react-with-addons

### ISSUE THREAD

**Issue by koddo** [reagent-project/reagent#290]
Hello. I found bumping version of `cljsjs/react-with-addons` up breaks dependencies somewhere.
With this everything works, `project.clj`:
```
                 [reagent "0.6.1" :exclusions [cljsjs/react]]
                 [cljsjs/react-with-addons "15.4.1-0"]
```

And this in `views.cljs`:

```
[css-transition-group {:transitionName "example" :transitionEnterTimeout 500 :transitionLeaveTimeout 500}
    (if (<sub [:checkbox])
      [:p "hello"])]
```

I pushed it to github-pages: https://koddo.github.io/tmp-cljs-react-with-addons-issue/

But when I bump the version to the latest `15.4.2-2`: https://clojars.org/cljsjs/react-with-addons/versions/15.4.2-2

I get `TypeError: Cannot read property 'findDOMNode' of null` when I click the checkbox, it occurs here:

```
  transition: function (animationType, finishCallback, userSpecifiedDelay) {
    var node = ReactAddonsDOMDependencies.getReactDOM().findDOMNode(this);
```

Here is a repo where you can quickly check it: https://github.com/koddo/tmp-cljs-react-with-addons-issue

**Comment by kennyjwilli** [comment]
I have also ran into this problem and have also observed, as @koddo said, when using `15.4.1-0` you do not receive the error.

**Comment by Deraen** [comment]
```
$ lein deps :tree
 ...
 [cljsjs/react-with-addons "15.4.1-0"]
 [reagent "0.6.1" :exclusions [[cljsjs/react]]]
   [cljsjs/react-dom-server "15.4.0-0"]
   [cljsjs/react-dom "15.4.0-0"]
```

Using different versions of react-dom and react-with-addons is not going to work. If you update react-dom-with-addons, you also have to make sure that react-dom and react-dom-server dependencies are updated.

Add these to the project and everything should work:

```clj
[cljsjs/react-dom "15.4.1-0" :exclusions [cljsjs/react]]
[cljsjs/react-dom-server "15.4.1-0"]
```

**Comment by kennyjwilli** [comment]
Yup, @Deraen was correct - using matching versions of react-with-addons, react-dom, and react-dom-server fixes the issue. Thanks!

**Comment by koddo** [comment]
Sorry for a delay. Thank you, closing the issue.
