### ISSUE TITLE
:> and adapt-react-class has unexpected behavior with #js props

### ISSUE THREAD

**Issue by seantempesta** [reagent-project/reagent#291]
When rendering a reagent component and calling a `NativeComponent` using either `:>` or `adapt-react-class`, the javascript props become children of the NativeComponent.

Why do I want to explicitly pass in #js props?  Because I want the `NativeComponent` to directly manipulate a clj data structure.

**Minimimal Repo**
https://github.com/seantempesta/reagent-bug

```clojure
(defn home-page []
  [:div [:h2 "Welcome to reagent-bug"]

   ;; Works as Expected 
   [:> js/NativeComponent {:test ["props"]}]           
   [(reagent/adapt-react-class js/NativeComponent) {:test ["props"]}]

   ;; Unexpected Behavior (sets the props.children as #js {:test ["props"]})
   [:> js/NativeComponent #js {:test ["props"]}]           
   [(reagent/adapt-react-class js/NativeComponent) #js {:test ["props"]}]])
```

**Console Output**
<img width="423" alt="screen shot 2017-03-29 at 4 31 14 pm" src="https://cloud.githubusercontent.com/assets/726276/24445659/3c878d3c-149d-11e7-8ec7-102dc4ebc8b9.png">

**What did I expect to happen?**
That either Reagent would call `(clj->js #js {:test ["props"]})` (which wouldn't do anything) or check to see if the props are already an instance of js/Object and then directly use them.   

This is important because I have a large ReactNative ListView and the conversion is causing 1-2 second UI lockups once I get to 1,000 or so rows.  ReactNative now includes a `VirtualizedList` that allows you to pass in any data structure and include whatever functions are necessary to pull the data out.

https://facebook.github.io/react-native/releases/0.43/docs/virtualizedlist.html

**Comment by Deraen** [comment]
I doubtful if there is any way to solve this. In JS pretty much everything is `Object` so checking for that doesn't help in detecting if a parameter is JS properties map or a children. There are ways to check if `Object` is "Plain object", but I'm not sure if those work with Cljs data structures.

**Comment by seantempesta** [comment]
@Deraen:  Not sure I understand.  Isn't the method signature for calling a React component always 

```js
React.createElement(class, props, children)
```
https://facebook.github.io/react/docs/react-without-jsx.html

Is there any reason to not assume that interop with a React class would follow the same convention?

**Comment by Deraen** [comment]
`createElement` signature doesn't matter much, it is the Reagent convention that first element is the component, second is optionally props and rest are the children. (`:>` breaks this convention so that second is the component and third item maybe props...) It is completely reasonable in React to use components without props: `<NativeComponent><Children prop="1"/></NativeComponent>`, and I have done so in projects and probably have others. So we can't change this (without breaking existing code).

However, we could add another way to use native React components which doesn't convert the props. Or maybe some kind of marker Record or metadata for the props which turns the conversion off, hmm...

https://github.com/reagent-project/reagent/blob/master/src/reagent/impl/template.cljs#L274-L275

As a workaround, I think you could wrap your data in a Record for now to prevent it being converted:

```cljs
(defrecord Wrapper [data])

[:> js/NativeComponent
 {:data (->Wrapper {:clj [:data :structure]})
  :read-fn (fn [x]
             ;; take data property from the Record
             (:data x))}]
```

**Comment by seantempesta** [comment]
I respectfully disagree, the `createElement` signature is what this interop code is used for (interacting with non-reagent components that always have the same signature).  When the user specifies `[:>` or uses `adapt-react-class` that's exactly what they are expecting.  

```jsx
<NativeComponent><Children prop="1"/></NativeComponent>
```
converts to (roughly)
```js
React.createElement(NativeComponent, null, React.createElement(Children, {prop: 1}, null))
```
The same positions are maintained (w/r/t Class, Props, and Children).  So, if you wanted to call a native component you'd just do this:

```clojure
[:> NativeComponent nil [:> Children {:prop 1} nil]]
```
Or something to that effect.  The point being, that the second position is *always* props.  If it's a clojure map then you should `(clj->js` convert them.  But if it's anything else, it should just be passed through as is.  

Sean

**Comment by Deraen** [comment]
`:>` and `adapt-create-class` check if the first argument is `map?` or `nil?` and uses it as props in that case, and automatically converts the props from Clojure to JS.

Looking at the problem, I think there in fact is already alternative function which should work here: [create-element](https://github.com/reagent-project/reagent/blob/master/src/reagent/core.cljs#L19)

```clj
(defn home-page []
  [:div [:h2 "Welcome to reagent-bug"]

   ;; Works as Expected 
   [:> js/NativeComponent {:test ["props"]}]
   (reagent/create-element js/NativeComponent {:test ["props"]})

   ;; Unexpected Behavior (sets the props.children as #js {:test ["props"]})
   (reagent/create-element js/NativeComponent #js {:test ["props"]})
   ])
```

Which I think makes sense. `adapt-react-class` and `:>` are high level helpers which automatically convert props to JS and make props optional, while `reagent/create-element` directly maps to `React.createElement`.

@seantempesta Could you check if this solves your use case?

**Comment by Deraen** [comment]
Closing as I think `:>` and `adapt-create-class` work as supposed. The high level helpers don't allow all use cases, but calling `create-element` directly should work.
