### ISSUE TITLE
React 15.5.0

### ISSUE THREAD

**Issue by Deraen** [reagent-project/reagent#292]
React will be deprecating `createClass`: https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html#migrating-from-react.createclass

This will cause warning with Reagent:

```
react.inc.js:3287 Warning: ndiv: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.
```

Solution will be either to drop the use of `createClass`. Perhaps we can create functions which correspond with code generated from ES6 classes? Though this will mean some breakage as I think mixins are not supported when using Classes.

Another option is to use the mentioned npm package. This will probably require use of module processing.

**Comment by seantempesta** [comment]
Huh.  Can the clojurescript compiler just consume javascript classes?  I noticed there was a `:language-in` parameter, but I haven't tried using it.

https://github.com/clojure/clojurescript/wiki/Compiler-Options#language-in-and-language-out

**Comment by ducky427** [comment]
If we package `create-react-class` npm module, I think it would require the least amount of changes.

**Comment by Deraen** [comment]
@ducky427 Any reason for closing #295?

Also, I implemented the mentioned solution using `create-react-class`: https://github.com/reagent-project/reagent/pull/298

**Comment by ducky427** [comment]
I think my PR is very simplistic and on deeper thinking it is not finished. I'd say :+1: on `create-react-class`.

I am not confident that moving to React ES6 Component won't break any existing code as `getInitialProps` logic should now move to the class constructor.

**Comment by Deraen** [comment]
Okay, good to know. Sounds like create-react-class is best way to solve this for now.

**Comment by ducky427** [comment]
Definitely. 

imho, we should, however, start thinking about deprecating its use as well. 

Additionally, when React 16 fiber comes out, it will make Reagent's rAF stuff redundant.

**Comment by Deraen** [comment]
Yeah,

I think I'll release 0.6.2 with React 15.4.2, 0.7 with React 15.5 and React 16 version should probably be 1.0. I'm also thinking of testing some React loading related changes which would help with using Reagent with `:npm-deps`, these could be included in 0.7.

React 16 will probably introduce some changes in Cljsjs, which should prevent problems with mismatched Cljsjs React dependencies: https://github.com/cljsjs/packages/issues/1170

**Comment by ducky427** [comment]
That sounds great!

**Comment by kommen** [comment]
@Deraen Just as a heads up, I have a fork which uses :npm-deps (and ditches cljsjs/react) and it works fine in a demo project. If it works for our production code as well I'm happy to provide a PR to test and discuss for you folks.

**Comment by Deraen** [comment]
@kommen Sure, I can have a look.

Cljsjs will continue to be the recommended way to include React, but by idea is to make sure `:npm-deps` can be used without exclusions and creating `cljsjs.react` etc. files just to satisfy `cljsjs.react` requires. I think this can be achieved by dropping requires to `cljsjs.react` etc. and improving [`reagent.impl.util` code]( https://github.com/reagent-project/reagent/blob/master/src/reagent/impl/util.cljs#L8) to guide user either add `cljsjs.react` require to the project before `reagent.core` require or to use `npm-deps`, and necessary requires.
