### ISSUE TITLE
Error when including reagent in a nodejs project

### ISSUE THREAD

**Issue by chr15m** [reagent-project/reagent#296]
My goal is to run reagent's `render-to-string` on the server side under node.

I'm using [figwheel-node-template](https://github.com/malyn/figwheel-node-template) to bootstrap the project:

    $ lein new figwheel-node isomorph

Then edit `isomorph/src/isomorph/core.cljs` so that it looks like this:

```clojure
(ns isomorph.core
  (:require [cljs.nodejs :as nodejs]
            [reagent.dom.server :refer [render-to-string]]))

(nodejs/enable-util-print!)

(defn some-component []
  [:div
   [:h3 "I am a component!"]
   [:p.someclass 
    "I have " [:strong "bold"]
    [:span {:style {:color "red"}} " and red"]
    " text."]])

(defn -main []
  (print (render-to-string [some-component])))

(set! *main-cli-fn* -main)
```

Then add `[reagent "0.6.1"]` to `:dependencies`.

Then build:

```
$ lein cljsbuild once prod
Compiling ClojureScript...
Compiling "server.js" from ["src"]...
Successfully compiled "server.js" in 13.385 seconds.
```

Then run the compiled server.js file:

```
$ node server.js 
module.js:472
    throw err;
    ^

Error: Cannot find module 'react'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at /home/chrism/dev/isomorph/server.js:37:72
    at Object.<anonymous> (/home/chrism/dev/isomorph/server.js:37:285)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
```

In [this chat session](https://clojurians-log.clojureverse.org/clojurescript/2016-02-11.html#inst-2016-02-11T00:08:23.002201Z) David Nolen advises @anmonteiro:

> dnolen 00:29:33 
> loading React DOM will blow up in Node.js
> and lead to your cryptic error

Could this be what is going on here?

Is there a better way for me to get reagent to render my component running inside nodejs?

**Comment by chr15m** [comment]
After some fiddling I got this working by:

 * Using `:exclusions [cljsjs/react]` in `project.clj` dependencies.
 * Creating `resources/include.js` with `var ReactDOMServer = require('react-dom/server');`
 * Adding `:preamble ["include.js"]` to `project.clj` builds configuration.
 * Adding `react.cljs` with `(ns cljsjs.react)`
 * Including `react` and `react-dom` via `packages.json`

You can see a working demo of these changes here: https://github.com/chr15m/reagent-node-render-demo

**Comment by arichiardi** [comment]
@chr15m I was looking for this! Thanks a lot!

I was even wondering if it is worth adding a `+reagent` to `fighweel-node-template` with your findings.

**Comment by ElChache** [comment]
@chr15m It worked like a charm with prod!

But lein-figwheel didn't work. It returns error saying that it didn't find React. What it worked for me was to create a wrapper file injecting react and react-dom
` global.React = require('react');
 global.ReactDOMServer = require('react-dom/server');
 require('./target/renderer_dev/renderer.js')`

**Comment by chr15m** [comment]
@ElChache ok cool maybe something changed when packages were upgraded? Thanks for the tip!

**Comment by ElChache** [comment]
@chr15m @arichiardi Actually I just created a working demo on [](https://github.com/ElChache/universal-reframe), and now I didn't even need those "polyfills", everything just worked, as long as the Reagent version included is the same as the reagent version that re-frame requires. Otherwise gives an error. Subscriptions and sync-events work out of the box. And it even works well with figwheel and a REPL!

**Comment by arichiardi** [comment]
The are changes coming in Cljs which probably will improve on how to import `reagent/server`

**Comment by Deraen** [comment]
Indeed. It looks like in the next Cljs release `:require` will work for all module types: Cljsjs packages style foreign libs, Node modules with Closure module processing and Node `require` when targetting Node.

**Comment by NeCkEr** [comment]
Any help/suggestions to get reagent 0.7.0 running on `nodejs`?

always getting the following error :
`ReferenceError: React is not defined`

**Comment by Deraen** [comment]
I just tested Reagent 0.8.0-alpha2 with https://github.com/malyn/figwheel-node-template and it is possible to get working quite easily.

1. add reagent dependency
2. npm install
3. npm install react react-dom
4. call e.g. `reagent.dom.server/render-to-string`

One problem with 0.8 is currently that it doesn't work without npm React, e.g. with only foreign library react, that problem is being tracked on separate issue: https://github.com/reagent-project/reagent/issues/310
