### ISSUE TITLE
how to use component defined by js, like cljsjs/antd?

### ISSUE THREAD

**Issue by charmer1989** [reagent-project/reagent#299]
I create a reagent template project, then I want to use a react UI library, like antd (https://ant.design/docs/react/introduce), I think cljsjs/antd can be used, but doesn't success.

I change the function current-page like that: 
```
(defn current-page []
  [js/antd.Button.])
```
but doesn't work.

other side, the code like that:
```
(defn current-page []
  [:div (js/antd.message.success. "success")])
```
work success!

I know that is a function call, not a compontent.
So, how to use compontent like "Button"?

**Comment by danielcompton** [comment]
Github issues for Reagent are for bug reports and feature requests. Support requests and usage questions should go to the [Clojure Slack channel](http://clojurians.net/), the [ClojureScript mailing list](https://groups.google.com/forum/#!forum/clojurescript), or the [Reagent mailing list](https://groups.google.com/forum/#!forum/reagent-project).

**Comment by charmer1989** [comment]
Ok, Thanks

**Comment by charmer1989** [comment]
Through your tips, I find something from (http://blob.tomerweller.com/reagent-import-react-components-from-npm), It has given me great inspiration. Thanks a lot
