### ISSUE TITLE
Include a copy of the license in repository root

### ISSUE THREAD

**Issue by yarwelp** [reagent-project/reagent#300]
README states that this project is released under the terms of the MIT license. Including a copy of the license in your repository lets GitHub tag the repo with the license. Furthermore, since the MIT license requires people who want to use your code include the copyright notice, including a copy of the license with the correct copyright notice makes it easier for others to comply with the terms of the license.

**Comment by Deraen** [comment]
https://github.com/reagent-project/reagent/pull/243

**Comment by Deraen** [comment]
Closing as duplicate.
