### ISSUE TITLE
0.8 release

### ISSUE THREAD

**Issue by Deraen** [reagent-project/reagent#307]
- [x] Run tests both with Cljsjs and node modules, currently only run with one? and not sure which
- [x] Provide upgrade guide which lists different environments: https://github.com/reagent-project/reagent/blob/master/docs/0.8-upgrade.md
- [ ] Update README.md to remove mentions of `:exclusions` and provide new documentation
on how to use
    - React addons (that is, use separate Cljsjs or npm packages, react-with-addons in deprecated)
    - additional React packages
    - ...
- [x] Validate how additional React packages work with this change, both Cljsjs and npm
- [ ] wait for Re-natal project (or someone) to validate how this will work with React-native: https://github.com/drapanjanas/re-natal/issues/128
- [x] Validate how this works on projects that target both Node and browser, and want to use foreign-libs on browser

**Comment by iku000888** [comment]
Hi @Deraen 

Thanks for the work on reagent!

Just wanted to throw my 2 cents that 0.8.0-alpha1 does not work with [devcards](https://github.com/bhauman/devcards) (ver 0.2.3) as it directly requires react as cljsjs.react.

I am speculating that it should be fine as long as devcards updates to require cljsjs.react the same way as the latest reagent does, but not sure at the moment.

**Comment by Deraen** [comment]
I have opened PRs on other projects so make themworks with global-exports and module-processing also:

bhauman/devcards#127
tonsky/rum#148
r0man/sablono#175
omcljs/om#887

We have some ideas still that might make the change easier and "less-breaking".

**Comment by Frozenlock** [comment]
I tried to upgrade a project to 0.8.0-alpha1 and use a react library with `:npm-deps`.
It works for development (figwheel), but fails when trying to use advanced compilation.

If it can help : 
[The errors in the browser](https://facebook.github.io/react/docs/error-decoder.html?invariant=33)

An example of the numerous warnings when compiling:
```
Aug 30, 2017 4:16:11 AM com.google.javascript.jscomp.LoggerErrorManager println
WARNING: <<<path-to-my-project>>>/target/uberjar/node_modules/react/lib/ReactChildren.js:41: WARNING - dangerous use of the global this object
  this.result = mapResult;
  ^^^^
```

**Comment by Deraen** [comment]
@Frozenlock Which React and Cljs versions did you try?

**Comment by Frozenlock** [comment]
```clj
[org.clojure/clojurescript "1.9.908"]

:npm-deps 
{:react "15.6.1"
 :react-dom "15.6.1"
 :create-react-class "15.6.0"
 :react-sortable-hoc "0.6.7"}
```

**Comment by Deraen** [comment]
@Frozenlock Can you try without react-sortable-hoc? It is possibile that ReactChildren file is only included in build when using that.

**Comment by Frozenlock** [comment]
Same thing :-(
And it's not only ReactChildren, there are hundreds of warnings.

The only way I can get the advanced compilation to work again is to delete the `node_modules` directory.

**Comment by Frozenlock** [comment]
New problem in 8.0 alpha2 :

When updating projects from clojure 1.8 to 1.9, advanced compilation doesn't work anymore.
It appears to be related to create-react-class.

Can be tested using the reagent-template to create a new project and then updating clojure.

**Comment by Deraen** [comment]
@Frozenlock 
`lein new reagent foo`
update project.clj to use 0.8.0-alpha2
`lein uberjar`
`java -jar target/foo.jar`

works for me.

**Comment by Frozenlock** [comment]
@Deraen On which java version are you?
I tried downgrading on java 8 and it works, but java 9 is a problem.

**Comment by Deraen** [comment]
I haven't tested with Java 9. Strange that Java version would affect this. Do you have any errors or information you could share?

**Comment by Frozenlock** [comment]
Like I said, it seems to be messing with the advanced compilation process.
The uberjar will complete as expected, but when opening the webpage it will show the default message "ClojureScript has not been compiled! please run lein figwheel in order to start the compiler".

In the console : 

```js
Uncaught TypeError: Cannot read property 'a' of undefined
    at hk (component.cljs:272)
    at kk (component.cljs:326)
    at Pk (component.cljs:332)
    at Mk (template.cljs:421)
    at dom.cljs:43
    at Uk (dom.cljs:20)
    at dom.cljs:44
    at dom.cljs:39
    at dom.cljs:39
```
Clicking on the error link (component.cljs at line 272) brings me to `create-react-class`.

![image](https://user-images.githubusercontent.com/1152041/35875990-faed1d80-0b3e-11e8-8275-da97a8c3dcfd.png)

**Comment by ackerleytng** [comment]
I'm having this problem too, and I'm on java 9

**Comment by Deraen** [comment]
Could you try with latest ClojureScript from git?

https://github.com/clojure/clojurescript/commit/8670cc40cf09f90f1d36cb4bf0a2c68713fb1d68

Cljs had bug in Java 9 which caused the externs to not be abled. This is not Reagent specific, and will affect any foreign libs under Java 9.

**Comment by ackerleytng** [comment]
Sorry I'm new to clojure. How should I edit `project.clj` to use that particular commit for clojurescript?

**Comment by ackerleytng** [comment]
It works fine with ClojureScript 1.10.238. Thanks!

**Comment by Deraen** [comment]
Getting close(r) to the release. I'll keep track of rest of issues using milestones https://github.com/reagent-project/reagent/milestone/2
