### ISSUE TITLE
Library name must be specified as a symbol in :require / :require-macros

### ISSUE THREAD

**Issue by borkdude** [reagent-project/reagent#309]
With the following deps:

```
[org.clojure/clojurescript "1.9.671"]
[reagent "0.8.0-alpha1"]
[cljsjs/react-with-addons "15.6.1-0"]
[cljsjs/react-dom-server "15.6.1-1"]
[cljsjs/react-dom "15.6.1-1"]
[cljsjs/create-react-class "15.6.0-2"]
```    
I get the following error message:

> Library name must be specified as a symbol in :require / :require-macros; offending spec: ["react-dom/server" :as dom-server] at line 1 jar:file:/Users/Borkdude/.m2/repository/reagent/reagent/0.8.0-alpha1/reagent-0.8.0-alpha1.jar!/reagent/dom/server.cljs at line 1, column 1 in file jar:file:/Users/Borkdude/.m2/repository/reagent/reagent/0.8.0-alpha1/reagent-0.8.0-alpha1.jar!/reagent/dom/server.cljs

**Comment by Deraen** [comment]
Reagent 0.8.0 requires ClojureScript 1.9.854

**Comment by borkdude** [comment]
Thanks!

**Comment by borkdude** [comment]
I upgraded to ClojureScript 1.9.854. I get the following error now:

> No such namespace: react, could not locate react.cljs, react.cljc, or JavaScript source providing "react" in file /Users/Borkdude/.boot/cache/tmp/Users/Borkdude/dre/DocSearch/app/3yq/10roi5/public/js/app.out/reagent/impl/component.cljs

**Comment by Deraen** [comment]
React-with-addons doesn't work with Reagent 0.8. It has been deprecated. As you can see the version number is different, `-0` instead of `-1`. Only `-1` React packages use new `:global-exports` and support Reagent 0.8.

**Comment by Deraen** [comment]
I added mention about this to the changelog:

> React-with-addons bundle [has been deprecated](https://facebook.github.io/react/docs/addons.html) and Cljsjs no longer provides new versions
of that package. The latest React-with-addons version won't work with Reagent 0.8.
For animation utils use [react-transition-group](https://github.com/cljsjs/packages/tree/master/react-transition-group) package instead (TODO: Update to use `:global-exports`). [React-dom/test-utils](https://facebook.github.io/react/docs/test-utils.html) and [react-addons-perf](https://facebook.github.io/react/docs/perf.html) are not currently packaged as browserified files, so their use would require Webpack, or they might work with Closure module processing (TODO: Provide example).

**Comment by borkdude** [comment]
Thanks, this helped me a lot.
