### ISSUE TITLE
Add helper functions for Portals

### ISSUE THREAD

**Issue by Deraen** [reagent-project/reagent#317]
https://reactjs.org/docs/portals.html

Probably already usable by calling directly to React.createPortal, but we should wrap this function.

**Comment by Deraen** [comment]
This should already work:

`(react/createPortal (r/as-element [:div "foo"]) (.. js/document (getElementById "portal-el"))`

**Comment by Osvalds** [comment]
@Deraen 's code snippet is almost there. To make this work I needed to use `react-dom` not the regular `react` namespace.

**Comment by Deraen** [comment]
https://github.com/reagent-project/reagent/blob/master/doc/ReactFeatures.md#portals

I think the docs are enough for now.
