### ISSUE TITLE
Problems with Shadow Dom (SLOT attribute, React 16.0)

### ISSUE THREAD

**Issue by WorldsEndless** [reagent-project/reagent#320]
A theme provided by my university makes use of the ShadowDOM and web components. In particular, it requires 

    <span slot="site-title">

React itself started supporting `slot` attributes after version 16.0 (https://github.com/facebook/react/pull/8061). Unfortunately, Reagent is a couple versions behind on React, and just trying 

                 [reagent "0.7.0" :exclusions [cljsjs/react]]
                 [cljsjs/react "16.0.0-0"]

Didn't work for me due to various error's you are all probably more aware of than I am. Anyway, since the prescribed theme uses web components, and Shadow DOM support seems troubled at least until React 16.0, I can't seem to find a way to implement things like this in the current version of Reagent.

**Comment by Deraen** [comment]
You need to update both `cljsjs/react` and `cljsjs/react-dom`, and to use 0.8.0-alpha2.

**Comment by WorldsEndless** [comment]
Thanks for the suggestions. Changing my project.clj as follows does not work; rendering fails. Am I getting something wrong in the syntax?

                 [reagent "0.8.0-alpha2" :exclusions [cljsjs/react cljsjs/react-dom]]
                 [cljsjs/react "16.0.0-0"]
                 [cljsjs/react-dom "15.6.2-0"]

**Comment by Deraen** [comment]
You need version 16.0.0-0 of react-dom.

**Comment by WorldsEndless** [comment]
Project.clj snippet:

                 [cljsjs/react "16.0.0-0"]
                 [cljsjs/react-dom "16.0.0-0"]
                 [reagent "0.8.0-alpha2" :exclusions [cljsjs/react cljsjs/react-dom]]

Browser error (still nothing rendering):
`ReferenceError: react_dom is not defined`

I'm not sure whether order matters in project.clj dependencies, so I also tried having the reagent declaration first. Either way it had the same result.

**Comment by Deraen** [comment]
Order shouldn't matter here. Important part is that the react deps are defined on your project, direct deps always have precedence over transitive deps. You don't need those exclusions either (though they don't do any harm either).

Did you try `lein clean` etc? This should definitely work, Reagent is tested against React 16.

**Comment by Deraen** [comment]
I recommend using the same deps as Reagent uses for tests:

```
[cljsjs/react "16.1.0-0"]
[cljsjs/react-dom "16.1.0-0"]
[cljsjs/react-dom-server "16.1.0-0"]
```

(and `:exclusions` is unncessary, you can validate the versions with `lein deps :tree` / `boot show -d`)

I'll close this now, but if you still have problems I recommend [Clojurians slack](http://clojurians.net/) or https://clojureverse.org/ for questions.

**Comment by WorldsEndless** [comment]
Thanks, @Deraen . That worked.
