### ISSUE TITLE
Support for react context

### ISSUE THREAD

**Issue by dspiteself** [reagent-project/reagent#330]
We are evaluating react wrappers and have a requirement of being able to use react context which in turn requires setting contextTypes on the component. Is there any plan to support this in the future?

**Comment by Deraen** [comment]
Context is already supported, doesn't require anything in reagent, check this commit for example: https://github.com/reagent-project/reagent/commit/a8ec0d219bbd507f51a4d9276c4a1dcc020245af

This PR has some related discussion https://github.com/reagent-project/reagent/pull/178

**Comment by mike-thompson-day8** [comment]
There's now an official API for context:
https://medium.com/@baphemot/whats-new-in-react-16-3-d2c9b7b6193b

**Comment by Deraen** [comment]
The new Context API is quite easily usable with Reagent: https://github.com/reagent-project/reagent/pull/372/files

https://github.com/Lokeh/reagent-context also wraps the calls in nice Cljs api.

**Comment by Deraen** [comment]
https://github.com/reagent-project/reagent/blob/master/doc/ReactFeatures.md#context

I've used this in my projects and haven't encountered any problems.
