### ISSUE TITLE
Call to clojure.core/refer-clojure did not conform to spec

### ISSUE THREAD

**Issue by irfn** [reagent-project/reagent#331]
I am seeing this on both of `1.9.0-RC2` and `1.9.0`  (java9)
I did a `lein new reagent`and updated the clojure dependency.

```
#error {
 :cause Call to clojure.core/refer-clojure did not conform to spec:
In: [2 1] val: :as fails at: [:args :exclude :op :quoted-spec :spec] predicate: #{:exclude}
In: [2 1] val: :as fails at: [:args :only :op :quoted-spec :spec] predicate: #{:only}
In: [2 1] val: :as fails at: [:args :rename :op :quoted-spec :spec] predicate: #{:rename}
In: [2] val: (quote :as) fails at: [:args :exclude :op :spec] predicate: #{:exclude}
In: [2] val: (quote :as) fails at: [:args :only :op :spec] predicate: #{:only}
In: [2] val: (quote :as) fails at: [:args :rename :op :spec] predicate: #{:rename}

 :data #:clojure.spec.alpha{:problems ({:path [:args :exclude :op :spec], :pred #{:exclude}, :val (quote :as), :via [], :in [2]} {:path [:args :exclude :op :quoted-spec :spec], :pred #{:exclude}, :val :as, :via [], :in [2 1]} {:path [:args :only :op :spec], :pred #{:only}, :val (quote :as), :via [], :in [2]} {:path [:args :only :op :quoted-spec :spec], :pred #{:only}, :val :as, :via [], :in [2 1]} {:path [:args :rename :op :spec], :pred #{:rename}, :val (quote :as), :via [], :in [2]} {:path [:args :rename :op :quoted-spec :spec], :pred #{:rename}, :val :as, :via [], :in [2 1]}), :spec #object[clojure.spec.alpha$regex_spec_impl$reify__2436 0x4dfec8eb clojure.spec.alpha$regex_spec_impl$reify__2436@4dfec8eb], :value ((quote :exclude) (quote [reduce into merge map take partition partition-by]) (quote :as) (quote core)), :args ((quote :exclude) (quote [reduce into merge map take partition partition-by]) (quote :as) (quote core))}
 :via
 [{:type clojure.lang.Compiler$CompilerException
   :message clojure.lang.ExceptionInfo: Call to clojure.core/refer-clojure did not conform to spec:
In: [2 1] val: :as fails at: [:args :exclude :op :quoted-spec :spec] predicate: #{:exclude}
In: [2 1] val: :as fails at: [:args :only :op :quoted-spec :spec] predicate: #{:only}
In: [2 1] val: :as fails at: [:args :rename :op :quoted-spec :spec] predicate: #{:rename}
In: [2] val: (quote :as) fails at: [:args :exclude :op :spec] predicate: #{:exclude}
In: [2] val: (quote :as) fails at: [:args :only :op :spec] predicate: #{:only}
In: [2] val: (quote :as) fails at: [:args :rename :op :spec] predicate: #{:rename}
```

However running 
`lein new figwheel game-of-life -- --reagent` works just fine.

Issue may be same as [bhauman/lein-figwheel/issues/540](https://github.com/bhauman/lein-figwheel/issues/540)

**Comment by Deraen** [comment]
Which ClojureScript version did you try? Try updating that. Unfortunately the error doesn't show which file causes the error, but I think it is not from Reagent.

**Comment by sandhu** [comment]
I've run into this a few times and it's typically caused by a version of core.async < `0.3.442` pulled in as a transitive dependency.

**Comment by irfn** [comment]
@Deraen you may be right but this is impacting an important step mentioned in README

`lein new reagent`

Either we remove that and ask ppl to use `lein new figwheel game-of-life -- --reagent` or we atleast investigate further. @sandhu is right about this, need to find which dependency is pulling the wrong core.async and update/patch that dependency. i understand that this may involve raising issues on a dependent project.

**Comment by Deraen** [comment]
I created new project with `lein new reagent foooo`, updated Clojure to 1.9 and ran figwheel. Works for me.

As mentioned in Figwheel issue, this can be caused by plugins declared on users Lein profile (`~/.lein/profiles.clj`). 

@irfn I can see if I can find what is causing this if you provide the profiles file and output of `lein deps :tree`.

**Comment by irfn** [comment]
strange i can now run this without any issues. also i never had any user profile in `.lein` folder.
since this is working now plz close this issue.

**Comment by Deraen** [comment]
Reagent template was updated with latest dependencies, it is possible some of those fixed a conflict with something.
