### ISSUE TITLE
Add framework benchmark to krausest/js-framework-benchmark

### ISSUE THREAD

**Issue by kaste** [reagent-project/reagent#332]
Hi!

I would like to see you on the relative popular [krausest/js-framework-benchmark](https://github.com/krausest/js-framework-benchmark). [Results page](https://rawgit.com/krausest/js-framework-benchmark/master/webdriver-ts-results/table.html)

An implementation just takes maybe 15 minutes to an hour for developers experienced with the framework. And it's not JS only, there is an implementation for `elm` as well, and it's fast BTW. 

It's not a 'classic' benchmark, they have a rule: You have to write idiomatic, readable and reasonable code, not a hack to be the fastest. So in that regard, it's a bit like a TodoApp competition, you get a sense of how a framework looks and feels.

P.S. I personally would like to see the TTI times, and memory cost.

**Comment by Deraen** [comment]
Done, waiting for PR to be merged: https://github.com/krausest/js-framework-benchmark/pull/343

Sneak peek of results:
![image](https://user-images.githubusercontent.com/648087/34182237-1e685d34-e51e-11e7-9243-a04af450613a.png)

**Comment by kaste** [comment]
Hej cool! 

Hope it wasn't too time-consuming. 

I don't want to discuss the numbers here, ... but if you look at **select row** 
![image](https://user-images.githubusercontent.com/8558/34198065-487b7494-e569-11e7-88cf-cedaa823061b.png) 

Roughly 19ms is not within 'a frame' and a bit unusual. You also have a pretty fast computer here 😄
