### ISSUE TITLE
Lists for class attribute results in wrong HTML

### ISSUE THREAD

**Issue by MrOerni** [reagent-project/reagent#337]
```clojure
[:circle.planet
       {:class ["fizz" "buzz" "test"]
        ; other stuff
]
```

Results in:

```html
<circle class="planet fizz,buzz,test">
```
Which isn't right.

The README states:
> The :class attribute can accept either a collection or a string.
>
> `[:div {:class ["a-class" (when active? "active") "b-class"]}]`

**Comment by Deraen** [comment]
@MrOerni Which Reagent version you tested this with?

**Comment by MrOerni** [comment]
@Deraen `[reagent "0.7.0"]`

**Comment by Deraen** [comment]
@MrOerni That feature is only available in `0.8.0-alpha2`. Sorry about the README, I hadn't noticed it already mentioned feature in dev version.

**Comment by WorldsEndless** [comment]
Ah! I've been tripping over that feature, too. I'm glad it wasn't 
just me.

**Comment by Deraen** [comment]
https://github.com/reagent-project/reagent/commit/035ba9cf29bc89477603d0fa64a1108453221b03
