### ISSUE TITLE
Server rendering in 0.8.0-alpha2 is broken

### ISSUE THREAD

**Issue by Lokeh** [reagent-project/reagent#338]
1. Create a new figwheel-node project: `lein new fighweel-node example`

2. Add dependency to `project.clj`: `[reagent "0.8.0-alpha2"]`

3. Load up a Node.js REPL- in one terminal: `lein figwheel` and in another terminal: `node target/js/compiled/example.js`

4. Try to use Reagent server rendering:
```
user.cljs> (require 'reagent.dom.server)
nil
cljs.user> (reagent.dom.server/render-to-string [:div "hello"])
```

Expected output:
```
"<div data-reactroot=\"\" data-reactid=\"1\" data-react-checksum=\"-857140882\">hello</div>"
```

Actual output:
```
#object[TypeError TypeError: Cannot read property 'renderToString' of undefined]
```

**Comment by Deraen** [comment]
With Node at least, this is probably caused by https://github.com/reagent-project/reagent/issues/310
You would try installing React, ReactDOM and create-react-class from npm to use those, which should work, or wait for the next Cljs release.

**Comment by Deraen** [comment]
Works for me, with one additional step:

Update ClojureScript to 1.10.238.

```
ClojureScript 1.10.238
dev:cljs.user=> (require 'reagent.dom.server)
nil
dev:cljs.user=> (reagent.dom.server/render-to-string [:div "hello"])
"<div data-reactroot=\"\" data-reactid=\"1\" data-react-checksum=\"-857140882\">hello</div>"
```
