### ISSUE TITLE
A full worked example using `:npm-deps`

### ISSUE THREAD

**Issue by royalaid** [reagent-project/reagent#341]
In messing around with `:npm-deps` I have came across the [instructions from the 0.8 upgrade](https://github.com/reagent-project/reagent/blob/master/docs/0.8-upgrade.md) which included the option to use `:npm-deps`. I tired to add `:npm-deps` to the [reagent template](https://github.com/reagent-project/reagent-template) but I had no such luck, instead spouting numerous unhelpful error messages. I think as 0.8 comes closer to release a worked example would be a great benefit as I can find examples using `left-pad` all over but no serious projects that work as you would expect or so show the use of interop.

**Comment by Deraen** [comment]
Could you paste some of those error message here? They might be helpful to me.

`:npm-deps` support is experimental in Cljs compiler still and it's not very useful for serious stuff, but requirement for improvement is that libraries support it, so I think we'll see much more examples after next Cljs and Reagent releases.

**Comment by royalaid** [comment]
Of course!
`goog.require could not find: module$Users$markaiken$Documents$git$clojure$chartjs$node_modules$react$lib$ReactPropTypeLocationNames`
`Error: goog.require could not find: module$Users$markaiken$Documents$git$clojure$chartjs$node_modules$react$lib$ReactPropTypeLocationNames`
`ReferenceError: module$Users$markaiken$Documents$git$clojure$npmmm$node_modules$react$lib$checkReactTypeSpec is not defined[Learn More]`
etc... see the image below.
![image](https://user-images.githubusercontent.com/2439803/36052728-ae2b4190-0da3-11e8-9c22-9a43387ab24a.png)

I have pushed an example repo to (suss out if I am making any mistakes) as well [here](https://github.com/royalaid/npm-deps-reagent-borked)

**Comment by mengu** [comment]
hi folks

it's the same for me as well. i added :npm-deps {:react-router "4.2.0" :react-router-dom "4.2.2"} and ran lein figwheel. i see it successfully installs those node modules and creates a node_modules directory. it also compiles most of them but seems something is wrong when i (require 'react-router-dom) in REPL:

```
goog.require could not find: module$Users$mengu$projects$rails$fortune$app$assets$javascripts$tendo$tendo$node_modules$react_router_dom$es$index
```

**Comment by Deraen** [comment]
This is an advanced feature and I'm only going to say React/React-dom/create-react-class work with Reagent. With all other packages you are on your own, and the errors should be reported in Cljs issue tracker, not here. (Testing this with Cljs 1.9 is not very useful, as soon to be released 1.10 will contain loads of fixes for this.)

**Comment by mengu** [comment]
hi @Deraen, sorry about bloating here. it's a cljs issue indeed.

**Comment by royalaid** [comment]
@Deraen Since there isn't really a fix should this issue be closed and then when `:npm-deps` is more production ready this can be revisited?

**Comment by Deraen** [comment]
CI is running Reagent test suite using Node module so I'm quite confident Reagent itself works using Node modules.

Would be probably good to understand what causes this, but based on logs here, it isn't anything in Reagent, but might be caused by ChartJS deps affecting installed node packages. Cljs issue tracker would be best place for these issue. As part of Cljs 1.10 release (or later...), some new ClojureScript docs might be written to document how to report issues with Node packages.

Anyway, this can probably be closed here.
