### ISSUE TITLE
Updating app-data Ratom succeeds, but page rerenders with original data

### ISSUE THREAD

**Issue by jamieorc** [reagent-project/reagent#35]
This is a question.

Wondering what I'm doing wrong here.

* The setup: data is a tree of n-depth. Components can have a list of children that are also components. My sample data has 4 levels.
* Each item's data is displayed as text of a few attributes
* Clicking a row enables edit mode with input fields for each attribute

As text is typed into a field (:name only right now), app-data is updated using update-raw-product. I've verified that items are updated properly in app-data, so the state is changing.

However, when rerendering, the original data is displayed. I've tried a couple of approaches, the current probably being the simplest, but can't see what I'm doing wrong. 

Heres a gist:

https://gist.github.com/jamieorc/980f033af5bf2a8737db

![screen shot 2014-05-23 at 12 09 39 pm](https://cloud.githubusercontent.com/assets/2139/3068942/b8aed5fc-e294-11e3-9839-3ba3e3597212.png)

If I update "One" I have verified the atom is updated, but the screen rerenders with the original "One"

Cheers,
Jamie

**Comment by mike-thompson-day8** [comment]
I think this issue can be closed
