### ISSUE TITLE
Handling ShouldComponentUpdate throwing an exception

### ISSUE THREAD

**Issue by danielcompton** [reagent-project/reagent#350]
In https://github.com/reagent-project/reagent/blob/1e19d31be805f3c4f2a2cd4d3319bf1f12d73894/src/reagent/impl/component.cljs#L160-L172 the `not=` call on line 170 can throw. A minimal example of this is:

```
(= {:todos 1} (sorted-map 1 2))
```

This is being tracked in [CLJ-2325](https://dev.clojure.org/jira/browse/CLJ-2325). It only shows up when using custom types. I don't think it can occur in equality checks between the standard Clojure data structures. A similar issue will need to be raised in CLJS, once the approach to fix it is decided in CLJS.

In the meantime, I wonder if we should wrap `not=` calls here with a try/catch, returning false if it throws. I'm not sure what the performance impact of this is though?

An alternative approach is for developers to manually reset the key of the React component to force a component re-render.

**Comment by Deraen** [comment]
Related: https://github.com/reagent-project/reagent/pull/344

**Comment by Deraen** [comment]
#373 merged
