### ISSUE TITLE
Expose reaction macro on reagent.core

### ISSUE THREAD

**Issue by Deraen** [reagent-project/reagent#356]
I think `reaction` is so important part of Reagent that is should part of the core API.

If is useful with Re-frame when writing subscriptions handlers using `re-sub-raw`.

**Comment by jmlsf** [comment]
Step one might be to get a docstring!  😄 Paging @pesterhazy

**Comment by nashbridges** [comment]
We use `reaction` extensively in our application, and it was always strange to require two namespaces for that:

```cljs
(:require
 [reagent.core :as reagent]
 [reagent.ratom :refer [reaction])
```

So being able to do

```cljs
(:require
 [reagent.core :as reagent :refer [reaction]])
```

would be awesome 👍🏻
