### ISSUE TITLE
reagent 0.8.0-alpha2 does not work with node_modules for browser build

### ISSUE THREAD

**Issue by xafizoff** [reagent-project/reagent#357]
1. `lein new reagent reagent-app`
2. Change reagent version to `0.8.0-alpha2`
3. `npm install react react-dom`
4. `lein cljsbuild once app`

Actual result:
```
[eval]:85
            !id.startsWith(goog:);
                           ^^^^

SyntaxError: missing ) after argument list
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:635:30)
    at evalScript (bootstrap_node.js:462:27)
    at startup (bootstrap_node.js:163:9)
    at bootstrap_node.js:608:3
```
OS: windows 7
npm version: 5.5.1
node v8.9.3

**Comment by Deraen** [comment]
I ran the same commands and this works for me.
Looks like ClojureScript compiler problem, not Reagent.

This is the problematic line: https://github.com/clojure/clojurescript/blob/master/src/main/cljs/cljs/module_deps.js#L85

Not sure why this would cause problems. ClojureScript compiler tests are passing & Reagent CI is also testing this.

Could be Windows related?

**Comment by xafizoff** [comment]
Yes, it is windows related.

**Comment by Deraen** [comment]
Will you open issue at https://dev.clojure.org/jira/browse/CLJS about this? ClojureScript tests are running on Windows CI also, so it is unfortunate if this wasn't catched by that.

**Comment by xafizoff** [comment]
I've posted this on the clojurescript forum.

**Comment by xafizoff** [comment]
Opened issue https://dev.clojure.org/jira/browse/CLJS-2708 as well
