### ISSUE TITLE
Spec'd, instrumented component throws "Invalid arity: 22" error

### ISSUE THREAD

**Issue by miikka** [reagent-project/reagent#358]
Not sure if this is a ClojureScript issue or a Reagent issue, but let's start the discussion here. I'm using ClojureScript 0.10.238 and Reagent 0.7.0. The problem does not occur with ClojureScript 1.9.946.

I have a Reagent form-1 component function with a `cljs.spec.alpha/fdef` spec and I've called `cljs.spec.test.alpha/instrument`. When trying to render the component with more than 21 arguments, I'll get the following error:

```
Uncaught Error: Invalid arity: 22
    at Function.G__10112 [as call] (core.js:6798)
    at Function.cljs.core.MetaFn.apply (core.js:6829)
    at component.js:147
    at reagent$impl$component$wrap_render (component.js:150)
    at reagent$impl$component$do_render (component.js:196)
    at component.js:222
    at reagent$ratom$in_context (ratom.js:61)
    at reagent$ratom$deref_capture (ratom.js:70)
    at reagent$ratom$run_in_reaction (ratom.js:1450)
    at Object.reagent$impl$component$render [as render] (component.js:220)
```

This should reproduce it:

```clojure
(ns foo.core
  (:require [reagent.core :as r]
            [cljs.spec.alpha :as s]
            [cljs.spec.test.alpha :as stest]))

(defn my-component [& args] [:p (pr-str args)])
(s/fdef my-component :args (s/cat :args (s/* any?)))

(defn init! []
  (stest/instrument)
  (r/render (into [my-component] (range 22)) (.getElementById js/document "app")))
```

The problem seems to be this line:
https://github.com/reagent-project/reagent/blob/65683b6b97604dd4b39d4035bc1fc751facfbf7d/src/reagent/impl/component.cljs#L102

You can try this in ClojureScript REPL:
```clojure
(require '[cljs.spec.alpha :as s] '[cljs.spec.test.alpha :as stest])
(defn my-fun [& args] (prn :args args))
(s/fdef my-fun :args (s/cat :args (s/* any?)))
(.apply my-fun nil (into-array (range 22)))
;; :args (0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21)
(stest/instrument)
(.apply my-fun nil (into-array (range 22)))
;; Error: Invalid arity: 22
```

**Comment by pesterhazy** [comment]
Given that you can reproduce the issue without Reagent, isn't this a ClojureScript bug more so than a Reagent issue?

**Comment by miikka** [comment]
At first I wasn't sure if ClojureScript functions are supposed to be callable with `.apply` but @Deraen pointed out that from interop perspective it should work anyway. I will open a ClojureScript issue.

**Comment by miikka** [comment]
https://dev.clojure.org/jira/browse/CLJS-2710
