### ISSUE TITLE
Question: Supported HTML Tags?

### ISSUE THREAD

**Issue by myguidingstar** [reagent-project/reagent#36]
[Sablono][1]'s Readme says:
> ## HTML Tags
>
> *Ŝablono* only supports tags and attributes that can be handled by
React. This means you can't have your own custom tags and attributes
at the moment. For more details take a look at the
[Tags and Attributes](http://facebook.github.io/react/docs/tags-and-attributes.html)
section in the React documentation.

Do we have such limit in Reagent? Sorry if the question is too silly.

[1]: https://github.com/r0man/sablono

**Comment by mike-thompson-day8** [comment]
Close this?
