### ISSUE TITLE
:class no longer supports keywords (since 0.8.0)

### ISSUE THREAD

**Issue by Dexterminator** [reagent-project/reagent#367]
Before Reagent 0.8.0 it was possible to use a keyword as a class (this seems to be facilitated by `convert-prop-value` being called?).

Reagent 0.8.0 breaks this by changing e.g the keyword `:highlight` to the string `":highlight"` (including the `:`, indicating that `name` hasn't been called). In earlier versions of Reagent this would result in the string `"highlight"` and a working class.

Possibly introduced in https://github.com/reagent-project/reagent/pull/323?

**Comment by Deraen** [comment]
Yes, new code is missing `convert-prop-value` after `stringify-class`.

**Comment by Deraen** [comment]
I've been trying to reproduce this but I'm unable to, in both Reagent demo site / test suite, or in a application using Reagent.

I've tried for example `[:div {:class :foo}]` and it is correctly rendered as `<div class="foo">`.

@Dexterminator Could you provide more specific example and information about your environment?

**Comment by Deraen** [comment]
Oh and right after writing the message, I found at least one problematic case: `[:p.a {:class :b}]`.
