### ISSUE TITLE
Default value in React 16 context does not propagate to Consumer

### ISSUE THREAD

**Issue by Lokeh** [reagent-project/reagent#370]
Using Reagent 0.8.0

```clojure
(ns context.core
  (:require [reagent.core :as r]
            ["react" :as react]))

(defonce my-context (.createContext react "wat"))

(defn page []
  (js/console.log my-context)
  (let [Provider (.-Provider my-context)
        Consumer (.-Consumer my-context)
        ]
    [(r/adapt-react-class Provider) {}
     [(r/adapt-react-class Consumer) {}
      (fn [v]
        (js/console.log v)
        (r/as-element [:div "Context: " v]))]]))

(defn start []
  (r/render [page] (.getElementById js/document "app")))


(defn ^:export init [] (start))
```

logs `undefined` for v, but the logging of `my-context` shows that the default value has in fact been set.

I can't tell if this is a problem with the `Provider`'s props or when `adapt-react-class` is applied to `Consumer` yet.

**Comment by Deraen** [comment]
Well, this is strange.

This can be tested without `adapt-react-class`, with `create-element` which doesn't do any automatic conversion for props or children, and the problem still happens:

```
(defonce my-context (react/createContext "wat"))

(defn page []
  (js/console.log my-context)
  (let [Provider (.-Provider my-context)
        Consumer (.-Consumer my-context)]
    (r/create-element
      Provider #js {:value "foo"} ;; if removed, value is nil
      (r/create-element
        Consumer #js {}
        (fn [v]
          (js/console.log "v" v)
          (r/as-element [:div "Context: " v]))))))
```

**Comment by Deraen** [comment]
> The defaultValue argument is used when you render a Consumer without a matching Provider above it in the tree. This can be helpful for testing components in isolation without wrapping them.

https://reactjs.org/docs/context.html

So this is working as intended.
