### ISSUE TITLE
"Uncaught Error: Invalid arity: 1" when using metadata on a component

### ISSUE THREAD

**Issue by Frozenlock** [reagent-project/reagent#39]
Okay, this is weird...

For an unknown reason, when I add metadata to a component (say :component-did-mount), I get an error when trying to load the JS:

"Uncaught Error: Invalid arity: 1"

I get the same error with an empty metadata.

```clj
(defn test-div []
  [:div "hello"])
;; this one works

(def test-div-2
  (with-meta
    test-div
    {:component-did-mount #(.log js/console "asd")}))
;; throws an error

(def test-div-3
  (with-meta test-div nil))
;; throws an error
```

What's worse is that I've already used this method before, so I know it should work!

Any clue on what might be causing this?

**Comment by mike-thompson-day8** [comment]
@Frozenlock  can we close this issue do you think?  I'm guessing we have moved on?

**Comment by Frozenlock** [comment]
Yup, sorry about that.
