### ISSUE TITLE
:> tag triggers false "unique :key" warnings

### ISSUE THREAD

**Issue by ProjectFrank** [reagent-project/reagent#399]
![image](https://user-images.githubusercontent.com/8015872/45096638-fa216e00-b0ee-11e8-8ad1-e36f1ff40a06.png)

The following code triggers warnings about unique keys in seqs:

```clojure
(require '[cljsjs.semantic-ui-react :as ui])

(defn table [{:keys [columns key-fn]} rows]
  [:> ui/Table
   {:celled true}
   [:> ui/Table.Header
    [:> ui/Table.Row
     (for [{:keys [header]} columns]
       [:> ui/Table.HeaderCell
        {:key header}
        header])]]
   [:> ui/Table.Body
    (for [row (take 2 rows)]
      [:> ui/Table.Row
       {:key (key-fn row)}
       (for [{:keys [cell-fn header]} columns]
         [:> ui/Table.Cell
          {:key (str (key-fn row) header)}
          (cell-fn row)])])]])
```

Opening the react debugger in Chrome shows that the keys are successful added to the react elements, despite the warnings.

Using `adapt-react-class` instead makes these warnings go away:
```clojure
(require '[cljsjs.semantic-ui-react :as ui])

(def table-row (adapt-react-class ui/Table.Row))

(def table-cell (adapt-react-class ui/Table.Cell))

(def table-header-cell (adapt-react-class ui/Table.HeaderCell))

(defn table [{:keys [columns key-fn]} rows]
  [:> ui/Table
   {:celled true}
   [:> ui/Table.Header
    [table-row
     (for [{:keys [header]} columns]
       [table-header-cell
        {:key header}
        header])]]
   [:> ui/Table.Body
    (for [row (take 2 rows)]
      [table-row
       {:key (key-fn row)}
       (for [{:keys [cell-fn header]} columns]
         [table-cell
          {:key (str (key-fn row) header)}
          (cell-fn row)])])]])
```

Using the metadata syntax to attach the keys `i.e. ^{:key "some-key"} [:div ...]` also makes the warnings go away:

```clojure
(defn table [{:keys [columns key-fn]} rows]
  [:> ui/Table
   {:celled true}
   [:> ui/Table.Header
    [:> ui/Table.Row
     (for [{:keys [header]} columns]
       ^{:key header}
       [:> ui/Table.HeaderCell
        header])]]
   [:> ui/Table.Body
    (for [row (take 2 rows)]
      ^{:key (key-fn row)}
      [:> ui/Table.Row
       (for [{:keys [cell-fn header]} columns]
         ^{:key (str (key-fn row) header)}
         [:> ui/Table.Cell
          (cell-fn row)])])]])
```

**Comment by kangbb** [comment]
This warning means that you must give a `unique key` for every Component in `for loop`. So you can do as this:

**Comment by Deraen** [comment]
This is a real bug. The key from props is indeed correctly passed to React, but the key check in Reagent looks for the key in wrong place: `https://github.com/reagent-project/reagent/blob/master/src/reagent/impl/template.cljs#L400`

`key-from-vec` only checks the second element of vector for prop map and check if has the key. This works for `adapt-react-class` as the properties map is the second element of vector as usual. For `:<>` the properties map is the third element. `key-from-vec` should check the first element of vector and have special handling for looking key for `:<>`.

**Comment by kangbb** [comment]
> This is a real bug. The key from props is indeed correctly passed to React, but the key check in Reagent looks for the key in wrong place: `https://github.com/reagent-project/reagent/blob/master/src/reagent/impl/template.cljs#L400`
> 
> `key-from-vec` only checks the second element of vector for prop map and check if has the key. This works for `adapt-react-class` as the properties map is the second element of vector as usual. For `:<>` the properties map is the third element. `key-from-vec` should check the first element of vector and have special handling for looking key for `:<>`.

Thanks for your correction. I will to learn more about it.
