### ISSUE TITLE
No need to define externs?

### ISSUE THREAD

**Issue by peeb** [reagent-project/reagent#41]
Hi Dan, purely out of curiosity, I notice that it's unnecessary to define externs when using the advanced compilation mode of the Google Closure Compiler with reagent projects. I'm wondering how you achieved this.

Thanks.

**Comment by holmsand** [comment]
The upcoming version of Reagent will use the new foreign lib inclusion mechanism in ClojureScript, mentioned by @tonsky, and that provides externs automagically.

Reagent itself will still work without externs (by using the interop macros here: https://github.com/reagent-project/reagent/blob/master/src/reagent/interop.clj), to make it easier to use Reagent with e.g React from a CDN.

Closing this.
