### ISSUE TITLE
security alert from package-lock.json

### ISSUE THREAD

**Issue by yogthos** [reagent-project/reagent#410]
There's a [security warning](https://github.com/reagent-project/reagent/network/alert/package-lock.json/cached-path-relative/open) for an old version cached-path-relative. It looks like it's coming from package-lock.json, I think that file should probably be added to gitignore.

**Comment by Deraen** [comment]
Package-lock file is intended to be indexed in git: https://github.com/npm/npm/blob/v5.0.0/doc/files/package-lock.json.md#description

I'll just disable npm security alters as they don't really affect us.
