### ISSUE TITLE
Reagent renders Hickory generated Hiccup with &escapes; litterally

### ISSUE THREAD

**Issue by ghost** [reagent-project/reagent#413]
Hickory claims to generate valid Hiccup (see e.g. davidsantiago/hickory#25), but Reagent appears to render that wrongly: If it contains `&escapes;`, e.g. `&#39;` for `'`, the escaped token will be rendered literally on the page. If React force-escapes input strings and the workarounds are troublesome, which I gather from #14 and #104, is it possible to make Reagent unescape strings before passing them on?

**Comment by Deraen** [comment]
As mentioned in 104, you can call `gstring/unescapeEntities` to convert HTML char entities to Unicode characters. But the call is not very performant if I recall correctly, so Reagent can't automatically call it.

Reagent probably isn't fully Hiccup compatible anyway, just "Hiccup-style".
