### ISSUE TITLE
Reagent component doesn't re-render after put into React portal

### ISSUE THREAD

**Issue by mt0erfztxt** [reagent-project/reagent#418]
- Version of Reagent being used - 0.8.1
- Minimal reproduction steps - repo with examples is [here](https://github.com/mt0erfztxt/reagent-portal-rerendering)

**Comment by lucywang000** [comment]
I came across the same problem, but fixed it by putting the content of the modal into a separate reagent component (or wrap the input with `r/create-class`), instead of passing its full hiccup as an argument.

E.g. Given your code, I believe putting the form into a function could solve it.

```clojure
(defn modal-in-portal [title content]
  (reagent/create-class
   {:render #(.createPortal js/window.ReactDOM
                            (reagent/as-element [modal title content])
                            (js/document.getElementById "portals-container"))}))
```

```clojure
(defn example-b []
  (let [state (reagent/atom "case b")]
    (fn []
      (let [value @state]
        [modal-in-portal
         "Example B - Modal rendered with React portal and form in-lined into modal (modal content not re-rendered)"
         [:form
          [:input
           {:on-change #(reset! state (event->value %))
            :type "text"
            :value value}]
          [:input
           {:disabled true
            :type "text"
            :value value}]]]))))
```

**Comment by lucywang000** [comment]
Forget all the above analysis, I think the answer is the typical caveat for reagent form-2 components: the props shall be passed to the innermost render function, otherwise it would capture the initial value of the outer function forever ...

For instance, with your example code, this fix should be:

```clojure
(defn modal-in-portal []
  (reagent/create-class
   {:render  (fn [title content] 
                          (.createPortal js/window.ReactDOM
                            (reagent/as-element [modal title content])
                            (js/document.getElementById "portals-container"))})))
```

Of course the easiest way is to simply get rid of the `reagent/create-class` all together.

**Comment by lucywang000** [comment]
created a pr to update the doc about portals: #488
