### ISSUE TITLE
Infer issue in with-let

### ISSUE THREAD

**Issue by aisamu** [reagent-project/reagent#420]
`with-let` is giving us an inference error during compilation of `:advanced` ("release") builds with shadow-cljs:

```
   5 |   (r/with-let [... ...
---------^----------------------------------------------------------------------
 Cannot infer target type in expression (. c__12709__auto__ -ratomGeneration)
--------------------------------------------------------------------------------
```

This was observed before (https://clojurians-log.clojureverse.org/shadow-cljs/2017-12-20), and it appears that part of it was already solved, since I'm only getting one of the errors mentioned.

Adding the type hint pointed on the slack channel solves it:
```diff
        (when ~asserting
-         (when-some [c# reagent.ratom/*ratom-context*]
+         (when-some [^clj c# reagent.ratom/*ratom-context*]
            (when (== (.-generation ~v) (.-ratomGeneration c#))
```

Things appear to be working as expected, and `./run-tests.sh` was successful.
If that wasn't already known and you don't see any unwanted side-effects, I'll gladly open a PR for it (if you so prefer).

Thanks for this great lib!

 #### Environment
* Reagent `0.8.1`
* Clojurescript `1.10.439`
* Shadow-cljs `2.7.8`

**Comment by Deraen** [comment]
I reproduced this without Shadow-cljs and commited fix with a test. I've deployed new 0.9.0-SNAPSHOT with the fix.

**Comment by aisamu** [comment]
That was fast, thanks!
