### ISSUE TITLE
JVM Dependency for Examples

### ISSUE THREAD

**Issue by cwstra** [reagent-project/reagent#422]
New user here.

I decided to use play around with the examples for learning purposes, but when initially trying to run them locally, I was plagued with error messages. I managed to find the probable cause online – namely, JVM version issues – and managed to fix them by updating the `project.clj`. The changes in question were
• In `:dependencies`: Upping the `clojure` and `clojurescript` versions to 1.10.0 and 1.10.191 respectively
• In `:plugins`: Upping `lein-figwheel` to 0.5.18

While things are now going swimmingly on my end, I might suggest either adjusting the `project.clj` to have conditional versions, or (assuming my diagnosis is correct) noting the required JVM in the readme.

**Comment by Deraen** [comment]
Which JVM versions worked and didn't work for you?

At least Java 8 should work and those new deps probably fix Java 11 compatibility.

**Comment by Deraen** [comment]
Anyway, I've now updated deps for examples.

**Comment by cwstra** [comment]
Based on the versions I have available, it seems the old examples don't function for Java 9 and above, which seems to match with the error messages such as the one below, which suggest the JAXB change might be to blame. The update also does _not_ seem to break the older versions I have, which might be expected, but still good news.

`Exception in thread "main" java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter, compiling:(cljs/closure.clj:1:1)
	at clojure.lang.Compiler.load(Compiler.java:7239)
	at clojure.lang.RT.loadResourceScript(RT.java:371)
	at clojure.lang.RT.loadResourceScript(RT.java:362)
        ...
	at clojure.main.main(main.java:37)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter
        ...`

**Comment by Deraen** [comment]
Example dependencies are now up-to-date.
