### ISSUE TITLE
Generalize props and children to accept hiccup forms

### ISSUE THREAD

**Issue by matiasmorant** [reagent-project/reagent#423]
I would like to use the props and children functions with a hiccup for argument, instead of a component. I know that these are just items of a vector, but having these functions automatically dispatch on its input type would add convenience

**Comment by Deraen** [comment]
I don't know. I don't see the point of trying to extract props or children out of Hiccup form. In what use case would you need this?

If you need to parse hiccup data, it sounds like you are trying to render the data yourself instead of using Regent?

**Comment by wvlia5** [comment]
I have implemented this as follows:
`
(defn props [x]
	(if (= (type []) (type x))
		(let [p (x 1)] (if (= (type {}) (type p)) p {}))
		(r/props x)))

(defn children [x]
	(if (= (type []) (type x))
		(let [p (x 1)] (if (= (type {}) (type p)) (rest (rest x)) (rest x)))
		(r/children x)))
`

I'm using them while creating a higher-order-component which allows me to make another component Selectable:
`
(defn Selectable [{:keys [timeout onPress onRelease onClick onHold]} child]
  (let [last-down (r/atom 0)
        last-up (r/atom 0)]
    (into [] (concat
      [(child 0)
      (merge (props child)
        {:onMouseDown (fn [] (do 
          (reset! last-down (.now js/Date))
          (js/setTimeout #(if (and (> @last-down @last-up) (> (- (.now js/Date) @last-up) timeout)) (onHold)) timeout)
          (if onPress (onPress))))
        :onMouseUp (fn [] (do 
          (reset! last-up (.now js/Date))
          (if onRelease (onRelease))
          (if (and onClick (< (- @last-up @last-down) timeout)) (onClick))))})]
      (children child)))))
`

Then I use the Selectable HOC inside a map, as follows:
`
          [List
            (doall (map-indexed (fn [i n]
              [Selectable
                {:key i
              	:timeout 1000
                :onClick #(if (not(empty? @selected-items)) (onRowSelect i)) ; {this.props.onClick(dietName)}
                :onHold #(onRowSelect i)} 
                [ListItem {:button true :selected (boolean (some #{i} @selected-items))}
                	[ListItemText n]]])
              @diet-names))]
`

For  the `child`argument in Selectable, I get a Hiccup. This works. I might not be doing things in the 'correct' way, but after some hours, I could find out what the 'correct' way is. Surely other beginners will experience the same

**Comment by wvlia5** [comment]
I would appreciate it if you could give me some hint of what i'm doing wrong (if anything) and how to correct it.

**Comment by Deraen** [comment]
Sorry, I don't really understand the example so can't say if there is something wrong there.

In general, if you need to access the data in component, pass in the data, don't try to retrieve the data from Hiccup elements. Even if you already pass in Hiccup elements, you can also pass in the original data in easy to handle format.
