### ISSUE TITLE
Add getDerivedStateFromProps method

### ISSUE THREAD

**Issue by khmelevskii** [reagent-project/reagent#424]
In such cases I need to use `componentWillReceiveProps ` lifecycle method but this method was deprecated. We need to use `getDerivedStateFromProps` instead of `componentWillReceiveProps`. How ca I do this with reagent?

**Comment by khmelevskii** [comment]
hey @Deraen , sorry to bother you but just curious, is reagent going to be maintained in future?

**Comment by Deraen** [comment]
Well, it is possible to define the `getDerivedStateFromProps` like follows:

```
(defn foobar []
  (r/create-class
    {:reagent-render (fn []
                       [:p "foo"])
     :get-derived-state-from-props
     (fn []
       (this-as this
         (js/console.log "get derived state from props")
         #js {}))}))
```

Problem with this is that Reagent internally uses `componentWillMount` legacy method, which won't be called when using these new methods, and this will break Reagent.

I don't have good idea yet what it would require to refactor Reagent to not use legacy methods, but it won't be easy.

**Comment by khmelevskii** [comment]
Thank you for explanation @Deraen! I understood. Btw, what's your plans about reagent and react 16.8 with hooks? Should we wait update reagent API and major update?

**Comment by Deraen** [comment]
https://reactjs.org/docs/hooks-faq.html#should-i-use-hooks-classes-or-a-mix-of-both

> You can’t use Hooks inside of a class component

Currently Reagent implementation creates a class from every Reagent component, so being able to use hooks inside Reagent components (i.e. components using Ratoms and where Reagent turns hiccup into React elements) will require major refactoring. However, you can use React components using Hooks inside Reagent, or use [hx](https://github.com/Lokeh/hx) components inside Reagent. And Reagent already works with 16.8, new features aren't just usable from Reagent components directly.

**Comment by Deraen** [comment]
Also, it is possible to create React components using Reagent API, because React function component is just a function that happens to return React elements, and `r/as-element` does just that:

```cljs
;; This is React function component. Can't use Ratoms here!
(defn example []
  (let [[count set-count] (react/useState 0)]
    (r/as-element
      [:div
       [:p "You clicked " count " times"]
       [:button
        {:on-click #(set-count inc)}
        "Click"]])))

;; Reagent component
(defn reagent-component []
  [:div
   ;; Note :> to use a function as React component
   [:> example]])
```

**Comment by Deraen** [comment]
Supported & tested in 0.9: https://github.com/reagent-project/reagent/blob/8f9045311c62af39a0b61252482a35fe0c79d2ca/test/reagenttest/testreagent.cljs#L1297-L1319
