### ISSUE TITLE
Inconsistent class name combination for tags & class/className

### ISSUE THREAD

**Issue by cszentkiralyi** [reagent-project/reagent#433]
In upgrading from `1.8.0-alpha2` to `1.8.1`, I noticed that some of rendered elements had incorrect classes applied to them. I dove in to a Figwheel REPL to figure out what was going on:
- Any of `[:div.foo]`, `[:div {:class "foo"}]`, or  `[:div {:className "foo"}]` work as expected, giving us a `<div class="foo" />`:
![image](https://user-images.githubusercontent.com/12720943/60204522-4075c400-980c-11e9-9c8e-6a2e8eb658f9.png)
- `[:div.bar {:class "foo"}]` works as expected, combining the tag's classes with the specified string:
![image](https://user-images.githubusercontent.com/12720943/60204601-6c914500-980c-11e9-96d8-d88618a6e222.png)
- `[:div.bar {:className "foo"}]` does _not_ work as expected, the tag's class is used but the string is entirely ignored:
![image](https://user-images.githubusercontent.com/12720943/60204675-9c404d00-980c-11e9-8811-545dea62be7c.png)

The `:className` prop under 1.8.0-alpha2 would combine with a tag's class(es) just like `:class` does now, which would result in `<div class="bar foo" />`. That's no longer the case under 1.8.1, and I couldn't find any mention of this kind of behavior being changed in the changelog. Is this an intended change, a bug, or was combining tag classes with either of those props not intended in the first place?

**Comment by Deraen** [comment]
I think `className` property in Reagent hiccup props has never been officially supported. Which means it didn't have any test cases, so I didn't catch this when `:class` handling was changed. It accidentally worked previously as  `className` didn't require any special handling and combining classes from hiccup tag and props was done at latter step.

I think this can still be considered regression and could be fixed.
