### ISSUE TITLE
Remove leiningen as prerequisite

### ISSUE THREAD

**Issue by Ashe** [reagent-project/reagent#436]
This can be misleading to new users, as Reagent is fully capable of being used in conjunction with `deps.edn` and Clojure CLI.

**Comment by danielcompton** [comment]
Where does it say that Leiningen is a prerequisite? I can see that lein is used for a new project template, is that what you’re referring to?

**Comment by Ashe** [comment]
![image](https://user-images.githubusercontent.com/8940077/62000227-6d4a1f00-b0c9-11e9-913b-1ea5a8c80e90.png)
At the bottom of my screenshot you'll see it says leiningen, without reference to the new project template you mentioned. As a beginner I certainly believed this was the case for a bit!

**Comment by danielcompton** [comment]
Ah I see, good spotting!

**Comment by Deraen** [comment]
I've removed the prerequisites list and moved mention of Leiningen to project template command.
