### ISSUE TITLE
Printing an atom/reaction/tracking isn't valid EDN

### ISSUE THREAD

**Issue by Lokeh** [reagent-project/reagent#439]
Printing an atom as currently implemented is not valid EDN, which prevents serializing and reading it later (either for state hydration or just introspection).

Example:

```clojure
(def a (reagent.core/atom 0))

(pr-str a) ;; => "#<Atom: 0>"
```

My proposed solution would be to print in a way that would be valid EDN, e.g.:

```clojure
(pr-str a) ;; => "#reagent/ratom[0]"

;; Trackings, cursors reactions could also be done:

(pr-str some-cursor) ;; => "#reagent/cursor[\"foo\"]"
(pr-str some-reaction) ;; => "#reagent/reaction[\"bar\"]"
(pr-str some-tracking) ;; => "#reagent/tracking[\"baz\"]"
```

**Comment by danielcompton** [comment]
What would be the desired semantics for rehydrating any of these? A core part of their nature is that they 'know' who has dereferenced them, but this would be difficult if not impossible to do after serialisation.

For debugging, it seems easy enough to me to dereference these to get the values inside. For serialisation, again it seems like you'd most often want just the data, not the full container.

Are there other use-cases you're thinking of?

**Comment by Lokeh** [comment]
My specific use case: I’m building a tool for introspecting / `nav`-ing data for CLJS called punk. The app works by running remotely from the actual user code, so that punk doesn’t have to exist in the same process as the application it’s being used to develop (in contrast to REBL, which doesn’t work remotely and needs to live in the same JVM process as the app it’s inspecting values in). It relies on serializing the data to EDN and sending it back and forth over a remote connection to and from the client application.

I was debugging an app at work and tried to inspect a data structure that looked something like:

```clojure
{:foo {:bar (r/atom “baz”) :asdf (r/atom “jkl”}}
```

And sending this to punk (serializing via pr-str) gave:

```clojure
{:foo {:bar #<Atom “baz”>}
           :asdf #<Atom “jkl”>}}
```

Which the remote tool understandably choked on.

**Comment by Lokeh** [comment]
I think the general idea is that: a RAtom is a value that can exist in some collection that gets serialized, in which case if we want to be able to deserialize it we should print it as valid EDN.

**Comment by Deraen** [comment]
Does serializing and deserializing regular atoms work?

We could provide methods for `RAtom` but it is impossible to serialize `Reaction` in meaningful way. Still, we can print them in way that doesn't break reader, though it can't deserialize them properly.

**Comment by Deraen** [comment]
I guess you would have your own readers anyway,  since Reagent doesn't provide any JVM code. And you don't need to deserialize reaction value to `Reaction`  instance. We can serialize current value easily. I guess that will be enough for debugging. For `Track` and `Cursor` we can also save some additional information.

**Comment by Lokeh** [comment]
I'm not really interested in being able to deserialize in a way that preserves behavior even, just in a way that can be read. In the inspector app, the default reader for tagged values is set to be `tagged-literal` so I can at least allow it to read any valid EDN, even if the tag itself isn't known.

**Comment by Lokeh** [comment]
Regular atoms get printed as by default as `#object [cljs.core.Atom ...]` IIRC which can be read perfectly fine.

**Comment by danielcompton** [comment]
> Regular atoms get printed as by default as #object [cljs.core.Atom ...] IIRC which can be read perfectly fine.

Are you sure? On Clojure I get this:

```clojure
(read-string (pr-str (atom 5)))
Execution error at dev/eval35637 (form-init5918015483486244902.clj:1).
No reader function for tag object
```

I would be surprised if this works in CLJS, I don't think `#object` normally has a reader?

**Comment by Lokeh** [comment]
It is being read successfully, it just doesn't have an associated reader function for that tag. You can pass in function associated with `object` that will parse the tagged literal. In the case of `object`, I am just using `tagged-literal`.

**Comment by danielcompton** [comment]
If you’re using `nav`, can you define your own extensions for how to inspect and navigate Reagent objects? I haven’t really used it, but I think this is a good use-case for it?

**Comment by Deraen** [comment]
Implemented in master, the output matches normal Atom very closely.
