### ISSUE TITLE
Warning regarding error boundaries - getDerivedStateFromError

### ISSUE THREAD

**Issue by mtruyens** [reagent-project/reagent#453]
In the newest Reagent/React releases, I get a ReactJS warning "Error boundaries should implement getDerivedStateFromError". 

I used the following structure: 

(r/create-class
      {:display-name ...

       :component-did-catch
       (fn [this e info] ...)

       :reagent-render
       (fn ... )})

**Comment by Deraen** [comment]
Yes, this is expected with the new React version.

I've now updated docs in preparation for 0.9: https://github.com/reagent-project/reagent/commit/edb3d2d322b46abda06d20e4fce2de7daa92e98e

**Comment by mtruyens** [comment]
Hi, 

Isn't there a mistake in the keyword? It seems to contain the suffix :get-derived-state-from-error-test, which is probably not necessary?

**Comment by Deraen** [comment]
Yeah, fixed now.
