### ISSUE TITLE
Missing value for goog.object/set call

### ISSUE THREAD

**Issue by thheller** [reagent-project/reagent#454]
I just ran a build using `[reagent "0.9-0-rc1"]` through `shadow-cljs check` which does a bit of type checking using the Closure Compiler. It found and complained about this.

```
------ WARNING #37 -  ----------------------------------------------------------
 File: ~/.m2/repository/reagent/reagent/0.9.0-rc1/reagent-0.9.0-rc1.jar!/reagent/impl/template.cljs:50:8
--------------------------------------------------------------------------------
  47 |     (if-some [k' (cache-get prop-name-cache (name k))]
  48 |       k'
  49 |       (let [v (util/dash-to-prop-name k)]
  50 |         (gobj/set prop-name-cache (name k))
--------------^-----------------------------------------------------------------
 Function goog.object.set: called with 2 argument(s). Function requires at least 3 argument(s) and no more than 3 argument(s).
--------------------------------------------------------------------------------
  51 |         v))
  52 |     k))
  53 |
  54 | (defn ^boolean js-val? [x]
--------------------------------------------------------------------------------
```

https://github.com/reagent-project/reagent/blob/078976de269463c45e2835a42a160cbb3b8f570d/src/reagent/impl/template.cljs#L50

**Comment by Deraen** [comment]
Ha, good catch. I've been thinking about adding Shadow-cljs config here and `check` seems like a good reason to do so.

**Comment by thheller** [comment]
Unfortunately `check` isn't all that useful most of the time but it can find stuff like this for direct uses of the Closure Library. It does produce a lot of noise so it is easy to miss the "real" stuff. This check for example produced over 40 warnings and only one was relevant.
