### ISSUE TITLE
Scripts in inner html not evaluated 

### ISSUE THREAD

**Issue by awb99** [reagent-project/reagent#457]
I am injecting Javascript scripts into reagent components. 

(defn html-script [html-script]                                                                                                                                                
  [:span {"dangerouslySetInnerHTML"                                                                                                                                             
         #js{:__html html-script}}])

(html-script "<script> console.log('hi')</script>")

I can see the script elements containing the script im the dom, 
But they never get executed. 

I am working on a port of gorilla repl to reagent and need to allow 
Custom ui components that bring their own Javascript under the
hood. 

Is there a way to make reagent allow running scripts inside 
reagent components? 

Thanks

**Comment by Deraen** [comment]
Some workarounds are mentioned in https://github.com/facebook/react/issues/8838

The example you give, could be implemented as

```
(html-script "<img onerror="console.log('hi')">")
```

Or you could use https://developer.mozilla.org/en-US/docs/Web/API/Range/createContextualFragment, which should allow adding script tags, from component Lifecycle methods (componentDidMount) to modify the created DOM element with your own content.
