### ISSUE TITLE
cljdoc as official documentation?

### ISSUE THREAD

**Issue by dijonkitchen** [reagent-project/reagent#463]
Looks like https://cljdoc.org/d/reagent/reagent is pretty good, should those be the new official docs?

**Comment by Deraen** [comment]
Cljdoc can't be updated without new release: https://github.com/cljdoc/cljdoc/issues/31 This doesn't really work as it has been 1.5 years since last release but docs have been worked on a lot since then.

**Comment by dijonkitchen** [comment]
Not sure this is true; if you go to the cljdoc link above, it goes to the latest RC version from 29 days ago. Is not that up to date? Seems like whenever there's any release (not necessarily a stable one), it'll generate the docs and have an appropriate link.

**Comment by Deraen** [comment]
Readme now links to Cljdoc for the latest stable release, and to the local api & docs for the next release.
