### ISSUE TITLE
get-derived-state-from-error not implemented as a static method

### ISSUE THREAD

**Issue by Lokeh** [reagent-project/reagent#466]
Using Reagent 0.8.1 and React 16.9.0, when I implement `:get-derived-state-from-error` I see this error in the browser console, and no error is caught:

`backend.js:6 Warning: ErrorBoundary: getDerivedStateFromError() is defined as an instance method and will be ignored. Instead, declare it as a static method.`

Code:

```clojure
(defn error-boundary [_]
  (r/create-class
    {:display-name "ErrorBoundary"
     :get-initial-state
     (fn [_]
       #js {:error nil})
     :get-derived-state-from-error
     (fn [error]
       #js {:error error})
     :render
     (fn [this]
       (-> (if-let [error (.. this -state -error)]
             [:pre [:code (pr-str error)]]
             (into [:<>] (r/children this)))
           (r/as-element)))}))
```

**Comment by Deraen** [comment]
Reagent 0.9 will support React 16.9 and implements getDerivedStateFromError as static method: https://github.com/reagent-project/reagent/blob/master/src/reagent/impl/component.cljs#L316
