### ISSUE TITLE
DOM refs aren't accessible

### ISSUE THREAD

**Issue by mattbetzel** [reagent-project/reagent#5]
React [supports](http://facebook.github.io/react/docs/more-about-refs.html#the-ref-attribute) a _ref_ attribute for gaining access to a specific DOM element in a component.  In this example, I should be able to focus the _input_ field after it is mounted in the DOM:

``` clojure
(defn login []
  [:form
   [:input#username {:type "text" :ref "username"}]])

(def login-with-focus
  (with-meta login
    {:component-did-mount (fn [this] (.. this -refs -username (getDOMNode) (focus)))}))
```

It doesn't work because cloact implicitly creates a component for each of the vectors in the _render_ function.  The [React Chrome Plugin](https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi?hl=en) shows this behavior:
![React Console](http://mattbetzel.github.io/ref-plugin.png)
The _ref_ is added to the highlighted component which is implicitly created instead of being attached to the login component (called "cloact1").

I'm thinking this isn't an easy problem to solve.  It seems ideal to avoid creating the implicit components but the current design works with the assumption that every child should be promoted to a component if it isn't already one.

[Sablono](https://github.com/r0man/sablono) might be helpful here because it can convert Hiccup into a nested tree of `React.DOM.*` calls.

BTW I really like cloact and it feels like the most idiomatic ClojureScript interface to React.
Matt

**Comment by levitanong** [comment]
But say, what if I want to focus and blur an input component from elsewhere? Either through a keyboard handler bound to the document in the parent component, or simply through a different component altogether?

**Comment by Deraen** [comment]
String refs are legacy feature in React and are likely to be removed in future version: https://reactjs.org/docs/refs-and-the-dom.html#legacy-api-string-refs

Ref callbacks work.
