### ISSUE TITLE
Restore reagent.core/render fn

### ISSUE THREAD

**Issue by thheller** [reagent-project/reagent#501]
A beginner asking in #shadow-cljs chat was trying to use `reagent.core/render` in `alpha2` but since that is removed they were mislead by the resulting `Undeclared var ...`. Thinking it was a problem in their setup. I'd suggest restoring that fn with a stub that just throws at runtime explaining the moved var. Easier to diagnose than a weird compiler error.

Just my 2 cents though.

**Comment by Deraen** [comment]
I prefer compile time exception to runtime for removed functions. I guess a macro could throw error during the compilation.

**Comment by thheller** [comment]
Yeah, the issue is that a "Undeclared var" warning is not exactly clear when most of the examples/articles use the old `reagent.core/render`. Leads the user to think it is a mistake in their setup when it is not.
