### ISSUE TITLE
Framer Motion library not working properly with reagent

### ISSUE THREAD

**Issue by zendevil** [reagent-project/reagent#502]
I'm using the framer-motion library to animate a div mount

This is what I have:
```
(:require [framer-motion :refer (motion MagicMotion AnimateSharedLayout AnimatePresence useSpring useMotionValue useTransform useViewportScroll) :as motion])
(def div (.-div motion))
(defn my-component []
    [:> div {
      :initial {:opacity 0}
      :animate {:opacity 1}
      :exit {:opacity 0}} 
"Show Me"])
```
And a boolean ```show-my-component?``` is changed from false to true when I click on a button (I'm using re-frame for managing the boolean ```show-my-component?``` but have simplified the code here):
```
[:button {:on-click (change-show-my-component-boolean-to-true)}]
(if show-my-component? [my-component])
 ```
But the component doesn't show immediately when clicking the button when using :>div, although it does when using a regular :div, but in the latter case of course there's no animation 

when using ```:> div```, I have to re-focus or click somewhere on the webpage for my-component to show

How do I fix this issue?

**Comment by rmschindler** [comment]
Not that this is any help, but i would love for someone to weigh in on this. Furthermore, zendevil, i'm impressed you got as far as importing the framer-motion library. I've tried all day to get framer-motion merely _required_, to no avail. I'm using shadow-cljs, but i can't think how that matters. (Besides, i'm so happy with shadow-cljs, i'd sooner give up on a promising new npm than shift from shadow-cljs as my build tool.)

**Comment by zendevil** [comment]
The opacity animation from 0 to 1 is triggered on click, and not on page load.

**Comment by Deraen** [comment]
I tested framer-motion with Reagent and toggling a animated div with opacity changes works here: https://github.com/reagent-project/reagent/compare/framer-motion-example

**Comment by zendevil** [comment]
It does work for me with reagent 0.10.0 and react/react-dom 16.8.6, but not with reagent 1.0.0-alpha2 and react/react-dom 16.13.0. Your test uses shadow-cljs 2.8.93. I'm using 2.9.2.

**Comment by Deraen** [comment]
What doesn't work?

I've updated deps and the example still works fine.

**Comment by rberger** [comment]
I was able to make a similar use case as you show in the new example work, but there a some framer-motion use cases where we seem to need to use a react hook from framer-motion. A good example is from [Framer Motion Example 35 Swipe to Delete](https://framerbook.com/x/animation/example-animations/35-swipe-to-delete/) ([CodeSandbox](https://codesandbox.io/s/framer-motion-example-35-z9hqi?module=%2Fsrc%2FExample.jsx))

In particular around the use of the[ Animation Controls](https://www.framer.com/api/motion/animation#animation-controls):
```
const controls = useAnimation();
...
controls.start({ x: 0, opacity: 1, transition: { duration: 0.5 } });
```

I get the error:
```
Uncaught Invariant Violation: Invalid hook call. Hooks can only be called inside of the body of a function component
This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
...
```

My framer-motion/react/reagent fu is not up to figuring out how to do any of the above in the reagent context.

**Comment by Deraen** [comment]
I've added an example using `useAnimation` and `useEffect` hooks.
