### ISSUE TITLE
[Feature request] Shorthand syntax for [:div.classname]

### ISSUE THREAD

**Issue by dvingo** [reagent-project/reagent#508]
When using [sablono](https://github.com/r0man/sablono) you can do the following:

```clojure
[:.ui.grid
  [:.row 
    [:.six.wide.column "Some content"]]]]
```
Which is the same as:
```clojure
[:div.ui.grid
  [:div.row 
    [:div.six.wide.column "Some content"]]]]
```
It would be nice to do this with reagent as well.

Is there interest in adding support for this?

**Comment by Deraen** [comment]
I'm not very interested in this.

I just don't see any benefits in this, and can find several cons:
- Makes the implementation even more complex and slower. Parsing Hiccup forms happens on runtime in Reagent, while Sablono can parse Hiccup using macros. Any additions here will affect rendering of every Reagent component.
- Reading the shorthand code is harder
- Two ways the write the same element

**Comment by dvingo** [comment]
Thanks for the reply @Deraen - given the cons to implementing this I think it's reasonable to not support it.

**Comment by mike-thompson-day8** [comment]
Yes, very difficult for someone new to Reagent to know what is going on, and even if they intuit it by some miracle,  is it a div or a span?  And it would be impossible to google for the answer.  And all this to save three chars (granted, repeatedly).  It is lovely and explicit as is - you read it and you can kinda guess what is happening (the class syntax is a little magic)
