### ISSUE TITLE
Production build for examples is broken

### ISSUE THREAD

**Issue by AndreasS2501** [reagent-project/reagent#512]
https://github.com/reagent-project/reagent/tree/master/examples/simple
(same for todomvc etc..)

In the project.clj 's for the examples it seems the configuration for the "production build" as advertised by the README.md is not working:
lein figwheel => works
lein clean; lein with-profile prod compile
=> doesn't do anything?

**Comment by Deraen** [comment]
Fixed in 9ecc6d2ee869ab5d6a6475272ce9006ff09bc8ea

**Comment by AndreasS2501** [comment]
Thank you
