### ISSUE TITLE
Sets of classes aren't properly joined

### ISSUE THREAD

**Issue by AdamClements** [reagent-project/reagent#52]
`[:div.test {:class #{:foo :bar}}]` very nearly works as one might expect, but it comma separates the classes, leaving you with `<div class="test foo,bar"/>` rather than the correct `<div class="test foo bar"/>`

It would be nice if this was either explicitly forbidden (errored out) or worked properly for classes.

**Comment by mike-thompson-day8** [comment]
See also #154

**Comment by Deraen** [comment]
Merged #138 and released in 0.8.0-alpha2
