### ISSUE TITLE
Nil Value Not Updating Text Input

### ISSUE THREAD

**Issue by whamtet** [reagent-project/reagent#53]
(def value (atom {"a" "Original Content"}))

    (defn content []
      [:div
      [:input {:type "text"
            :value (get-in @value ["a"] "") ; <<<--- DEFAULT VALUE SHOULDN'T BE NECESSARY
            :on-change #(swap! value assoc "a" (-> % .-target .-value))
            }]])

    (defn clear-content []
      (reset! value nil))

The above code gives a text box which responds to user input and can be cleared by calling clear-content.  However if no default value is included

    :value (get-in @value ["a"])

instead of 

    :value (get-in @value ["a"] "")

then calling clear-content results in value returning a null value and not clearing the text box as it should.  Subtle but annoying.

Thanks for the great library BTW.

**Comment by yogthos** [comment]
this appears to work correctly in the latest version
