### ISSUE TITLE
render-to-static-markup requires :on-change for inputs

### ISSUE THREAD

**Issue by chr15m** [reagent-project/reagent#550]
Rendering something as static markup implies no interactivity. Should this warning be thrown?

```clojure
(render-to-static-markup [:input {:value 12}])
```

Warns with this:

```
Warning: You provided a `value` prop to a form field without an `onChange` handler. This will render a read-only field. If the field should be mutable use `defaultValue`. Otherwise, set either `onChange` or `readOnly`.
    at input
    at ReagentInput (file:///...)
```

The error goes away if you add `:on-change nil`.

**Comment by Deraen** [comment]
The warning is from React, and we are using `react-dom/server` to render the static markup, React team decided that this shouldn't be fixed: https://github.com/facebook/react/issues/8482

If you are sure you want static value, use `defaultValue`. If you might later make this dynamic, use value and onChange.

**Comment by chr15m** [comment]
`defaultValue` works perfectly, thanks. Sorry for the noise.
