### ISSUE TITLE
Docs on “Changed?” inaccurate?

### ISSUE THREAD

**Issue by shaunlebron** [reagent-project/reagent#574]
Hi, I’m trying to understand when things update.  From the docs, [When Do Components Update?][doc]:

> As of Reagent 0.6.0, ratoms use `=` (instead of `identical?`) is to determine if a new value is different to an old value. So, `ratoms` and `props` now have the same `changed?` semantics. 

This was hard to track down, but from what I found, `=` is never used on ratoms for determining when to update components:

1. A reagent component’s render function is first run with `run-in-reaction` to capture all the ratoms/reactions that are deref’d during  that render.  
2. The `handle-change` function of the render’s reaction object is then added as a watcher for each deref’d ratom/reaction, via `-add-watch`.
3. If some new value is inserted into one of those deref’d ratoms, via `-reset!`, it will indiscriminately invoke all of its watchers (no equality checks).
4. The render reaction object’s `handle-change` is then called with the new/old values of the updated ratom, and only continues if the values are not `identical?`
5. The `auto-run` property of the render reaction object is then called, which is `batch/queue-render`.

Is this correct?  If so, I can update the docs to reflect this.

[doc]:https://github.com/reagent-project/reagent/blob/master/doc/WhenDoComponentsUpdate.md#changed

**Comment by shaunlebron** [comment]
Here’s an OrgPad for tracing this: https://orgpad.com/s/n3W2BotZfA_?open=all

<img width="1124" alt="CleanShot 2022-08-24 at 16 24 12@2x" src="https://user-images.githubusercontent.com/116838/186526414-2d125942-97a2-4c71-a877-6d0a93ee8c53.png">

**Comment by mike-thompson-day8** [comment]
@shaunlebron 
I'm struggling to remember the flow of control right now (I knew it well in 2015!) , but from memory, I feel this is a key line of code:

https://github.com/reagent-project/reagent/blob/master/src/reagent/ratom.cljs#L466

Note the `=` check.  

Given your investigation (it looks like you have your head wrapped around the code) does that make any sense?

**Comment by mike-thompson-day8** [comment]
I wrote the docs which you are questioning, so I'm feeling like I should be able to answer you definitively,  BUT it is all a long time ago ... so all I can add for the moment is a further fact I can remember ... there was a time when `identical?` was used but that lead to programmers being "surprised", so we switched to `=` (which actually does an `identical?` check internally anyway but moves on to deeper checks on `false`) 

This change is mentioned in the [change log for v6.0.0](https://github.com/reagent-project/reagent/blob/master/CHANGELOG.md#060-alpha).  Note:
>  Reactions now only trigger updates of dependent components if their value change, as reported by `=` (previously,` identical?` was used).

**Comment by Deraen** [comment]
There is also `=` check on Reaction `_run` method: https://github.com/reagent-project/reagent/blob/master/src/reagent/ratom.cljs#L436 This is called either directly from `handle-change` or through the queue.

But yes, looks like if the component is directly dereffing a Ratom, the component will be rendered even if reset/swap doesn't change the value.

Component dereffing a RAtom:
ratom reset/swap -> notify the render reaction -> queue-render

Component dereffing a Reaction depending on a RAtom:
reaction reset/swap -> notify reaction -> run -> IF result changed -> notify the render reaction -> queue-render

**Comment by shaunlebron** [comment]
@mike-thompson-day8 Not a bad memory for seven years ago!  I currently understand only how ratoms trigger a specific kind of reaction— the one created for a component’s render function.  Looking at your reference, I think that `=` is related to a lazily evaluated reaction (?), wherein a Deref notifies its watchers, but only if it has changed in value.

I don’t think the reaction created purely for a component’s render function is ever deref’d like that.  The only path to its auto-run function (i.e. batch/queue-render) is in `handle-change`, which I think only fires in response to:

* a dependent ratom being reset to a non-`identical?` value or,
* a dependent reaction being reset to a non-`=` value

> **NEW EDIT FOR THE DOCS?**
> “The ‘changed?’ semantics that make a component re-render are: `identical?` for ratoms, and `=` for reactions.

I don’t know yet if this is accurate or desirable, but that’s how I currently understand it.

@Deraen Thank you, I think you summarized it well, except for the last “reaction reset” is supposed to be “ratom reset”?— since the atom triggers the first reaction, which triggers the render reaction.
