### ISSUE TITLE
`simple-example` reports `undefined` function `mountComponentIntoNode`

### ISSUE THREAD

**Issue by matthewgertner** [reagent-project/reagent#59]
Apologies in advance since I am a total n00b to ClojureScript and Reagent, so this is probably due to my ignorance rather than a bug. I tried to run the `simple-example` you provide, and it fails when calling `nextComponent.mountComponentIntoNode` with the error `undefined is not a function`. I nosed around a bit in the generated JS, and it seems like it is expecting the component defined by the first parameter to `reagent/render-component` to have the `mountComponentIntoNode` method when compiled into JS. When I changed the code to match the example in the README (calling `reagent/render-component [simple-example]...` instead of passing in an anonymous function) it works fine.

Is the example out-of-date or do I have something configured wrongly?

**Comment by yogthos** [comment]
is this still an issue in 0.5?

**Comment by mike-thompson-day8** [comment]
This is now a very old issue, and it isn't clear if it is still a problem.  I'm going to close.  Happy to reopen if new information is provided.
