### ISSUE TITLE
Readme says npm i or add deps to .edn but (in my case at least) needed both

### ISSUE THREAD

**Issue by DeepReef11** [reagent-project/reagent#591]
Hi,

I've had troubles using Reagent because of this little or in the readme. I don't know if there are reasons to not install react and react-dom with npm but since it was saying or, I've skipped it and it caused errors. Maybe a little bit of clarification or replace 'or' by 'and' would prevent futur problems.

Readme.md:

And provide React using either npm (when using e.g. [Shadow-cljs](https://shadow-cljs.github.io/docs/UsersGuide.html))

npm i react react-dom

**_or_** by adding [Cljsjs](http://cljsjs.github.io/) React packages to your project:

[cljsjs/react "17.0.2-0"]
[cljsjs/react-dom "17.0.2-0"]

**Comment by Deraen** [comment]
It is "or" in purpose.

Shadow-cljs should work without cljsjs libs as it doesn't need even the extern files from those. Reagent test suite should be running Shadow-cljs build without cljsjs libs.

What kind of errors have you seen?
