### ISSUE TITLE
Generating components that are compatible with React.isValidClass

### ISSUE THREAD

**Issue by erikcw** [reagent-project/reagent#65]
I'm trying to interop with a 3rd React component that expects component passed to it to pass `React.isValidClass(my_component) === true`.

The source of that React method is:

```javascript
ReactDescriptor.isValidFactory = function(factory) {
  return typeof factory === 'function' &&
         factory.prototype instanceof ReactDescriptor;
};
```

Reagent seems to generate components as an object instead of a function. Here is my code:

```clojure
(ns mytest.core
  (:require [reagent.core :as reagent :refer [atom]])

(defn home []
  [:div [:h1 "Home Page placeholder"]])

(reagent/as-component (home)) ; => #<[object Object]>

(.isValidClass js/React (reagent/as-component (home))) ; => false

```

I've looked through the Reagent code base, and have been unable to find an API to generate a component that will pass this test.

React 0.11.2
Reagent 0.4.3

**Comment by mdhaney** [comment]
I came across a similar issue working with Rum.  I think it might be related to this:

https://gist.github.com/sebmarkbage/ae327f2eda03bf165261

I can look into this further if someone else isn't already working on it.

**Comment by holmsand** [comment]
Reagent 0.5.0-alpha3 has a new function – `reactify-component` – that takes a Reagent component (i.e a component function, or something returned by `create-class`), and returns an adapter that can be used in JSX (and passes the `React.isValidClass` test). The Reagent side will receive a single argument, the `props`, that is converted into a ClojureScript `map`.

You could also do that conversion yourself: create a plain React class (using `React.createClass`), and return e.g `(reagent/as-element [foo "arg"])` from the `render` method.

Note, however, that `React.isValidClass` is deprecated, and will probably go away in the future.

**Comment by mike-thompson-day8** [comment]
As v0.5.0 delivered this feature, can this issue can now be closed?
