### ISSUE TITLE
component-did-update doesn't pass previous state

### ISSUE THREAD

**Issue by tomconnors** [reagent-project/reagent#80]
I'm trying to detect a transition of a component's internal state, set with `reagent.core/set-state` but only the argv passed when constructing the component is passed to the `component-did-update` fn. Is there a way to easily detect specific state transitions that only use component-local state? If a means does not currently exist, is it possible to pass the component's previous state into that fn?

Only tangentially related, but worth mentioning: perhaps `set-state` should be `set-state!`?

**Comment by holmsand** [comment]
In Reagent 0.5.0-alpha3, there is now a `reagent.core/state-atom` that can be used instead of the one in `reagent.impl.component`.

**Comment by tomconnors** [comment]
Cool, thanks a lot!

**Comment by pandeiro** [comment]
Why is there a need to use a JS object w/ camel-cased lifecycle keys and the :mixins key?

In other words, why would this not work using merge with reagent/create-class to include a regular cljs map with :component-will-mount and :component-will-unmount keys?

**Comment by tomconnors** [comment]
I don't remember well what the reason was, but I think it's because `reagent/create-class` performs the vector to array/hashmap to js object conversion shallowly, or the snake-case to camelCase conversion shallowly, or, probably, both of those.

**Comment by pandeiro** [comment]
Thanks @tomconnors, but still neither of those would seem to prevent it (no need for :mixins at all, so vector/array wouldn't matter, and hyphen-to-camel being shallow also wouldn't matter, since these are at the top level anyway)... Anyway, food for thought.

**Comment by tomconnors** [comment]
Assuming what I posted above about shallowness is actually the case, the #js reader macro (or the equivalent-ish `clj->js` fn call) and camel case are needed when using mixins, because `componentDidMount` and the like are properties of the mixin object, not the class that's created, so they aren't actually top level when reagent sees them. And the functionality I described above did require a mixin, at least as far as I could tell.

**Comment by pandeiro** [comment]
@tomconnors Cheers, thanks for the explanation. I guess I don't understand what the functional difference between using :mixin and just merging the map is. I'll try to figure that out -- thanks again for your replies!

**Comment by mike-thompson-day8** [comment]
It looks to me as if this issue is resolved and can be closed?

**Comment by tomconnors** [comment]
Yep, using the reference in reagent.core works for me.

**Comment by mike-thompson-day8** [comment]
Excellent. Would you mind closing (I don't have perms)?
