### ISSUE TITLE
Value changes in <input type="range"/> not picked up on Windows Phone

### ISSUE THREAD

**Issue by Reefersleep** [reagent-project/reagent#82]
When trying out the demos at http://reagent-project.github.io/news/index.html on my windows phone, changes in sliders are not picked up - whenever I change a slider value, the demo does not react in any way.

My phone is a Nokia Lumia. I'm using Internet Explorer.

**Comment by marcloyal3** [comment]
I assume that since Reagent deals only with React not the actual DOM, all cross-browser issues are due to React, not Reagent. Makes sense?

**Comment by Reefersleep** [comment]
I guess so? :) Haven't had the chance to test whether using React in the same setting causes the same bug.

**Comment by mike-thompson-day8** [comment]
Is there more information available, or should this issue now be closed?

**Comment by yogthos** [comment]
This doesn't appear to be a Reagent specific issue, if there's more information indicating that this is the case we can reopen.
