### ISSUE TITLE
ajax GET strange behaviour.

### ISSUE THREAD

**Issue by huxley-source** [reagent-project/reagent#86]
I'm going to collect data every 10 seconds with the rest api and ajax. I would also like to download data when loaded the page. However, after 10 seconds ajax are called twice.

```
(def page-state (atom {}))


(defn error-handler [{:keys [status status-text]}]
  (.log js/console (str "something bad happened: " status " " status-text)))


(defn get-data []
  (do
    (.log js/console (str "update! " (js/Date.)))
    (GET "/api/blablabblabla.json" {:response-format :json
                                                     :handler         #(reset! page-state %)
                                                     :error-handler   error-handler
                                                     :keywords?       true})))


(defn page []
  (fn []
    (get-data)
    (js/setInterval get-data 10000)
    [:div
     [:p (str @page-state)]]))
```

Here is console log.

update! Wed Jan 07 2015 00:56:12 GMT+0100 (CET)
update! Wed Jan 07 2015 00:56:22 GMT+0100 (CET)
update! Wed Jan 07 2015 00:56:23 GMT+0100 (CET)
update! Wed Jan 07 2015 00:56:33 GMT+0100 (CET)
update! Wed Jan 07 2015 00:56:34 GMT+0100 (CET)

**Comment by Frozenlock** [comment]
Your `page` component is re-rendered every time you modify @page-state, which means the `get-data` function is called immediately after.

**Comment by huxley-source** [comment]
```
(get-data)

(defn page []
  (fn []
    (js/setInterval get-data 10000)
    [:div
     [:p (str @page-state)]]))
```

Even if a `get-page` is out of `page`, problem occurs.
How so I can solve it?

**Comment by Frozenlock** [comment]
Well, your `setInterval` is also called every time the `page` component is re-rendered. 
I would try putting it outside the component, just like `get-data`.

**Comment by mike-thompson-day8** [comment]
I think this can be closed.
