### ISSUE TITLE
Allow any atom to be reagent-ized

### ISSUE THREAD

**Issue by Frozenlock** [reagent-project/reagent#92]
I recently built [Entanglement](https://github.com/Frozenlock/entanglement) specifically to manipulate atoms. It was becoming clear, with all the cursors/lenses/wraps appearing everywhere, that there was an underlying problem trying to be solved there.

Anyhow...

With a few modifications in `ratom.cljs` , Reagent could be used with *any* atom construct, while making (IMO) the code simpler.

In the `ratom.cljs` namespace:
```clj

(declare ^:dynamic *in-ratom*)

(defn reagent-ize
  "Add the special Reagent sauce to an atom. Return the new and
  improved atom."
  [source-atom]
  (let [derefer (fn [this source-atom getter]
                  (if-not *in-ratom*
                    ;; if we are not already derefing from another ratom
                    (do (notify-deref-watcher! this)
                        (binding [*in-ratom* true]
                          (getter (-deref source-atom))))
                    ;; already in ratom: just get the value
                    (getter (-deref source-atom))))]
    (ent/entangle source-atom
                  (fn [value] value) ;; identity
                  (fn [_ new-val] new-val)
                  :derefer derefer)))


(defn atom
  "Like clojure.core/atom, except that it keeps track of derefs."
  [x & rest]
  (-> (apply cljs.core/atom x rest)
      (reagent-ize))) ;; <--- Special Reagent sauce
```

Following that, `cursors` could simply be this:

```clj
(defn cursor
  "Like a normal cursor, but make sure Reagent capture it, rather than
  any higher up atoms in the chain."
  [a path]
  (-> (ent/cursor a path)
      (reagent-ize)))  ;; <--- special Reagent sauce
```

I tested it in my own Reagent applications and it seems to work. The only thing bugging me is that it fails the tests (if I ran them correctly...).

I wanted to ask for opinions before spending any more time with this.

**Comment by Frozenlock** [comment]
@holmsand  Any chances you could take a look at this? I opened this issue before your last major update. If 0.5.0 is too advanced, perhaps it could be added in 0.6.0?

**Comment by holmsand** [comment]
@Frozenlock Looks interesting, but I'm not entirely sure what it is you want to achieve here… 

If you want to create an alias for a "non-Reagent atom", you can do this today just by setting up mutual add-watches between a Reagent atom and a clojure.core one, that keeps them in sync at all times. 

If you want to customize getters and setters, you can do that as well, using the new cursors in 0.5.0-alpha3. 

Or do you have another use-case altogether in mind?

**Comment by Frozenlock** [comment]
> If you want to customize getters and setters, you can do that as well, using the new cursors in 0.5.0-alpha3.

The customized getters and setters are tools targeted at atoms, not at Reagent *per se*. Every react-like library is re-implementing its own version of this. It's something users always need when interacting closely with atoms. 

IMO all the sugar contained in wraps and cursors should be kept to a minimum to leave Reagent as simple as possible. Reagent is feeling kinda big compared to say [Rum](https://github.com/tonsky/rum/blob/gh-pages/src/rum.cljs).


Using Entanglement (or something like it) gives us 2 benefits:
- All the atom manipulation logic is taken care elsewhere;
- *Any* atom can be used as a Reagent atom.

> If you want to create an alias for a "non-Reagent atom", you can do this today just by setting up mutual add-watches between a Reagent atom and a clojure.core one, that keeps them in sync at all times.

Correct! *But..*
- It's boiler plate code with delicate operations, especially if you want your atoms to by synced in both directions. It can quickly become dangerous if you also want to transform the data between the two atoms.
- It can be CPU/memory expensive. You'll notice that all the atoms generated by [Entanglement](https://github.com/Frozenlock/entanglement) use the getter/setter functions only when derefed and reset. On the contrary, synced atoms with watches will be triggered at every atom modification.

When Reagent makes the assumption we'll always use it to initiate an atom, it makes it a whole lot harder to use anything else. What if I'd like to use a [Javelin](https://github.com/tailrecursion/javelin)'s cell with Reagent?

I'm playing around with atoms kept in sync between the server and the client. Once it's done, I'd like to be able to simply add in code "Oh, by the way, I want this atom to be used with Reagent." 

I guess what I'm saying is that atoms can come in multiple shapes and colors and Reagent shouldn't make assumptions about that.

**Comment by holmsand** [comment]
@Frozenlock I can see the point about the boilerplate (but I can't really see how two-way add-watching would be expensive enough to be noticeable: reset! is quite cheap). So maybe some variant of reagent-ize may be warranted, if this is a common enough use case? Do you think it is common enough to be worth the extra API?

On cursors: what "sugar" is unnecessary?

**Comment by Frozenlock** [comment]
`reset!` might be cheap, but functions attached to the watch might not be. We can't really make assumptions as to what else is attached to the atoms, nor as to how they are synced. With the advent of react native, I can easily see atoms bound to underlying OS operations. I might want to spin off 500 atoms, but end up only derefing 10. The point is that by forcing the use of add-watch, we make many assumptions that could be avoided.

> Do you think it is common enough to be worth the extra API?

That's the thing; I want to *reduce* the API. I think Reagent should focus on what it's doing very well: 
making and binding components to atoms. All the atoms generation and tooling are a very different subject and should be in other libraries.

The change of arguments order in `cursor` that messes with @seancorfield (and probably others) production code is an example of the drawbacks of merging Reagent and atom tooling. It also means that any good atom tooling developed in Reagent is much less likely to be used elsewhere.

I don't know if you closely followed [reagent-cursor](https://github.com/reagent-project/reagent-cursor), but we fixed many bugs much more quickly than reagent.core. Independent libraries can also explore new things and slowly die without leaving a bloated Reagent API behind.

**Comment by holmsand** [comment]
reagent-cursor (and the old cursor code in Reagent) doesn't solve (IMHO, of course) the fundamental problem: how do you create a cursor that only makes components re-render when needed?

If you think that the argument order of reagent's cursor is wrong, then by all means don't use it. Or make a helper function that swaps the order.

**Comment by Frozenlock** [comment]
> reagent-cursor (and the old cursor code in Reagent) doesn't solve (IMHO, of course) the fundamental problem: how do you create a cursor that only makes components re-render when needed?

I know that, **that's the whole point behind this issue**: Allow any atom to be reagent-ized.

My minimum implementation at the top was making sure to not notify the deref watcher more than once, thus (hopefully) allowing all kinds of reagent atoms/cursors to be composable.

**Comment by holmsand** [comment]
I'm confused: you don't think that avoiding unnecessary re-rendering is worthwhile?

And you think that the argument order is wrong, but that it should not be changed?

I'm sorry, but I simply don't understand your complaints here.

**Comment by Frozenlock** [comment]
Of course avoiding unnecessary re-rendering is worthwhile.
What I want is a solution that can accept any atom, not just those created in Reagent.
No special atoms/cursors/wraps in Reagent with better performance. Instead, a smart way to incorporate any atom which hopefully allows the same performance.

Do you think it's possible?

The binding used in the example above shows how `notify-deref-watcher!` is called only once, even in the case of cursors/atoms constructed with other cursors/atoms.

If we follow this pattern, we don't have to have a special case for every RAtom, RCursors and all the other R[something]. Everything is an atom (with reagent sauce). We just have to consider that these atoms are composable.

Following this, can't the optimization be contained in make-reaction or elsewhere?

-- 

The point with the argument-order change was that it broke existing code. Were it a different, external libraries, it would be on them to decide whether to break existing code or if they should just create a new library. But with things as they are, we can't really seek any alternatives if we don't like any changes in the tools, because everything is tightly coupled in the core implementation.

After all, Reagent's description is:
>A **minimalistic** ClojureScript interface to React.js

**Comment by holmsand** [comment]
Just so we talk about the same thing: What I mean by "avoiding unnecessary re-rendering" is in cases like this

```clojure
(defonce state (atom {:name "some name"
                      :other 1}))

(defn show-name [name]
  [:div @name])

(defn some-comp []
  [:div
   (pr-str @state)
   [show-name (reagent/cursor state [:name])]])
```

Changes to `:other` in `state` should not cause `show-name` to re-render. I don't think that is possible with your proposal.

Also, the argument-order-change should not break any existing code – you should have gotten a deprecation warning. Didn't you?

**Comment by Frozenlock** [comment]
In what I propose, cursors, from the code point of view, are completely independent atoms.
Your case would be equivalent to this:
```clj
(defonce state (atom {:name "some name"
                      :other 1}))

(defonce state2 (atom {:name "some name"}))

(defn show-name [name]
  [:div @name])

(defn some-comp []
  [:div
   (pr-str @state)
   [show-name state2]])
```

I would expect Reagent to not re-render `show-name` considering it's a completely different atom, but I might be wrong on this; I just always assumed it would do the right thing when I used multiple atoms.

--

> Also, the argument-order-change should not break any existing code – you should have gotten a deprecation warning. Didn't you?

I never used reagent.core/cursor, but the deprecation warning is to indicate that eventually the existing code will not be working anymore, is it not? It really isn't a big deal, but it was to show how everything coupled in the core implementation isn't very practical, especially for newish things that might change quite a lot, like cursors.

**Comment by holmsand** [comment]
I don't see what "completely independent atoms" has to do with cursors.

**Comment by Frozenlock** [comment]
The code has no way of seeing that the cursor is sharing data with the original atom. From any function POV, a cursor is an atom like any other. (Like with `reagent-cursor` cursors.)

**Comment by holmsand** [comment]
reagent-cursor derefs the source atom, so any changes to the source will cause a re-render (even if the changes are outside the scope of the cursor). And it doesn't implement equality correctly. Both will lead to unnecessary re-rendering in my example. Try it.

**Comment by Frozenlock** [comment]
I know.
The deref will trigger the `notify-deref-watcher!`, which will cause the component to be registered with the atom for rendering.

And because the cursor in reagent-cursor doesn't have the added `*in-ratom*` binding I demonstrated at the top, it will register everything, including the original atom, causing the whole thing to re-render **as expected**.

This was the whole reason the standalone reagent-cursor couldn't be as efficient as the reagent.core one.

The addition shown here should solve this problem.

**Comment by holmsand** [comment]
Ok, now I (at least I think that I) see what you're trying to do.

But your code still won't avoid re-renders in my example (because you'll get equality wrong in your cursor).

There are some other issues as well:

1. Reagent's atom (and cursor) only registers with `notify-deref-watcher!` on `deref`, and not in `-swap!` and `-pr-writer`. Your code would mean a subtle change, that could cause some really hard-to-find bugs. 

2. Your cursor will call `getter` 3 times on every update, if I'm not mistaken (which I may very well be), and there is no caching of "parent cursors'" values. That makes your code much simpler than mine (in Reaction), but also limits use cases a bit (to very inexpensive getter functions).

3. There's no way of supporting the new generalized version of Reagent's cursor (where you can pass a function instead of an atom) with your code. The new version allows you to access an arbitrary number of other atoms in the getter, and (for example) combine values from many of them into one.

Also, simplifying the contract also means saying no to (at least some) future optimizations. For example: eventually I'd like to make evaluation of e.g cursors async, so that the getter functions are not run until they are needed (and not at `-notify-watches` time).

**Comment by mathiasp** [comment]
Did you have a look at https://github.com/tonsky/rum ? It's build to modify it's behaviour.

From the readme: 
"Rum comes with a couple of mixins which emulate behaviors known from quiescent, om and reagent. Developing your own mixin is also very simple."

or, as Nikita said here https://groups.google.com/forum/#!topic/clojurescript/JP71mw1BIYo

"The main idea is that I wanted to hack my own component’s behaviors, but both Om, Reagent and even Quiescent came with something built-in, and change that was impossible without rewriting internals."

Might be better than to bend reagent to your needs.

**Comment by Frozenlock** [comment]
> Ok, now I (at least I think that I) see what you're trying to do.

Yes, I get the impression you don't understand me, but I don't see how I can phrase it more clearly...
---->  Allow any atom to be reagent-ized

>
- Reagent's atom (and cursor) only registers with notify-deref-watcher! on deref, and not in -swap!..

Ok, so would something like this work?
https://www.refheap.com/97368

It calls the deref watcher only once, regardless of the number of layers of reagent atoms, and it doesn't call the deref watcher at all for the swap and pr-writer operations.

Is there anything else that prevents Reagent from accepting atoms?

--
> There's no way of supporting the new generalized version of Reagent's cursor (where you can pass a function instead of an atom) with your code. 

Yes and no.

- No, in the example I gave with the Entanglement cursor there's no way. IMO this would be the responsibility of another library: creating an atom from another atom is very different than creating an atom from arbitrary functions.

- Yes, if you can use *any* atom, then you can also use an implementation of cursor that allows arbitrary functions. (Tho I wouldn't call it a cursor...)

But the implementation of these tools is just a detail compared to what I'm asking here:
Allowing any atoms to be used.

Memoization and other optimizations are the responsibility of the tool maker.


--
@mathiasp I'm trying to prevent Reagent from bending away from its original promises. All these sugary atom manipulations are not what I would describe "minimal". If you look at ratom.cljs, you'll see they are a good chunk of the code. Allowing the use of any atoms would prevent the pressure to add yet more atom manipulation in reagent.core.

At the same time, we currently can't build any tools for Reagent, because everything is locked tight. Need something a little different than a cursor? Sorry mate, you need to make a PR and hope it will be accepted in the next release.

**Comment by marcloyal3** [comment]
I think "Locked tight" is good and aligned with Reagent's ideology, although I'm brand new to it so I should keep my mouth shut. 

On the other hand, I find the new cursor as function in latest Reagent to be just the right amount of flexibility. You could still implement bad patterns with it but it's not by itself promoting a culture of "anything goes." 

Having said that, I need to read this whole thread and history of discussion about cursors and atoms before I open my mouth again ;)

**Comment by tomconnors** [comment]
I'm with @Frozenlock - there's a lot of competing cursor/reactive atom implementations floating around and it would be nice as a user of Reagent to be able to easily use an alternative.

**Comment by mike-thompson-day8** [comment]
Say no to Cursors entirely and get a better architecture:  https://github.com/Day8/re-frame

**Comment by Frozenlock** [comment]
Except that accepting any atom opens the door to much more than simple cursors.

For example, when you talk about subscription:

> Yes, subscriptions abstract away (hide) the data source, like a Cursor, but they also allow for computation. To put that another way, they can create derived data from app-db (a Materialised View of app-db).

All of this could be done by reagent.core/cursor (with @holmsand  recent addition of the arbitrary function) or by some other IAtom implementation. The one advantage I see over random IAtom implementation, after a quick read, is the efficient update that will not try to re-run the getter function.

But then again, if you start with the assumption that derefing an atom might be expensive, then you can use other methods than equality of value to see if the Reagent atom changed since the last render. You could have a special Reagent field changing at every `reset!`. 

```clj
  IReset
  (-reset! [a new-value]
    (set! reagent-marker (uuid))
    (reset! source-atom new-value))
```
  
Reagent main API has always been the atom (and a single call to `render`). 
It's what made it so simple to use. 
It would make sense to continue in the same path.

(Terrific readme btw, @mike-thompson-day8 )

**Comment by mike-thompson-day8** [comment]
@Frozenlock I'm not sure my Readme is any good!!   If it had done its job, you'd have seen a flash of light and abandoned all further thought of using Cursors :-)

**Comment by tomconnors** [comment]
I just finished reading through it as well. Really cool stuff! I'm going to play with these ideas in the context of the (cursorful) app I've been developing and see how it feels in practice. 
I still like the idea of Reagent integrating well with the myriad atom implementations out there.

**Comment by marcloyal3** [comment]
@Frozenlock @holmsand @mike-thompson-day8 

That's cool but I'm afraid that it would make development of reusable Reagent components a bit tricky since you couldn't simply pass in cursors from the app's atoms into a 3rd party reusable Reagent component and expect the reusable component to know how to use that cursor since the cursor implementation and interface could be different than the Reagent cursor. We need one standard so we can all develop our comoonents to work with that one standard. Am I being naive?

**Comment by Frozenlock** [comment]
Not naive, but I don't think you really understand the difference between what's in reagent.core and everything else. There's not really any problem with 'difference in implementations'.

> (...) you couldn't simply pass in cursors from the app's atoms into a 3rd party reusable Reagent component and expect the reusable component to know how to use that cursor since the cursor implementation and interface could be different than the Reagent cursor. 

See [reagent-cursor](https://github.com/reagent-project/reagent-cursor): it created simple atoms that were accepted by ALL components. The only drawback was that it was less optimal than reagent.core/cursor because we didn't have access to some special sauce.

That's mostly what the whole idea of allowing any atom to be used in Reagent is about: being able to wrap the special sauce around an existing atom, instead of having to create it from reagent.core every time.

If Reagent were to accept any atom, then you can make a component for a vanilla atom, but someone else decide to pass it an hoplon cell (reagent-ized) and it still works.

One could also make an atom that fetches its data from a remote database. Reagent doesn't need to know where/how the data is taken. It just needs to be able to deref it.

If anything, it makes it a whole lot easier to make reusable component.

Here's an example:
```clj
(def app-db (atom {:a {:b "hello"}}))


(defn greeting-component [app-atom]
  [:div
   [:h1 (get-in @app-atom [:a :b])]])

(defn greeting-component [msg-atom]
  [:div
   [:h1 @msg-atom]])
```
The first component expects to be passed the whole app atom. You had to hardcode the path `[:a :b] into the very component, which makes it impossible to reuse.

The second just expects to be passed an atom containing the interesting data.
To match the second component expectation, one can use a cursor:

```clj
(def msg-atom (cursor app-db [:a :b]))

;; msg-atom implements IAtom and will act exactly like any other atom.
```
Or anything else that implements IAtom
```clj
(def app-db (atom {:z {:x ["hello" "allo"]}}))

(def msg-atom (entangle app-db
                        #(-> (get-in % [:z :x])
                             (first))))
```

Your component will work with anything that implements the basic atom protocols.

**Comment by marcloyal3** [comment]
I'm new to Clojure, so like I thought I shouldn't have opened my mouth :) Looking into Protocols now to understand how they work, as it seems a little magical without that understanding.

**Comment by JulianLeviston** [comment]
I wonder if freactive's rx might solve these issues.

**Comment by mike-thompson-day8** [comment]
@Frozenlock  as chief protagonist in this issue, I'm wondering what you'd like done with it.  Should it stay open?  Morph in some way?  Be closed?

**Comment by Frozenlock** [comment]
My suggestion holds, but I don't think it will see the light of day. (At least in the near term.)

**Comment by GetContented** [comment]
@Frozenlock yes, you'd like Reaction to be a prototcol that you could extend to anything, it seems. In the spirit of clojure, extending a set of lightweight abstractions to all kinds of things.
