### ISSUE TITLE
Kioo not working with reagent 0.5.0-alpha

### ISSUE THREAD

**Issue by jaen** [reagent-project/reagent#93]
When trying to use the alpha version of Reagent with Kioo templating it fails with an error like this:
```
Caused by: clojure.lang.ExceptionInfo: Referred var reagent.impl.template/as-component does not exist at line 1 file:/home/jaen/.m2/repository/kioo/kioo/0.4.1-SNAPSHOT/kioo-0.4.1-SNAPSHOT.jar!/kioo/reagent.cljs
```
And sure enough, Kioo refers to that var - https://github.com/ckirkendall/kioo/blob/master/src/kioo/reagent.cljs#L4

As far as I can tell it was renamed to `as-element` but with an alias for backward-compatibility,  the aliasing seems to be done only for `reagent.core` and not in `reagent.impl.template` though.  
Adding the alias in that namespace fixes the problem, but I'm not sure if it's solution you'd be content with, or maybe there should be a change on the Kioo side to not use the `as-component`/`as-element` function in the `reagent.impl.template` namespace but the one in `reagent.core` instead (if they are equivalent in how they function).

**Comment by seancorfield** [comment]
Sounds like Kioo should not rely on Reagent internals.

**Comment by holmsand** [comment]
I agree. Kioo should probably use `reagent.core/as-element` instead (or maybe `reagent.core/as-component` to keep supporting pre-0.5.0-Reagents). Otherwise it will probably break in the future, anyway.

**Comment by jaen** [comment]
So they are equivalent in functionality and there's no reason to use the private one over the one in `reagent.core`, yes?
If so, I'll file an appropriate issue there.

**Comment by city41** [comment]
yup, the core one just calls the one in template: https://github.com/reagent-project/reagent/blob/master/src/reagent/core.cljs#L41

**Comment by jaen** [comment]
Gotcha, I'll report issue with kioo then, thanks : )
