### ISSUE TITLE
Local state and arguments render weirdness

### ISSUE THREAD

**Issue by tatut** [reagent-project/reagent#97]
Hope I am explaining this correctly.

I ran into a problem with having a component that received as arguments a list of items to render (deref'd from an atom by the containing component). The component also used local state (using the let-and-return-a-0-arity-fn style). 

The component would not receive the updated arguments. Adding logging to rendering showed that the render function was called but did not receive the updated atom value passed in by the parent.
The state changes in the components local state was reflected in the render ok.

I looked around and the return-create-class-trick seems to make it work.
See for a full example demonstrating the problem: https://gist.github.com/tatut/e7e5e7e2becf56b8ef7b

**Comment by city41** [comment]
The "0-arity-fn style" is the issue, the function you return actually needs to take the same number of parameters as the outer function. Checkout the "rookie mistake" in the [form 2 section on the wiki](https://github.com/reagent-project/reagent/wiki/Creating-Components#form-2--a-function-returning-a-function)

**Comment by tatut** [comment]
*bangs self on forehead*

Wow! Thanks for the quick reply... I'm glad it was such a simple mistake on my end :)

**Comment by rhacker** [comment]
Sorry for digging the old topic, maybe I'm wrong but I still have problem with form2 reagent. What I'm trying is 
```clojure
(defn outer [x]
  (fn [x] [:div (str x)]))
```

the value of x in inner function is nil.

**Comment by mbertheau** [comment]
@rhacker How is `outer` called?

**Comment by mike-thompson-day8** [comment]
People, this is not a help forum.  This is a place for reporting issues and discussing new features.  

Please go to the help forums detailed here:
https://github.com/reagent-project/reagent/blob/master/CONTRIBUTING.md#support-questions

**Comment by rhacker** [comment]
@mike-thompson-day8 thanks for reminding.
@mbertheau thanks, I called it wrong `(outer arg)`, it should be called `[outer arg]`. Thanks for asking anyway.
