### ISSUE TITLE
(browser-repl) throwing an exception

### ISSUE THREAD

**Issue by ajmorgan** [reagent-project/reagent#98]
after running `lein repl`, followed by `(browser-repl)`, the following exception occurs:

java.lang.IllegalStateException: Can't change/establish root binding of: *cljs-repl-options* with set

**Comment by mike-thompson-day8** [comment]
Adam, that's just not enough information and this is the wrong place to be asking.  

Best to ask here:  https://groups.google.com/forum/#!forum/reagent-project

For details on correct project setup, look at these examples:
  - https://github.com/reagent-project
  - https://github.com/gadfly361/reagent-figwheel

**Comment by ajmorgan** [comment]
My apologies, this happens on a fresh reagent project created by the reagent template.  I should have put the issue there.
